<a href="https://colab.research.google.com/github/ThanhB18059162022/MMRec/blob/dev/preprocessing/0rating2inter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## preprocessing/
Tiền xử lý bước 0
Bước này tạo ra 3 file:
- i_id_mapping.csv: file map lại id của sản phẩm vì đã chuyển sang số
- u_id_mapping.csv: file map lại id của người dùng vì đã chuyển sang số
- sports14-indexed.inter: file tương tác tương tự file csv nhưng id của người và sản phẩm đã chuyển sang số

# 从ratings_Sports_and_Outdoors.csv文件中提取U-I交互图, 5-core后重新编号
- Extracting U-I interactions and performing 5-core, re-indexing
- dataset located at: http://jmcauley.ucsd.edu/data/amazon/links.html, rating only file in "Small" subsets for experimentation

## Link data: https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/links.html

Tìm file csv Sports and Outdoors "ratings only (3,268,695 ratings)"

## data chưa filter 5-core (dùng code này để xử lý): https://snap.stanford.edu/data/amazon/productGraph/item_dedup.csv

## data này filter 5-core rồi "https://snap.stanford.edu/data/amazon/productGraph/categoryFiles/ratings_Sports_and_Outdoors.csv

In [1]:
import os, csv
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
!wget https://snap.stanford.edu/data/amazon/productGraph/categoryFiles/ratings_Sports_and_Outdoors.csv

--2026-03-11 09:44:17--  https://snap.stanford.edu/data/amazon/productGraph/categoryFiles/ratings_Sports_and_Outdoors.csv
Resolving snap.stanford.edu (snap.stanford.edu)... 171.64.75.80
Connecting to snap.stanford.edu (snap.stanford.edu)|171.64.75.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133182998 (127M) [text/csv]
Saving to: ‘ratings_Sports_and_Outdoors.csv’

ratings_Sports_and_ 100%[===================>] 127.01M  38.7MB/s    in 4.8s

2026-03-11 09:44:22 (26.2 MB/s) - ‘ratings_Sports_and_Outdoors.csv’ saved [133182998/133182998]

In [35]:
# !wget https://snap.stanford.edu/data/amazon/productGraph/item_dedup.csv

--2026-03-11 08:53:05--  https://snap.stanford.edu/data/amazon/productGraph/item_dedup.csv
Resolving snap.stanford.edu (snap.stanford.edu)... 171.64.75.80
Connecting to snap.stanford.edu (snap.stanford.edu)|171.64.75.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3366981927 (3.1G) [text/csv]
Saving to: ‘item_dedup.csv’

item_dedup.csv      100%[===================>]   3.14G  43.6MB/s    in 2m 4s

2026-03-11 08:55:10 (25.9 MB/s) - ‘item_dedup.csv’ saved [3366981927/3366981927]

In [4]:
!cp "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec/data/0rating2inter/ratings_Sports_and_Outdoors.csv" "ratings_Sports_and_Outdoors.csv"

In [18]:
df = pd.read_csv('ratings_Sports_and_Outdoors.csv', names=['userID', 'itemID', 'rating', 'timestamp'], header=None)

In [9]:
# df = pd.read_csv('item_dedup.csv', names=['userID', 'itemID', 'rating', 'timestamp'], header=None)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3268694 entries, 0 to 3268693
Data columns (total 4 columns):
 #   Column          Dtype
---  ------          -----
 0   A3PMSRCL80KSA1  object
 1   0000031852      object
 2   4.0             float64
 3   1388275200      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 99.8+ MB

In [7]:
# !wget "https://mcauleylab.ucsd.edu/public_datasets/data/amazon_2023/benchmark/5core/rating_only/Sports_and_Outdoors.csv.gz"

In [10]:
# !gunzip Sports_and_Outdoors.csv.gz

In [11]:
# df1 = pd.read_csv('/content/Sports_and_Outdoors.csv')

In [14]:
# 3472019-3268693

203326

In [12]:
# df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3472020 entries, 0 to 3472019
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   user_id      object
 1   parent_asin  object
 2   rating       float64
 3   timestamp    int64
dtypes: float64(1), int64(1), object(2)
memory usage: 106.0+ MB

In [4]:
df.head(3)

                        user_id parent_asin  rating      timestamp
0  AEO4M665ZOCBF7HEFRMTUDHLSB5Q  B004JU0H6O     4.0  1655859477958
1  AEO4M665ZOCBF7HEFRMTUDHLSB5Q  B082WJTFRR     5.0  1655860079499
2  AEO4M665ZOCBF7HEFRMTUDHLSB5Q  B08FZJ3YHH     4.0  1655860597696

In [14]:
# !rm -rf "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec/code/data/data"

In [35]:
PATH = "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec/"

In [15]:
!mkdir "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec/data/0rating2inter"

In [16]:
!cp "ratings_Sports_and_Outdoors.csv" "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec/data/0rating2inter/ratings_Sports_and_Outdoors.csv"

In [17]:
!cp "./item_dedup.csv" "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec/data/0rating2inter/item_dedup.csv"

In [32]:
# !cp "{PATH}/ratings_Sports_and_Outdoors.csv" "."

In [ ]:
# os.chdir('/home/enoche/MMRec/Sports14')
# os.getcwd()

## 先5-core过滤
## 5-core filtering

In [21]:
print(f'shape: {df.shape}')
df[:5]

shape: (3268695, 4)

           userID      itemID  rating   timestamp
0  A3PMSRCL80KSA1  0000031852     4.0  1388275200
1  A1SNLWGLFXD70K  0000031852     4.0  1392940800
2  A1KJ4CVG87QW09  0000031852     4.0  1389657600
3    AA9ITO6ZLZW6  0000031852     5.0  1399507200
4    APJ5ULJ1RMZ4  0000031852     1.0  1398556800

In [20]:
df_bak = df.copy()

In [22]:
# Bỏ giá trị null với trùng
learner_id, course_id, tmstmp_str = 'userID', 'itemID', 'timestamp'

df.dropna(subset=[learner_id, course_id, tmstmp_str], inplace=True)
df.drop_duplicates(subset=[learner_id, course_id, tmstmp_str], inplace=True)
print(f'After dropped: {df.shape}')
df[:3]

After dropped: (3268695, 4)

           userID      itemID  rating   timestamp
0  A3PMSRCL80KSA1  0000031852     4.0  1388275200
1  A1SNLWGLFXD70K  0000031852     4.0  1392940800
2  A1KJ4CVG87QW09  0000031852     4.0  1389657600

Trong bài toán GCN và Hệ thống gợi ý, mục đích của code này là loại bỏ những người dùng và sản phẩm có quá ít tương tác để giảm độ nhiễu và giải quyết vấn đề "dữ liệu quá thưa thớt" (Data Sparsity). Bỏ những dòng mà số cặp userID-itemID	< 5.

In [23]:
from collections import Counter
import numpy as np

min_u_num, min_i_num = 5, 5

# Hàm này có nhiệm vụ tìm ra danh sách các ID "không hợp lệ" dựa trên số lượng tương tác.
def get_illegal_ids_by_inter_num(df, field, max_num=None, min_num=None):
    if field is None:
        return set()
    if max_num is None and min_num is None:
        return set()

    max_num = max_num or np.inf
    min_num = min_num or -1

    ids = df[field].values
    inter_num = Counter(ids)
    ids = {id_ for id_ in inter_num if inter_num[id_] < min_num or inter_num[id_] > max_num}
    print(f'{len(ids)} illegal_ids_by_inter_num, field={field}')

    return ids

# Đây là hàm quan trọng nhất, thực hiện lọc dữ liệu theo vòng lặp cho đến khi mọi User và Item đều đạt chuẩn "5-core".
def filter_by_k_core(df):
    while True:
        ban_users = get_illegal_ids_by_inter_num(df, field=learner_id, max_num=None, min_num=min_u_num)
        ban_items = get_illegal_ids_by_inter_num(df, field=course_id, max_num=None, min_num=min_i_num)
        if len(ban_users) == 0 and len(ban_items) == 0:
            return

        dropped_inter = pd.Series(False, index=df.index)
        if learner_id:
            dropped_inter |= df[learner_id].isin(ban_users)
        if course_id:
            dropped_inter |= df[course_id].isin(ban_items)
        print(f'{len(dropped_inter)} dropped interactions')
        df.drop(df.index[dropped_inter], inplace=True)

## lọc dữ liệu theo k-core
Hiện tại là 5 core file ratings_Sports_and_Outdoors.csv tác giả đã lọc sẵn 5 core rồi

In [26]:
print(f'k-core shape: {df_bak.shape}')
print(f'shape before k-core: {df_bak.shape}')

k-core shape: (3268695, 4)
shape before k-core: (3268695, 4)

In [25]:
k_core = 5
filter_by_k_core(df)
print(f'k-core shape: {df.shape}')
print(f'shape after k-core: {df.shape}')
df[:2]

1906153 illegal_ids_by_inter_num, field=userID
376127 illegal_ids_by_inter_num, field=itemID
3268695 dropped interactions
22213 illegal_ids_by_inter_num, field=userID
54919 illegal_ids_by_inter_num, field=itemID
589029 dropped interactions
18323 illegal_ids_by_inter_num, field=userID
3743 illegal_ids_by_inter_num, field=itemID
422478 dropped interactions
2298 illegal_ids_by_inter_num, field=userID
4388 illegal_ids_by_inter_num, field=itemID
349749 dropped interactions
3331 illegal_ids_by_inter_num, field=userID
639 illegal_ids_by_inter_num, field=itemID
326238 dropped interactions
579 illegal_ids_by_inter_num, field=userID
1012 illegal_ids_by_inter_num, field=itemID
311188 dropped interactions
897 illegal_ids_by_inter_num, field=userID
169 illegal_ids_by_inter_num, field=itemID
305054 dropped interactions
155 illegal_ids_by_inter_num, field=userID
308 illegal_ids_by_inter_num, field=itemID
300866 dropped interactions
301 illegal_ids_by_inter_num, field=userID
47 illegal_ids_by_inter_num, field=itemID
299031 dropped interactions
50 illegal_ids_by_inter_num, field=userID
79 illegal_ids_by_inter_num, field=itemID
297646 dropped interactions
87 illegal_ids_by_inter_num, field=userID
11 illegal_ids_by_inter_num, field=itemID
297132 dropped interactions
16 illegal_ids_by_inter_num, field=userID
24 illegal_ids_by_inter_num, field=itemID
296741 dropped interactions
24 illegal_ids_by_inter_num, field=userID
1 illegal_ids_by_inter_num, field=itemID
296581 dropped interactions
1 illegal_ids_by_inter_num, field=userID
8 illegal_ids_by_inter_num, field=itemID
296481 dropped interactions
8 illegal_ids_by_inter_num, field=userID
0 illegal_ids_by_inter_num, field=itemID
296445 dropped interactions
0 illegal_ids_by_inter_num, field=userID
5 illegal_ids_by_inter_num, field=itemID
296413 dropped interactions
5 illegal_ids_by_inter_num, field=userID
0 illegal_ids_by_inter_num, field=itemID
296393 dropped interactions
0 illegal_ids_by_inter_num, field=userID
3 illegal_ids_by_inter_num, field=itemID
296373 dropped interactions
4 illegal_ids_by_inter_num, field=userID
0 illegal_ids_by_inter_num, field=itemID
296361 dropped interactions
0 illegal_ids_by_inter_num, field=userID
1 illegal_ids_by_inter_num, field=itemID
296345 dropped interactions
1 illegal_ids_by_inter_num, field=userID
0 illegal_ids_by_inter_num, field=itemID
296341 dropped interactions
0 illegal_ids_by_inter_num, field=userID
0 illegal_ids_by_inter_num, field=itemID
k-core shape: (296337, 4)
shape after k-core: (296337, 4)

             userID      itemID  rating   timestamp
564    AIXZKN4ACSKI  1881509818     5.0  1390694400
565  A1L5P841VIO02V  1881509818     5.0  1328140800

## Re-index

In [27]:
df.reset_index(drop=True, inplace=True)

In [28]:
learner_id

'userID'

Đoạn code này thực hiện bước Re-indexing (Đánh số lại ID). Đây là một bước "sống còn" sau khi bạn đã lọc dữ liệu (K-core).Nói một cách đơn giản: Nó chuyển các ID loằng ngoằng của Amazon (ví dụ: A3SG769SK) thành các con số nguyên liên tiếp ($0, 1, 2, 3...$) để máy tính có thể xử lý nhanh và dùng làm chỉ mục (index) cho ma trận Embedding.

In [29]:
i_mapping_file = 'i_id_mapping.csv'
u_mapping_file = 'u_id_mapping.csv'

splitting = [0.8, 0.1, 0.1]
uid_field, iid_field = learner_id, course_id

# 1. Khai báo và lấy danh sách ID duy nhất
uni_users = pd.unique(df[uid_field])
uni_items = pd.unique(df[iid_field])

# 2. Tạo "Từ điển" ánh xạ (Mapping Dictionary)
# start from 0
u_id_map = {k: i for i, k in enumerate(uni_users)}
i_id_map = {k: i for i, k in enumerate(uni_items)}

# 3. Cập nhật trực tiếp vào dữ liệu (Mapping)
df[uid_field] = df[uid_field].map(u_id_map)
df[iid_field] = df[iid_field].map(i_id_map)
df[uid_field] = df[uid_field].astype(int)
df[iid_field] = df[iid_field].astype(int)

# 4. Lưu lại "Cuốn sổ địa chỉ" (Mapping File)
# dump
rslt_dir = './'
u_df = pd.DataFrame(list(u_id_map.items()), columns=['user_id', 'userID'])
i_df = pd.DataFrame(list(i_id_map.items()), columns=['asin', 'itemID'])

u_df.to_csv(os.path.join(rslt_dir, u_mapping_file), sep='\t', index=False)
i_df.to_csv(os.path.join(rslt_dir, i_mapping_file), sep='\t', index=False)
print(f'mapping dumped...')

mapping dumped...

In [36]:
!cp "i_id_mapping.csv" "{PATH}/data/0rating2inter/"
!cp "u_id_mapping.csv" "{PATH}/data/0rating2inter/"

Đoạn code này là bước chuẩn bị các "điểm cắt" (split points) để chia tập dữ liệu gốc thành 3 phần: Train (Huấn luyện), Validation (Kiểm tra/Tối ưu) và Test (Thử nghiệm).

Trong nghiên cứu của bạn, việc chia này cực kỳ quan trọng để đảm bảo mô hình SMORE không "học vẹt" mà thực sự có khả năng dự đoán sản phẩm mới.

In [37]:

# =========2. splitting
print(f'splitting ...')
# 1. Chuẩn hóa tỷ lệ (Normalization)
tot_ratio = sum(splitting) # Tổng tỷ lệ (ví dụ: 0.8 + 0.1 + 0.1 = 1.0)
# remove 0.0 in ratios
ratios = [i for i in splitting if i > .0] # Loại bỏ các phần tử bằng 0 (nếu có)
ratios = [_ / tot_ratio for _ in ratios] # Đảm bảo tổng các tỷ lệ luôn bằng 1
# 2. Tạo điểm cắt bằng Tổng tích lũy (Cumulative Sum)
split_ratios = np.cumsum(ratios)[:-1]

#df[tmstmp_str] = df[tmstmp_str].map(lambda x: datetime.strptime(x, "%Y-%m-%dT%H:%M:%SZ"))
split_ratios

splitting ...

array([0.8, 0.9])


Tại sao lại là [0.8, 0.9]?
Vì để chia một cái bánh thành 3 phần, bạn chỉ cần 2 nhát cắt:

Nhát 1 tại vị trí 80%: Mọi thứ trước đó là Train.

Nhát 2 tại vị trí 90%: Mọi thứ từ 80% đến 90% là Validation.

Phần còn lại (từ 90% đến 100%) mặc định là Test.

Gemini đã nói
Đoạn code này thực hiện bước Chia dữ liệu theo thời gian (Temporal Splitting).

Trong hệ thống gợi ý, đây là cách chia dữ liệu "chuẩn" nhất vì nó mô phỏng đúng thực tế: Bạn dùng dữ liệu trong quá khứ để huấn luyện mô hình và dùng dữ liệu mới nhất (tương lai) để kiểm tra xem mô hình dự đoán có đúng không.

In [38]:
ts_id = 'timestamp'

# 1. Xác định "Mốc thời gian" để cắt
# Cơ chế: Hàm np.quantile sẽ tìm ra giá trị thời gian (timestamp) tại các điểm 80% và 90% của toàn bộ dữ liệu.
# Ví dụ: Nếu dữ liệu của bạn kéo dài từ năm 2020 đến 2025, nó sẽ tính toán và trả về:
# split_timestamps[0]: Ngày nào đó vào năm 2024 (mốc 80%).
# split_timestamps[1]: Ngày nào đó vào đầu năm 2025 (mốc 90%).

split_timestamps = list(np.quantile(df[ts_id], split_ratios))

# 2. Tách dữ liệu thành 3 tập
# Train (0): Những tương tác xảy ra trước mốc 80%. Đây là dữ liệu mô hình SMORE sẽ "học".
# Validation (1): Những tương tác xảy ra trong khoảng 80% - 90%. Dùng để chỉnh các tham số (Hyperparameters).
# Test (2): Những tương tác mới nhất (10% cuối cùng). Đây là bài thi cuối kỳ để đánh giá độ chính xác của mô hình.
# get df training dataset unique users/items
df_train = df.loc[df[ts_id] < split_timestamps[0]].copy()
df_val = df.loc[(split_timestamps[0] <= df[ts_id]) & (df[ts_id] < split_timestamps[1])].copy()
df_test = df.loc[(split_timestamps[1] <= df[ts_id])].copy()

# 3. Đánh nhãn (Labeling) và Gộp lại
# Thay vì lưu thành 3 file riêng biệt, code này gộp chúng lại thành một bảng duy nhất nhưng thêm một cột "nhãn" (x_label).
# Dòng nào có số 0 -> Thuộc tập Train.
# Dòng nào có số 2 -> Thuộc tập Test.
# Việc này giúp việc quản lý dữ liệu gọn gàng hơn.
# Định dạng .inter: Đây là định dạng phổ biến trong các framework GCN (như RecBole hoặc SMORE).
# Thực chất nó là một file văn bản bình thường nhưng các cột cách nhau bằng dấu Tab (\t).
x_label, rslt_file = 'x_label', 'sports14-indexed.inter'
df_train[x_label] = 0
df_val[x_label] = 1
df_test[x_label] = 2
temp_df = pd.concat([df_train, df_val, df_test])
temp_df = temp_df[[learner_id, course_id, 'rating', ts_id, x_label]]
print(f'columns: {temp_df.columns}')

temp_df.columns = [learner_id, course_id, 'rating', ts_id, x_label]

temp_df.to_csv(os.path.join(rslt_dir, rslt_file), sep='\t', index=False)
temp_df[:5]
#print('done!')

columns: Index(['userID', 'itemID', 'rating', 'timestamp', 'x_label'], dtype='object')

   userID  itemID  rating   timestamp  x_label
0       0       0     5.0  1390694400        0
1       1       0     5.0  1328140800        0
2       2       0     4.0  1330387200        0
3       3       0     4.0  1328400000        0
4       4       0     4.0  1366675200        0

In [39]:
!cp "{rslt_file}" "{PATH}/data/0rating2inter/{rslt_file}"

## Reload

In [40]:
indexed_df = pd.read_csv(rslt_file, sep='\t')
print(f'shape: {indexed_df.shape}')
indexed_df[:4]

shape: (296337, 5)

   userID  itemID  rating   timestamp  x_label
0       0       0     5.0  1390694400        0
1       1       0     5.0  1328140800        0
2       2       0     4.0  1330387200        0
3       3       0     4.0  1328400000        0

In [41]:
u_uni = indexed_df[learner_id].unique()
c_uni = indexed_df[course_id].unique()

print(f'# of unique learners: {len(u_uni)}')
print(f'# of unique courses: {len(c_uni)}')

print('min/max of unique learners: {0}/{1}'.format(min(u_uni), max(u_uni)))
print('min/max of unique courses: {0}/{1}'.format(min(c_uni), max(c_uni)))

# of unique learners: 35598
# of unique courses: 18357
min/max of unique learners: 0/35597
min/max of unique courses: 0/18356