<a href="https://colab.research.google.com/github/ThanhB18059162022/MMRec/blob/dev/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## prevent timeout
```javascript
function ClickConnect(){
console.log("Working");
document.querySelector("#top-toolbar > colab-connect-button").shadowRoot.querySelector("#connect").click();
}
const inter = setInterval(ClickConnect,60000)
```
## undo
```javascript
clearInterval(inter)
```

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install lmdb

Collecting lmdb
  Downloading lmdb-1.8.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Downloading lmdb-1.8.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.2/301.2 kB 10.2 MB/s eta 0:00:00
Installing collected packages: lmdb
Successfully installed lmdb-1.8.1

In [ ]:
!pip install torch-scatter -f https://data.pyg.org/whl/torch-$(python -c "import torch;print(torch.__version__)").html

Looking in links: https://data.pyg.org/whl/torch-2.10.0+cu128.html
Collecting torch-scatter
  Downloading https://data.pyg.org/whl/torch-2.10.0%2Bcu128/torch_scatter-2.1.2%2Bpt210cu128-cp312-cp312-linux_x86_64.whl (10.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 115.1 MB/s eta 0:00:00
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.1.2+pt210cu128

In [1]:
import os

In [ ]:
PATH = "/content/drive/MyDrive/Colab Notebooks/CTH001/MMRec"

In [ ]:
# !pip freeze > requirements.ggcolab.txt

In [ ]:
# !cp "requirements.ggcolab.txt" "{PATH}/requirements.ggcolab.txt"

In [ ]:
!rm -rf MMRec

In [ ]:
!git clone https://github.com/ThanhB18059162022/MMRec.git -b dev

Cloning into 'MMRec'...
remote: Enumerating objects: 591, done.
remote: Counting objects: 100% (332/332), done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 591 (delta 259), reused 209 (delta 193), pack-reused 259 (from 2)
Receiving objects: 100% (591/591), 901.00 KiB | 3.72 MiB/s, done.
Resolving deltas: 100% (333/333), done.

In [ ]:
# Copy qua /content: Thư mục /content nằm trên ổ cứng SSD nội bộ của máy ảo Colab.
# Tốc độ đọc dữ liệu tại đây nhanh hơn gấp 10 - 50 lần so với đọc trực tiếp từ Drive.
!cp -r "{PATH}/code/data/sports" "MMRec/data/sports"

In [ ]:
os.chdir("MMRec/src")

In [ ]:
import torch

print(f"Is CUDA available? {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"Current Device Index: {torch.cuda.current_device()}")
else:
    print("PyTorch is running on CPU.")

Is CUDA available? True
GPU Name: Tesla T4
Current Device Index: 0

In [ ]:
# Thiết lập số epoch mong muốn tại đây
new_epochs = 10

# Sử dụng f-string để truyền biến vào lệnh sed
!sed -i "s/epochs: [0-9]*/epochs: {new_epochs}/g" /content/MMRec/src/configs/overall.yaml

# Kiểm tra lại
print(f"Đã đổi epochs thành: {new_epochs}")
!grep "epochs:" /content/MMRec/src/configs/overall.yaml

Đã đổi epochs thành: 10
epochs: 10

In [ ]:
!pip install nvitop

Collecting nvitop
  Downloading nvitop-1.6.2-py3-none-any.whl.metadata (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 3.1 MB/s eta 0:00:00
Requirement already satisfied: nvidia-ml-py<13.591.0a0,>=11.450.51 in /usr/local/lib/python3.12/dist-packages (from nvitop) (13.590.48)
Requirement already satisfied: psutil>=5.6.6 in /usr/local/lib/python3.12/dist-packages (from nvitop) (5.9.5)
Downloading nvitop-1.6.2-py3-none-any.whl (215 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.5/215.5 kB 11.1 MB/s eta 0:00:00
Installing collected packages: nvitop
Successfully installed nvitop-1.6.2

In [ ]:
# Xài terminal thay vì cell
!nvitop

)07=Mon Mar 16 07:02:55 2026
╒═════════════════════════════════════════════════════════════════════════════╕
│ NVITOP 1.6.2       Driver Version: 580.82.07      CUDA Driver Version: 13.0 │
├───────────────────────────────┬──────────────────────┬──────────────────────┤
│ GPU  Name        Persistence-M│ Bus-Id        Disp.A │ Volatile Uncorr. ECC │
│ Fan  Temp  Perf  Pwr:Usage/Cap│         Memory-Usage │ GPU-Util  Compute M. │
╞═══════════════════════════════╪══════════════════════╪══════════════════════╡
│   0  Tesla T4             Off │ 00000000:00:04.0 Off │                    0 │
│ N/A   34C   P8      12W / 70W │   2.88MiB / 15360MiB │      0%      Default │
╘═══════════════════════════════╧══════════════════════╧══════════════════════╛
[ CPU: █████████████████████████████ MAX ]  ( Load Average:  2.34  0.70  0.29 )
[ MEM: ███▉ 13.2%          USED: 1.36GiB ]  [ SWP: ▏ 0.0%                     ]

╒═════════════════════════════════════════════════════════════════════════════╕
│ Processes:                                                root@27eb2c229d58 │
│ GPU     PID      USER  GPU-MEM %SM %GMBW  %CPU  %MEM  TIME  COMMAND         │
╞═════════════════════════════════════════════════════════════════════════════╡
│  No running processes found                                                 │
╘═════════════════════════════════════════════════════════════════════════════╛
ERROR: Failed to initialize `curses` (curs_set() returned ERR)

In [ ]:
os.chdir("src")

NameError: name 'os' is not defined

In [5]:
# !python main.py -d sports -m SMORE

In [9]:
import subprocess
import sys

# sys.executable sẽ tự động trỏ đến đúng venv của bạn
command = [sys.executable, "main.py", "-d", "sports", "-m", "SMORE"]

try:
    process = subprocess.Popen(
        command, 
        stdout=subprocess.PIPE, 
        stderr=subprocess.STDOUT, 
        text=True,
        encoding='utf-8'
    )
    print(f"--- Đang chạy với Python từ: {sys.executable} ---")
    
    for line in iter(process.stdout.readline, ""):
        print(line, end="")
        
except KeyboardInterrupt:
    print("\n[!] Đang dừng...")
    process.terminate()

--- Đang chạy với Python từ: c:\projects\MMRec\.venv\Scripts\python.exe ---
25 Mar 16:25    INFO ██Server: 	Thanhvc-stg-00
25 Mar 16:25    INFO ██Dir: 	c:\projects\MMRec\src

25 Mar 16:25    INFO
gpu_id=0
use_gpu=True
seed=[999]
data_path=../data/
inter_splitting_label=x_label
filter_out_cod_start_users=True
is_multimodal_model=True
checkpoint_dir=saved
save_recommended_topk=True
recommend_topk=recommend_topk/
embedding_size=64
weight_decay=0.0
req_training=True
epochs=1
stopping_step=20
train_batch_size=2048
learner=adam
learning_rate=0.001
learning_rate_scheduler=[0.96, 50]
eval_step=1
training_neg_sample_num=1
use_neg_sampling=True
use_full_sampling=False
NEG_PREFIX=neg__
USER_ID_FIELD=userID
ITEM_ID_FIELD=itemID
TIME_FIELD=timestamp
field_separator=
metrics=['Recall', 'NDCG', 'Precision', 'MAP']
topk=[5, 10, 20, 50]
valid_metric=Recall@20
eval_batch_size=4096
use_raw_features=False
max_txt_len=32
max_img_size=256
vocab_size=30522
type_vocab_size=2
hidden_size=4
pad_token_id=0
max_position_embeddings=512
layer_norm_eps=1e-12
hidden_dropout_prob=0.1
end2end=False
hyper_parameters=['seed', 'n_ui_layers', 'image_knn_k', 'text_knn_k', 'reg_weight', 'dropout_rate']
inter_file_name=sports.inter
vision_feature_file=image_feat.npy
text_feature_file=text_feat.npy
user_graph_dict_file=user_graph_dict.npy
n_ui_layers=[3]
n_layers=1
lambda_coeff=0.9
reg_weight=[0.0001]
cl_loss=0.03
temperature=0.2
image_knn_k=[10]
text_knn_k=[10]
dropout_rate=[0]
model=SMORE
dataset=sports
valid_metric_bigger=True
device=cpu


25 Mar 16:25    INFO sports
The number of users: 35598
Average actions of users: 8.324540704533963
The number of items: 18357
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465195454304%
25 Mar 16:25    INFO
====Training====
sports
The number of users: 35598
Average actions of users: 6.13542895668296
The number of items: 18352
Average actions of items: 11.901100697471666
The number of inters: 218409
The sparsity of the dataset: 99.96656806366236%
25 Mar 16:25    INFO
====Validation====
sports
The number of users: 35598
Average actions of users: 1.0646384628349908
The number of items: 13342
Average actions of items: 2.840578623894469
The number of inters: 37899
The sparsity of the dataset: 99.99202039826986%
25 Mar 16:25    INFO
====Testing====
sports
The number of users: 35598
Average actions of users: 1.1244732850160122
The number of items: 13738
Average actions of items: 2.9137429028970736
The number of inters: 40029
The sparsity of the dataset: 99.99181486908563%
25 Mar 16:25    INFO

=================================


25 Mar 16:25    INFO =========1/1: Parameters:['seed', 'n_ui_layers', 'image_knn_k', 'text_knn_k', 'reg_weight', 'dropout_rate']=(999, 3, 10, 10, 0.0001, 0)=======
25 Mar 16:26    INFO SMORE(
  (dropout): Dropout(p=0, inplace=False)
  (user_embedding): Embedding(35598, 64)
  (item_id_embedding): Embedding(18357, 64)
  (image_embedding): Embedding(18357, 4096)
  (text_embedding): Embedding(18357, 384)
  (image_trs): Linear(in_features=4096, out_features=64, bias=True)
  (text_trs): Linear(in_features=384, out_features=64, bias=True)
  (softmax): Softmax(dim=-1)
  (query_v): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=64, bias=False)
  )
  (query_t): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=64, bias=False)
  )
  (gate_v): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Sigmoid()
  )
  (gate_t): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Sigmoid()
  )
  (gate_f): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Sigmoid()
  )
  (gate_image_prefer): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Sigmoid()
  )
  (gate_text_prefer): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Sigmoid()
  )
  (gate_fusion_prefer): Sequential(
    (0): Linear(in_features=64, out_features=64, bias=True)
    (1): Sigmoid()
  )
)
Trainable parameters: 86020998
25 Mar 16:28    INFO epoch 0 training [time: 155.77s, train loss: 96.7252]
25 Mar 16:29    INFO epoch 0 evaluating [time: 11.32s, valid_score: 0.047600]
25 Mar 16:29    INFO valid result:
recall@5: 0.0237    recall@10: 0.0340    recall@20: 0.0476    recall@50: 0.0683    ndcg@5: 0.0161    ndcg@10: 0.0195    ndcg@20: 0.0229    ndcg@50: 0.0271    precision@5: 0.0049    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0014    map@5: 0.0135    map@10: 0.0148    map@20: 0.0158    map@50: 0.0164
25 Mar 16:29    INFO test result:
recall@5: 0.0228    recall@10: 0.0326    recall@20: 0.0456    recall@50: 0.0680    ndcg@5: 0.0152    ndcg@10: 0.0184    ndcg@20: 0.0217    ndcg@50: 0.0263    precision@5: 0.0050    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0015    map@5: 0.0123    map@10: 0.0136    map@20: 0.0145    map@50: 0.0152
25 Mar 16:29    INFO Latest checkpoint saved to saved\SMORE_sports_seed999_n_ui_layers3_image_knn_k10_text_knn_k10_reg_weight0.0001_dropout_rate0_latest.pth
25 Mar 16:29    INFO ██ SMORE--Best validation results updated!!!
25 Mar 16:29    INFO Best checkpoint saved to saved\SMORE_sports_seed999_n_ui_layers3_image_knn_k10_text_knn_k10_reg_weight0.0001_dropout_rate0_best.pth
25 Mar 16:29    INFO best valid result: recall@5: 0.0237    recall@10: 0.0340    recall@20: 0.0476    recall@50: 0.0683    ndcg@5: 0.0161    ndcg@10: 0.0195    ndcg@20: 0.0229    ndcg@50: 0.0271    precision@5: 0.0049    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0014    map@5: 0.0135    map@10: 0.0148    map@20: 0.0158    map@50: 0.0164
25 Mar 16:29    INFO test result: recall@5: 0.0228    recall@10: 0.0326    recall@20: 0.0456    recall@50: 0.0680    ndcg@5: 0.0152    ndcg@10: 0.0184    ndcg@20: 0.0217    ndcg@50: 0.0263    precision@5: 0.0050    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0015    map@5: 0.0123    map@10: 0.0136    map@20: 0.0145    map@50: 0.0152
25 Mar 16:29    INFO ████Current BEST████:
Parameters: ['seed', 'n_ui_layers', 'image_knn_k', 'text_knn_k', 'reg_weight', 'dropout_rate']=(999, 3, 10, 10, 0.0001, 0),
Valid: recall@5: 0.0237    recall@10: 0.0340    recall@20: 0.0476    recall@50: 0.0683    ndcg@5: 0.0161    ndcg@10: 0.0195    ndcg@20: 0.0229    ndcg@50: 0.0271    precision@5: 0.0049    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0014    map@5: 0.0135    map@10: 0.0148    map@20: 0.0158    map@50: 0.0164    ,
Test: recall@5: 0.0228    recall@10: 0.0326    recall@20: 0.0456    recall@50: 0.0680    ndcg@5: 0.0152    ndcg@10: 0.0184    ndcg@20: 0.0217    ndcg@50: 0.0263    precision@5: 0.0050    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0015    map@5: 0.0123    map@10: 0.0136    map@20: 0.0145    map@50: 0.0152



25 Mar 16:29    INFO
============All Over=====================
25 Mar 16:29    INFO Parameters: ['seed', 'n_ui_layers', 'image_knn_k', 'text_knn_k', 'reg_weight', 'dropout_rate']=(999, 3, 10, 10, 0.0001, 0),
 best valid: recall@5: 0.0237    recall@10: 0.0340    recall@20: 0.0476    recall@50: 0.0683    ndcg@5: 0.0161    ndcg@10: 0.0195    ndcg@20: 0.0229    ndcg@50: 0.0271    precision@5: 0.0049    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0014    map@5: 0.0135    map@10: 0.0148    map@20: 0.0158    map@50: 0.0164    ,
 best test: recall@5: 0.0228    recall@10: 0.0326    recall@20: 0.0456    recall@50: 0.0680    ndcg@5: 0.0152    ndcg@10: 0.0184    ndcg@20: 0.0217    ndcg@50: 0.0263    precision@5: 0.0050    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0015    map@5: 0.0123    map@10: 0.0136    map@20: 0.0145    map@50: 0.0152
25 Mar 16:29    INFO

█████████████ BEST ████████████████
25 Mar 16:29    INFO 	Parameters: ['seed', 'n_ui_layers', 'image_knn_k', 'text_knn_k', 'reg_weight', 'dropout_rate']=(999, 3, 10, 10, 0.0001, 0),
Valid: recall@5: 0.0237    recall@10: 0.0340    recall@20: 0.0476    recall@50: 0.0683    ndcg@5: 0.0161    ndcg@10: 0.0195    ndcg@20: 0.0229    ndcg@50: 0.0271    precision@5: 0.0049    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0014    map@5: 0.0135    map@10: 0.0148    map@20: 0.0158    map@50: 0.0164    ,
Test: recall@5: 0.0228    recall@10: 0.0326    recall@20: 0.0456    recall@50: 0.0680    ndcg@5: 0.0152    ndcg@10: 0.0184    ndcg@20: 0.0217    ndcg@50: 0.0263    precision@5: 0.0050    precision@10: 0.0036    precision@20: 0.0025    precision@50: 0.0015    map@5: 0.0123    map@10: 0.0136    map@20: 0.0145    map@50: 0.0152

Using device: cpu

{'epoch': 43,
 'model_state_dict': OrderedDict([('image_complex_weight',
               tensor([[[-0.7795,  0.5151],
                        [ 0.3265, -0.8950],
                        [-2.2076,  0.5592],
                        [-0.8124,  0.2277],
                        [ 0.1892,  0.6833],
                        [-0.2569,  1.2942],
                        [ 0.5806, -1.4800],
                        [-3.2718, -0.6123],
                        [-1.3429, -0.2191],
                        [-0.0834,  0.6362],
                        [ 0.3822,  1.0347],
                        [ 0.6993,  1.9135],
                        [ 2.2441,  0.9717],
                        [-0.5467,  1.0909],
                        [ 0.5332,  0.3112],
                        [ 1.6389,  0.5942],
                        [-1.7335,  0.9973],
                        [-0.5315,  0.3880],
                        [ 0.2993, -0.9630],
                        [-1.4210,  0.2978],
                        [-1.8644,  0.3032],
                        [ 0.4897,  0.0164],
                        [ 1.5709,  0.0584],
                        [ 0.4865,  0.1272],
                        [ 1.0615,  1.4636],
                        [-0.0993,  0.2494],
                        [-0.7849,  0.2751],
                        [ 1.0854, -0.8806],
                        [ 0.6988,  1.6375],
                        [ 1.2722,  0.0956],
                        [ 0.9437, -0.4365],
                        [ 1.9843, -0.2609],
                        [-0.6976, -2.2491]]])),
              ('text_complex_weight',
               tensor([[[ 1.6830, -0.1765],
                        [ 1.4131, -1.9964],
                        [-1.9969, -0.1866],
                        [-1.8477,  0.5070],
                        [-2.2422, -3.3746],
                        [-1.6885, -3.9279],
                        [ 0.7564, -2.9968],
                        [-2.7708, -0.8465],
                        [-2.5677, -1.4755],
                        [-1.8904, -3.2411],
                        [ 0.9568, -1.2811],
                        [-0.0877, -0.2968],
                        [ 0.4254, -0.3815],
                        [ 0.0219,  1.6651],
                        [ 1.3128,  2.7966],
                        [-2.3842,  0.1477],
                        [ 1.4858,  2.3607],
                        [ 2.3854, -0.1891],
                        [ 3.2635, -3.6636],
                        [-2.7218,  0.6152],
                        [ 2.1043, -1.3968],
                        [-0.2092,  0.5233],
                        [-3.9736,  2.0740],
                        [ 1.7160,  1.2487],
                        [ 2.9466,  1.9740],
                        [ 2.6762,  4.0576],
                        [ 1.5449, -1.1904],
                        [-1.4830,  3.0541],
                        [-1.5447,  2.2520],
                        [-1.9776,  3.3304],
                        [-0.5336,  1.2323],
                        [-2.0049,  2.5171],
                        [ 0.5501,  2.0615]]])),
              ('fusion_complex_weight',
               tensor([[[-1.3944, -1.5227],
                        [-0.8715,  0.7571],
                        [-0.4660, -1.3703],
                        [-0.0974,  1.4864],
                        [-1.4831, -0.1835],
                        [ 0.0861,  1.3566],
                        [-0.3654, -0.9953],
                        [-1.2530,  0.9339],
                        [-2.2308,  0.9645],
                        [-0.7505,  1.4215],
                        [ 1.2835, -0.1011],
                        [-1.2379, -1.7663],
                        [ 1.0684, -0.4666],
                        [-3.2032,  0.5023],
                        [ 0.3292, -1.3331],
                        [ 2.6786, -0.3227],
                        [-1.0954,  0.1716],
                        [ 0.8468, -1.3169],
                        [-1.2347,  0.4865],
                        [ 1.1011,  0.3173],
                        [-0.7699,  0.7163],
                        [ 0.1029,  1.3733],
                        [-0.1347, -0.4451],
                        [ 0.2232, -1.2773],
                        [-0.9897,  0.8736],
                        [-0.2534,  0.3665],
                        [ 0.0907, -2.3748],
                        [ 1.3387,  0.4052],
                        [ 0.2827, -2.1395],
                        [-0.9614, -1.1509],
                        [-0.6734, -2.1066],
                        [ 1.2859,  1.0560],
                        [-1.7007,  1.1054]]])),
              ('user_embedding.weight',
               tensor([[ 0.3206, -0.5063, -0.2246,  ...,  0.2442,  0.5974,  0.2569],
                       [ 0.2112, -0.1267, -0.5186,  ...,  0.2416,  0.2709,  0.3943],
                       [ 0.0474, -0.5523,  0.0519,  ..., -0.5074,  0.2758,  0.3016],
                       ...,
                       [ 0.0269, -0.1948, -0.5178,  ...,  0.2758, -0.1752, -0.4473],
                       [ 0.1213, -0.6196, -0.1530,  ...,  0.2784,  0.3963,  0.3812],
                       [ 0.0144, -0.3643, -0.3081,  ..., -0.0387,  0.2521, -0.1906]])),
              ('item_id_embedding.weight',
               tensor([[ 0.3583, -0.6409, -0.4428,  ...,  0.3149,  0.1707,  0.7071],
                       [-0.3959, -0.4909,  0.2521,  ...,  0.3905,  0.3591,  0.3866],
                       [-0.4718,  0.0576, -0.0037,  ...,  0.1730,  0.3741, -0.3174],
                       ...,
                       [-0.4024, -0.3595,  0.1269,  ..., -0.3702, -0.5999, -0.4420],
                       [-0.0505, -0.4608, -0.3657,  ..., -0.1708, -0.3511, -0.3977],
                       [ 0.0165, -0.0826, -0.0282,  ..., -0.0415,  0.4130, -0.4625]])),
              ('image_embedding.weight',
               tensor([[ 1.3192e-03,  5.2707e+00, -2.3776e-04,  ...,  1.3668e-03,
                         4.0829e-03,  2.4771e-04],
                       [ 4.6694e-03,  1.7553e-03,  6.5934e-04,  ...,  2.9930e+00,
                         4.1630e-01,  4.1209e-03],
                       [ 1.1802e-03,  7.2503e-04,  6.4659e-05,  ...,  5.0880e-04,
                         1.7272e+00,  1.0857e-03],
                       ...,
                       [ 1.6760e-03,  3.9204e-05,  5.9990e-04,  ...,  2.1854e-03,
                         1.8988e-03,  3.9059e-04],
                       [-8.7932e-04,  3.4516e+00, -6.8174e-04,  ..., -2.0973e-03,
                         9.2799e-05, -1.2397e-03],
                       [ 1.9964e-03,  5.6128e-04,  3.0221e-03,  ...,  1.3808e-03,
                         6.0698e-03,  1.3095e+00]])),
              ('text_embedding.weight',
               tensor([[-0.0864,  0.0095, -0.0377,  ..., -0.1754,  0.1218,  0.0501],
                       [-0.0584, -0.0029, -0.0592,  ...,  0.0081,  0.1057,  0.1043],
                       [-0.1612,  0.1014, -0.0210,  ..., -0.2483,  0.0123,  0.0953],
                       ...,
                       [-0.0149,  0.0348, -0.0401,  ..., -0.1198, -0.0347, -0.0367],
                       [-0.0491,  0.0183,  0.0390,  ..., -0.0198, -0.0858, -0.0064],
                       [-0.0511, -0.0751,  0.0656,  ...,  0.0762,  0.0448, -0.0469]])),
              ('image_trs.weight',
               tensor([[-0.0252, -0.0132, -0.0514,  ..., -0.0425, -0.0446, -0.0266],
                       [ 0.0636,  0.0115,  0.0074,  ...,  0.0314,  0.0425,  0.0707],
                       [-0.0137,  0.0150, -0.0288,  ...,  0.0272, -0.0060, -0.0084],
                       ...,
                       [-0.0491, -0.0841, -0.0461,  ..., -0.0992, -0.0983, -0.0618],
                       [-0.0241,  0.0012, -0.0209,  ...,  0.0238,  0.0379, -0.0209],
                       [ 0.0957,  0.0824,  0.0724,  ...,  0.0248,  0.0962,  0.1053]])),
              ('image_trs.bias',
               tensor([-0.0127,  0.0976, -0.0148,  0.0687, -0.1106, -0.0235, -0.1278, -0.0304,
                       -0.0538, -0.0332, -0.0566,  0.0506, -0.0779,  0.1118,  0.0029, -0.0005,
                       -0.1082, -0.1331,  0.1047,  0.1864, -0.1778,  0.0146,  0.0403, -0.0510,
                       -0.1402,  0.1430,  0.1274,  0.0621, -0.0747, -0.0657,  0.0449,  0.0077,
                        0.1297,  0.1150,  0.0487,  0.2225,  0.0768,  0.1183,  0.0293, -0.0468,
                        0.0851, -0.0794, -0.1259, -0.0006, -0.0747, -0.1017, -0.0489,  0.1438,
                        0.0501,  0.1126,  0.0404, -0.0613, -0.0461,  0.0083,  0.0475, -0.1301,
                        0.1642,  0.0190,  0.1640,  0.0004, -0.0267, -0.1225,  0.0121,  0.1181])),
              ('text_trs.weight',
               tensor([[-0.0043,  0.0085,  0.0263,  ..., -0.0365, -0.0437,  0.0282],
                       [-0.0201, -0.0540, -0.0258,  ...,  0.0007,  0.0561, -0.0253],
                       [ 0.0230, -0.0826,  0.0236,  ...,  0.0418, -0.1010,  0.0439],
                       ...,
                       [-0.0093, -0.0401, -0.0392,  ..., -0.0385, -0.0255, -0.0175],
                       [-0.0111, -0.0050, -0.0382,  ..., -0.0080, -0.0638, -0.0033],
                       [ 0.0115, -0.0536,  0.0416,  ..., -0.0692, -0.0289,  0.0751]])),
              ('text_trs.bias',
               tensor([ 0.0468,  0.0347, -0.0461, -0.0005, -0.0357, -0.0137,  0.0504,  0.0336,
                       -0.0272,  0.0840,  0.0382, -0.0800, -0.0217,  0.0192, -0.0123, -0.0446,
                       -0.0474,  0.0008,  0.0583, -0.0218,  0.0213, -0.0881,  0.0482, -0.0128,
                        0.0863,  0.0571, -0.0597,  0.1404, -0.0427, -0.0607, -0.0185,  0.0435,
                       -0.0136,  0.0062, -0.0524,  0.0992,  0.0243, -0.0406,  0.0413, -0.0687,
                        0.0875,  0.0401, -0.0282,  0.0026, -0.0398, -0.0298, -0.0331, -0.0265,
                        0.1066, -0.0039, -0.0258, -0.0542, -0.0504, -0.0409,  0.0090, -0.0508,
                        0.0537, -0.0541,  0.0231,  0.0156,  0.0135,  0.0139,  0.0233,  0.0719])),
              ('query_v.0.weight',
               tensor([[ 0.3075,  1.0699,  0.1370,  ...,  0.2130,  0.2471,  0.3486],
                       [ 0.0382, -0.0811,  0.1432,  ..., -0.3010,  0.0892, -0.2823],
                       [ 0.1520, -0.0443,  0.0115,  ...,  0.3209, -0.0341,  0.2241],
                       ...,
                       [ 0.2624, -0.5116,  0.1603,  ...,  0.3212,  0.0281, -0.0625],
                       [-0.4247, -0.0119, -0.2502,  ..., -0.1467, -0.1028, -0.0356],
                       [-0.0597, -0.7457,  0.1054,  ..., -0.2398, -0.1649, -0.0480]])),
              ('query_v.0.bias',
               tensor([-0.4514, -0.3457, -0.1266,  0.3547, -0.4610,  0.0288,  0.1516,  0.2781,
                       -0.1937, -0.0108,  0.3289,  0.5914,  0.1794,  0.2416,  0.3032,  0.1360,
                        0.2848, -0.0601, -0.4653,  0.3875,  0.4402, -0.2983,  0.1979, -0.6003,
                       -0.4682,  0.5326,  0.4401,  0.2966, -0.3814,  0.4755,  0.3495, -0.0446,
                       -0.2426,  0.0047, -0.3098, -0.3848, -0.2337,  0.3998,  0.2052, -0.1307,
                       -0.3422, -0.0875, -0.3139,  0.1768,  0.2935, -0.3044, -0.3660, -0.3462,
                       -0.2667, -0.5028,  0.4054,  0.2174,  0.2366, -0.4362,  0.1962, -0.4754,
                        0.1178, -0.2512,  0.2864, -0.4124, -0.2485,  0.0652, -0.6259,  0.1301])),
              ('query_v.2.weight',
               tensor([[ 0.2859,  0.2673,  0.0976,  ..., -0.0981,  0.4370, -0.2537],
                       [ 0.4306, -0.2697,  0.1340,  ..., -0.1990, -0.0033, -0.4194],
                       [ 0.1620,  0.4922, -0.2668,  ..., -0.2862,  0.4851,  0.2183],
                       ...,
                       [ 0.2438,  0.3342,  0.1669,  ...,  0.2866,  0.1407, -0.2023],
                       [ 0.0049,  0.3782,  0.2430,  ..., -0.0399,  0.3931,  0.2892],
                       [ 0.2523,  0.4132,  0.1346,  ..., -0.5723,  0.3930, -0.1554]])),
              ('query_t.0.weight',
               tensor([[-0.2449, -0.4333,  0.0713,  ...,  0.3608,  0.1416, -0.2651],
                       [-0.2580, -0.4277,  0.3365,  ...,  0.3841,  0.1019,  0.1891],
                       [-0.3311,  0.0237, -0.1723,  ..., -0.3539,  0.2102,  0.1448],
                       ...,
                       [ 0.2989, -0.3151,  0.2857,  ..., -0.1901,  0.1272,  0.0869],
                       [-0.3178,  0.4072, -0.2545,  ..., -0.1887,  0.1672,  0.3884],
                       [ 0.4920,  0.1852, -0.3268,  ...,  0.1685, -0.3985, -0.4489]])),
              ('query_t.0.bias',
               tensor([ 0.0288,  0.5722, -0.2622,  0.1394, -0.1236,  0.1243,  0.2704, -0.0364,
                       -0.0217, -0.0708,  0.3442,  0.1861,  0.2347,  0.0544, -0.1166, -0.1483,
                        0.2914,  0.3038, -0.3071, -0.0159, -0.5021,  0.0858, -0.3301,  0.1321,
                        0.2308,  0.0566, -0.1679,  0.3161, -0.1251, -0.2732, -0.2883, -0.4075,
                        0.0518,  0.1257,  0.5183, -0.0598, -0.3379, -0.1529, -0.3671, -0.2240,
                        0.1749,  0.1176,  0.0273,  0.3127, -0.0736,  0.3295, -0.3042,  0.0831,
                       -0.2617, -0.0806,  0.6233, -0.5313, -0.2645, -0.2877, -0.1521,  0.0495,
                        0.2576, -0.3367,  0.5217, -0.0641,  0.2683,  0.2932, -0.2051, -0.0491])),
              ('query_t.2.weight',
               tensor([[ 0.0381,  0.0288,  0.4892,  ..., -0.2232,  0.5775, -0.2141],
                       [-0.0868, -0.7146,  0.0240,  ..., -0.6295,  0.2026,  0.0021],
                       [-0.2576, -0.3980,  0.4577,  ..., -0.3742,  0.4906,  0.5647],
                       ...,
                       [-0.4060, -0.4848, -0.0815,  ..., -0.2032,  0.3564, -0.0662],
                       [ 0.3488, -0.0136,  0.0526,  ..., -0.4036, -0.0225, -0.5293],
                       [-0.2689,  0.3511, -0.0852,  ...,  0.2538,  0.2679, -0.2699]])),
              ('gate_v.0.weight',
               tensor([[ 0.0553, -0.1396,  0.0908,  ..., -0.0647, -0.1030, -0.0857],
                       [ 0.0388, -0.0493, -0.0690,  ..., -0.0206, -0.1051, -0.0412],
                       [-0.0632, -0.0819, -0.0490,  ..., -0.0158,  0.0466,  0.1034],
                       ...,
                       [ 0.0322, -0.0355,  0.0792,  ...,  0.1045,  0.1029, -0.0428],
                       [-0.1025, -0.0221, -0.1350,  ..., -0.0712,  0.0271, -0.0532],
                       [ 0.0950,  0.0610, -0.1129,  ...,  0.1159,  0.1149, -0.0683]])),
              ('gate_v.0.bias',
               tensor([ 0.0580, -0.0693,  0.0320,  0.0961, -0.1036,  0.0504, -0.0296,  0.1271,
                        0.0389,  0.1162,  0.1276, -0.0914,  0.0505,  0.0239,  0.1394, -0.0262,
                       -0.0414,  0.0777, -0.0698,  0.1343,  0.0619,  0.0778,  0.0108, -0.0559,
                        0.0694, -0.0506,  0.0610,  0.0501, -0.0658,  0.0343,  0.0365, -0.0528,
                       -0.0811, -0.0728,  0.0953, -0.0460,  0.1266, -0.0545,  0.0328,  0.1315,
                        0.0371,  0.0794, -0.0331,  0.0518, -0.0198,  0.0720, -0.0052,  0.0197,
                       -0.0448,  0.1149,  0.1136,  0.0505, -0.0589,  0.0841,  0.1220,  0.0498,
                       -0.0235,  0.0522,  0.0783,  0.0352,  0.0295,  0.0557, -0.0872, -0.0153])),
              ('gate_t.0.weight',
               tensor([[ 0.3926, -0.2206,  0.4301,  ..., -0.2590, -0.2254,  0.5171],
                       [ 0.1658, -0.1669,  0.6228,  ..., -0.1912, -0.2138,  0.2387],
                       [ 0.0822, -0.1341,  0.3051,  ..., -0.3198, -0.1410,  0.6854],
                       ...,
                       [ 0.2787, -0.0650,  0.4149,  ..., -0.2875, -0.1787,  0.6941],
                       [-0.1449, -0.2050,  0.2098,  ..., -0.2173, -0.3924,  0.4312],
                       [ 0.0442, -0.6271,  0.4615,  ..., -0.6246, -0.2618,  0.8164]])),
              ('gate_t.0.bias',
               tensor([0.3185, 0.3666, 0.2777, 0.3734, 0.4430, 0.3729, 0.6565, 0.4575, 0.3823,
                       0.5197, 0.5557, 0.3204, 0.4513, 0.5920, 0.6351, 0.4557, 0.3934, 0.3196,
                       0.3400, 0.4209, 0.4126, 0.4389, 0.5527, 0.4043, 0.7388, 0.3064, 0.4116,
                       0.5107, 0.5510, 0.4408, 0.3001, 0.3858, 0.5488, 0.4598, 0.5561, 0.4704,
                       0.3911, 0.5271, 0.4362, 0.4328, 0.4797, 0.3001, 0.6351, 0.5877, 0.2167,
                       0.4992, 0.4579, 0.5728, 0.2499, 0.3736, 0.4172, 0.4119, 0.5105, 0.4094,
                       0.5867, 0.5572, 0.4450, 0.4783, 0.4400, 0.4388, 0.3939, 0.3359, 0.3668,
                       0.3909])),
              ('gate_f.0.weight',
               tensor([[ 0.1299,  0.0216,  0.0527,  ...,  0.1137,  0.0527, -0.0370],
                       [-0.0280, -0.1218, -0.1356,  ..., -0.1252, -0.0380, -0.0772],
                       [ 0.0461, -0.1317, -0.0104,  ..., -0.1190, -0.2553,  0.0003],
                       ...,
                       [-0.2429,  0.1576,  0.1651,  ..., -0.0901,  0.1335, -0.0531],
                       [-0.1380, -0.0009, -0.0162,  ...,  0.0100,  0.3197, -0.1351],
                       [-0.1849, -0.1019,  0.0625,  ...,  0.0303, -0.0339, -0.1103]])),
              ('gate_f.0.bias',
               tensor([ 0.0330,  0.0644, -0.0161, -0.0556,  0.0376, -0.0317,  0.1286,  0.0279,
                       -0.0031, -0.0030, -0.0711,  0.0792, -0.0198,  0.0688,  0.0437,  0.1571,
                        0.0290,  0.0360,  0.0801, -0.0299,  0.0790, -0.1039,  0.1094,  0.1405,
                        0.0927,  0.1146,  0.1194,  0.0676,  0.0793,  0.0158, -0.0018,  0.0884,
                        0.0467,  0.1252,  0.1417, -0.0671,  0.0133,  0.0617,  0.0969,  0.1012,
                       -0.0124,  0.0342, -0.0490,  0.0666,  0.0604,  0.0265,  0.1015, -0.0813,
                        0.0227,  0.0008,  0.0984,  0.0256,  0.1018,  0.0813, -0.0127,  0.0028,
                       -0.0320,  0.1162, -0.0235, -0.0039,  0.0454,  0.1207,  0.0832,  0.0701])),
              ('gate_image_prefer.0.weight',
               tensor([[ 0.1596,  0.4010, -0.0171,  ...,  0.1777, -0.1550, -0.3144],
                       [ 1.3626,  2.2924, -0.5229,  ...,  0.4348, -0.4469, -1.1977],
                       [-0.1231,  0.5891, -0.5153,  ..., -0.0734, -0.5258, -0.4971],
                       ...,
                       [ 0.0841,  0.2332, -0.1259,  ...,  0.3663,  0.1029, -0.1798],
                       [-0.1909, -0.0972, -0.0158,  ...,  0.1762,  0.0321, -0.0403],
                       [ 0.0691,  0.2384, -0.1878,  ...,  0.0209, -0.2931, -0.2944]])),
              ('gate_image_prefer.0.bias',
               tensor([0.8527, 2.4637, 0.8564, 0.5790, 0.5924, 2.8939, 2.4304, 0.6795, 1.4090,
                       0.7135, 2.8690, 2.8256, 1.0696, 1.0731, 2.8279, 1.3977, 0.6862, 0.5050,
                       1.0045, 0.8558, 1.1126, 1.1829, 1.5008, 1.1817, 1.5163, 2.0031, 0.1263,
                       2.5947, 2.8062, 2.5093, 1.6410, 0.7142, 1.2687, 1.3425, 0.8265, 0.6849,
                       0.9498, 0.6273, 2.7845, 2.2563, 0.7449, 2.6647, 1.3927, 1.0151, 1.2524,
                       0.8958, 2.4945, 1.2269, 0.7245, 1.0636, 2.5975, 0.8436, 2.6649, 2.7382,
                       1.2435, 0.9058, 0.7984, 0.5887, 0.9175, 1.6229, 0.5534, 1.0248, 1.2246,
                       0.5579])),
              ('gate_text_prefer.0.weight',
               tensor([[-1.0975, -0.1327,  0.0652,  ..., -0.1431,  0.6031,  0.7797],
                       [-0.2544,  0.0722,  0.1907,  ...,  0.2155,  0.0444,  0.3075],
                       [-0.2800,  0.2842, -0.2712,  ..., -0.2330, -0.0833,  0.1452],
                       ...,
                       [-0.2677,  0.1677, -0.2161,  ..., -0.3510,  0.3237,  0.0844],
                       [-1.0026, -0.7020,  0.2395,  ..., -0.0805,  0.5402,  0.8557],
                       [-1.0631, -0.0662,  0.4100,  ...,  0.2493,  0.7869,  1.4291]])),
              ('gate_text_prefer.0.bias',
               tensor([1.6807, 0.7959, 1.1478, 1.3733, 2.3984, 1.3920, 2.7852, 2.9341, 1.6487,
                       1.9824, 2.2234, 1.8588, 2.6344, 2.8720, 2.1952, 1.1476, 2.1680, 1.5384,

sports
The number of users: 35598
Average actions of users: 8.324540704533963
The number of items: 18357
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465195454304%
✓ Model loaded successfully!
  Epoch: 43

OrderedDict([('image_complex_weight',
              tensor([[[-0.7781,  0.5151],
                       [ 0.3063, -0.9044],
                       [-2.1879,  0.5574],
                       [-0.7699,  0.2161],
                       [ 0.1764,  0.6585],
                       [-0.2551,  1.3129],
                       [ 0.6066, -1.5011],
                       [-3.3006, -0.6108],
                       [-1.3500, -0.2245],
                       [-0.0564,  0.6472],
                       [ 0.3605,  1.0517],
                       [ 0.7059,  1.8928],
                       [ 2.2398,  0.9830],
                       [-0.5336,  1.0620],
                       [ 0.5289,  0.3246],
                       [ 1.6279,  0.5774],
                       [-1.7490,  1.0120],
                       [-0.5464,  0.3762],
                       [ 0.3045, -0.9949],
                       [-1.4448,  0.3182],
                       [-1.8918,  0.2962],
                       [ 0.4890,  0.0310],
                       [ 1.5776,  0.0270],
                       [ 0.4984,  0.1328],
                       [ 1.1114,  1.4869],
                       [-0.0882,  0.2777],
                       [-0.7425,  0.2653],
                       [ 1.1171, -0.8826],
                       [ 0.7171,  1.6326],
                       [ 1.2542,  0.1017],
                       [ 0.9198, -0.4578],
                       [ 1.9632, -0.2606],
                       [-0.6910, -2.2491]]])),
             ('text_complex_weight',
              tensor([[[ 1.3343, -0.1765],
                       [ 0.9048, -1.4139],
                       [-0.8132, -0.0396],
                       [-1.7161,  1.0091],
                       [-1.0675, -1.8893],
                       [-0.5066, -2.1016],
                       [ 0.2065, -1.6297],
                       [-1.5877, -0.4042],
                       [-0.7991, -0.0791],
                       [-1.6060, -2.5648],
                       [ 0.7067, -0.8584],
                       [-0.3925,  0.0596],
                       [ 0.1501, -0.1478],
                       [ 0.3864,  1.5155],
                       [ 1.0850,  2.0023],
                       [-0.9619,  0.0504],
                       [ 0.3043,  0.8449],
                       [ 1.3330,  0.0159],
                       [ 2.1632, -2.4160],
                       [-1.6095,  0.1053],
                       [ 1.3477, -1.1207],
                       [-0.4077,  0.0804],
                       [-2.7711,  1.5344],
                       [ 0.9959,  1.0918],
                       [ 1.6661,  0.6535],
                       [ 0.9562,  1.9005],
                       [ 1.3386, -0.7940],
                       [-1.1335,  2.2607],
                       [-0.3739,  0.9939],
                       [-1.2321,  2.3030],
                       [-0.0848,  0.4843],
                       [-1.5312,  1.9717],
                       [ 0.6533,  2.0615]]])),
             ('fusion_complex_weight',
              tensor([[[-0.9984, -1.5227],
                       [-0.5019,  0.4762],
                       [-0.4493, -1.2074],
                       [-0.0553,  0.8867],
                       [-1.3602, -0.1695],
                       [ 0.0785,  1.1578],
                       [-0.2934, -0.7908],
                       [-1.1485,  0.8680],
                       [-2.1701,  0.9445],
                       [-0.6474,  1.1969],
                       [ 1.0924, -0.1033],
                       [-1.1437, -1.6342],
                       [ 0.6333, -0.2589],
                       [-3.1358,  0.4638],
                       [ 0.2002, -0.9129],
                       [ 2.6102, -0.3066],
                       [-0.8790,  0.1384],
                       [ 0.7014, -1.0845],
                       [-0.8131,  0.3117],
                       [ 0.7095,  0.2108],
                       [-0.2781,  0.2832],
                       [ 0.0907,  1.1657],
                       [-0.0575, -0.2657],
                       [ 0.1108, -0.7213],
                       [-0.7571,  0.6779],
                       [-0.1931,  0.2945],
                       [ 0.0665, -2.1420],
                       [ 0.8612,  0.2403],
                       [ 0.2866, -2.0337],
                       [-0.7596, -0.9348],
                       [-0.5687, -1.8438],
                       [ 1.0088,  0.8368],
                       [-1.3496,  1.1054]]])),
             ('user_embedding.weight',
              tensor([[ 0.0241, -0.0170, -0.0336,  ...,  0.0270,  0.0209,  0.0345],
                      [ 0.0188, -0.0027, -0.0177,  ...,  0.0259,  0.0009,  0.0484],
                      [ 0.0260, -0.0085, -0.0271,  ...,  0.0316, -0.0187,  0.0393],
                      ...,
                      [ 0.0162, -0.0138,  0.0177,  ..., -0.0023,  0.0077, -0.0243],
                      [-0.0388, -0.0045,  0.0152,  ..., -0.0315,  0.0130,  0.0262],
                      [-0.0492, -0.0234,  0.0181,  ..., -0.0359,  0.0389,  0.0087]])),
             ('item_id_embedding.weight',
              tensor([[ 0.0152, -0.0200, -0.0360,  ...,  0.0841, -0.0117,  0.0593],
                      [ 0.0144,  0.0121, -0.0015,  ...,  0.0604, -0.0244,  0.0068],
                      [-0.0327, -0.0020,  0.0026,  ...,  0.0088,  0.0462, -0.0232],
                      ...,
                      [-0.0002,  0.0056, -0.0133,  ...,  0.0157,  0.0154, -0.0325],
                      [ 0.0005, -0.0173,  0.0364,  ..., -0.0264, -0.0516, -0.0242],
                      [-0.0377, -0.0004, -0.0215,  ..., -0.0101, -0.0102,  0.0204]])),
             ('image_embedding.weight',
              tensor([[-1.2887e-03,  5.2697e+00, -1.5495e-03,  ..., -3.8797e-03,
                       -2.4926e-03, -3.4999e-04],
                      [ 1.8964e-03,  2.9977e-03,  3.4380e-03,  ...,  2.9918e+00,
                        4.1802e-01,  4.0306e-03],
                      [-5.9886e-04, -5.0572e-04, -1.2668e-03,  ..., -5.0556e-04,
                        1.7248e+00, -6.4089e-04],
                      ...,
                      [ 3.3274e-04,  3.4373e-04,  5.1871e-04,  ...,  7.7874e-04,
                        2.1692e-04,  1.9002e-04],
                      [-6.1187e-04,  3.4522e+00, -6.6585e-04,  ..., -9.5908e-06,
                       -5.3218e-04,  1.8914e-04],
                      [ 1.4190e-04,  1.2246e-03,  1.0916e-03,  ...,  6.5325e-04,
                        1.3228e-03,  1.3110e+00]])),
             ('text_embedding.weight',
              tensor([[-0.0956,  0.0243, -0.0119,  ..., -0.0639,  0.0435,  0.0840],
                      [-0.0385,  0.0014, -0.0732,  ..., -0.0281, -0.0023,  0.0734],
                      [-0.1129,  0.0510,  0.0261,  ..., -0.1689,  0.0592,  0.0429],
                      ...,
                      [-0.0119,  0.0196, -0.0235,  ..., -0.1154, -0.0114, -0.0145],
                      [-0.0140, -0.0050,  0.0284,  ..., -0.0861, -0.0343, -0.0259],
                      [-0.1159, -0.0105,  0.0047,  ..., -0.1078,  0.0434,  0.0594]])),
             ('image_trs.weight',
              tensor([[ 0.0095,  0.0043, -0.0046,  ..., -0.0056,  0.0022,  0.0223],
                      [ 0.0071, -0.0090,  0.0335,  ...,  0.0094,  0.0158,  0.0236],
                      [ 0.0353,  0.0311,  0.0116,  ..., -0.0080,  0.0399, -0.0019],
                      ...,
                      [-0.0335, -0.0106, -0.0086,  ..., -0.0560, -0.0239, -0.0018],
                      [ 0.0057, -0.0012,  0.0059,  ...,  0.0034, -0.0135, -0.0220],
                      [-0.0028,  0.0119,  0.0083,  ..., -0.0021,  0.0171,  0.0237]])),
             ('image_trs.bias',
              tensor([ 5.7140e-02,  7.0274e-02,  4.5078e-02,  3.4165e-02,  2.6078e-02,
                       2.4445e-02, -1.6450e-02, -2.5693e-02, -7.2625e-02, -1.7866e-02,
                      -2.4499e-02, -2.6778e-02, -3.8116e-02,  1.0999e-02,  3.8439e-02,
                       1.0632e-02,  6.4136e-03,  2.9267e-02,  6.5746e-02,  5.8617e-02,
                      -5.6809e-02,  2.3449e-02,  3.6490e-02, -2.5143e-02, -8.1011e-02,
                       1.2810e-02,  1.1361e-02, -2.6051e-02, -3.6885e-02, -2.5898e-02,
                       1.2740e-02,  2.0245e-02,  2.8313e-02,  2.9881e-03,  7.2628e-02,
                       7.4233e-02,  4.0092e-02,  9.6812e-03, -1.4153e-02, -1.8367e-02,
                      -9.1595e-03, -6.7017e-02, -7.5785e-02, -1.0192e-02,  3.5599e-03,
                      -3.3845e-02,  1.4265e-02,  5.2811e-02,  5.2610e-02,  5.7611e-02,
                       3.5402e-02,  1.0883e-02,  1.6156e-02,  3.3937e-05, -3.6660e-02,
                      -5.7634e-02,  4.7715e-02, -5.6990e-02, -2.9563e-02, -1.5804e-02,
                      -7.7304e-03, -2.3213e-02,  1.0522e-02,  7.7650e-04])),
             ('text_trs.weight',
              tensor([[ 0.0131,  0.0088,  0.0268,  ..., -0.0124, -0.0307, -0.0078],
                      [-0.0226, -0.0277, -0.0082,  ..., -0.0271,  0.0287, -0.0072],
                      [-0.0059, -0.0541, -0.0104,  ...,  0.0138, -0.0706,  0.0338],
                      ...,
                      [ 0.0180, -0.0394,  0.0193,  ..., -0.0081, -0.0078, -0.0256],
                      [-0.0115, -0.0117, -0.0361,  ...,  0.0148, -0.0256, -0.0163],
                      [ 0.0178, -0.0403,  0.0357,  ..., -0.0465, -0.0284,  0.0468]])),
             ('text_trs.bias',
              tensor([ 0.0576,  0.0757,  0.0719,  0.0630,  0.0386,  0.0491, -0.0725, -0.1000,
                      -0.0877, -0.0376, -0.1010, -0.0897,  0.0930,  0.0456,  0.0495,  0.0293,
                       0.0236,  0.0437,  0.0364,  0.0087,  0.0913, -0.0399, -0.0106, -0.0550,
                      -0.0037, -0.0717, -0.0039, -0.0288, -0.0369, -0.0142,  0.0789, -0.0185,
                       0.0611,  0.1325, -0.0021,  0.0729,  0.0266, -0.0277,  0.0239, -0.0779,
                      -0.1200, -0.0028,  0.0136, -0.0392, -0.0873,  0.0716,  0.0828,  0.0688,
                       0.0258, -0.0200,  0.0927, -0.0147, -0.0721,  0.0092,  0.0467, -0.0416,
                      -0.0665, -0.0628, -0.0174, -0.0139, -0.0486, -0.0695,  0.0077,  0.0961])),
             ('query_v.0.weight',
              tensor([[ 0.0376,  0.0495, -0.0162,  ..., -0.0015,  0.0856,  0.0447],
                      [-0.1047, -0.0422,  0.1038,  ..., -0.0474, -0.1050, -0.0679],
                      [-0.0870, -0.0660, -0.0458,  ..., -0.0395, -0.0516,  0.0414],
                      ...,
                      [ 0.0764, -0.0903, -0.0732,  ...,  0.0524,  0.0242,  0.0153],
                      [-0.0770, -0.0179, -0.1054,  ...,  0.1247,  0.0031,  0.1220],
                      [-0.0377, -0.0476, -0.0146,  ..., -0.1058, -0.0591,  0.1047]])),
             ('query_v.0.bias',
              tensor([-0.0622, -0.0280, -0.0085,  0.0612, -0.0265,  0.0039,  0.0310, -0.0013,
                      -0.0546,  0.0100,  0.0541,  0.0411,  0.0060,  0.0211,  0.0229,  0.0914,
                       0.0166, -0.0290, -0.0801,  0.0576,  0.0471, -0.0568,  0.0846, -0.0833,
                      -0.0916,  0.0593, -0.0078,  0.0440, -0.0939,  0.0228,  0.0510, -0.0247,
                      -0.0597, -0.0328, -0.0638,  0.0007, -0.0379,  0.0088,  0.0002, -0.0444,
                      -0.0296, -0.0159,  0.0053,  0.0731,  0.0764, -0.0188, -0.0048, -0.0114,
                      -0.0715, -0.0333,  0.0498,  0.0229,  0.0595, -0.0634, -0.0015, -0.0737,
                       0.0766, -0.0031,  0.0425, -0.0659, -0.0622,  0.0040, -0.0676,  0.0047])),
             ('query_v.2.weight',
              tensor([[ 0.0832, -0.0602, -0.0704,  ...,  0.0771,  0.1119, -0.1185],
                      [ 0.0735, -0.1223,  0.0366,  ..., -0.1071, -0.0428, -0.0694],
                      [ 0.1194,  0.1293, -0.1021,  ...,  0.0018,  0.0723, -0.0811],
                      ...,
                      [ 0.0016, -0.0027, -0.0697,  ...,  0.0957, -0.0468,  0.0912],
                      [-0.0824,  0.0376,  0.0716,  ..., -0.0834,  0.1161,  0.0681],
                      [ 0.1235, -0.0019,  0.1232,  ...,  0.0391,  0.0334,  0.0177]])),
             ('query_t.0.weight',
              tensor([[-0.1069, -0.0565,  0.0124,  ...,  0.1073,  0.0212, -0.0551],
                      [-0.0944,  0.0067, -0.0174,  ..., -0.0015, -0.0389,  0.0566],
                      [ 0.0684, -0.0288, -0.0849,  ..., -0.0221,  0.1155, -0.1270],
                      ...,
                      [-0.0001, -0.1069,  0.1272,  ..., -0.0262,  0.1098,  0.0383],
                      [-0.0751, -0.0248, -0.0904,  ...,  0.1190,  0.0084, -0.0803],
                      [ 0.0998, -0.0370, -0.0728,  ...,  0.0391, -0.0686,  0.0854]])),
             ('query_t.0.bias',
              tensor([ 0.1143,  0.0488, -0.1311,  0.0436, -0.0474, -0.0129,  0.0028, -0.0166,
                       0.0119, -0.0705,  0.1334,  0.1070,  0.0843, -0.0769, -0.0627,  0.0954,
                       0.0540,  0.0745, -0.0695, -0.0910, -0.1305,  0.0289,  0.0413,  0.0375,
                       0.0748,  0.0693, -0.0614,  0.1084, -0.0701, -0.0922, -0.0763, -0.1259,
                      -0.0066,  0.0946,  0.0713,  0.0540, -0.0303, -0.0143, -0.1091, -0.0912,
                       0.0936, -0.0246, -0.0644,  0.1399, -0.0684,  0.0745, -0.0623,  0.0218,
                      -0.0183, -0.0912,  0.1239, -0.0449,  0.0261, -0.1058, -0.0728, -0.0517,
                       0.0626, -0.0670,  0.0757, -0.0619,  0.1052,  0.0398, -0.0637,  0.0404])),
             ('query_t.2.weight',
              tensor([[-0.0119, -0.0252,  0.0144,  ..., -0.0376,  0.0347,  0.0775],
                      [ 0.0769, -0.0453, -0.0523,  ...,  0.0133,  0.0344,  0.0915],
                      [-0.0802, -0.0018, -0.0704,  ..., -0.0131, -0.0410,  0.1149],
                      ...,
                      [-0.0665,  0.0309, -0.0816,  ...,  0.0976,  0.1130, -0.0706],
                      [ 0.0842, -0.0964, -0.0074,  ..., -0.1126,  0.0034, -0.0298],
                      [ 0.1205, -0.0384,  0.0342,  ...,  0.0783,  0.0593,  0.1212]])),
             ('gate_v.0.weight',
              tensor([[ 0.0481, -0.1562,  0.0727,  ..., -0.0498, -0.0900, -0.1021],
                      [ 0.0377, -0.0546, -0.0802,  ..., -0.0099, -0.0965, -0.0501],
                      [-0.0646, -0.0836, -0.0575,  ..., -0.0100,  0.0490,  0.0966],
                      ...,
                      [ 0.0327, -0.0445,  0.0675,  ...,  0.1133,  0.1145, -0.0513],
                      [-0.0885, -0.0281, -0.1437,  ..., -0.0664,  0.0356, -0.0588],
                      [ 0.0949,  0.0576, -0.1209,  ...,  0.1237,  0.1211, -0.0730]])),
             ('gate_v.0.bias',
              tensor([ 0.0700, -0.0636,  0.0372,  0.1010, -0.0958,  0.0524, -0.0204,  0.1353,
                       0.0503,  0.1181,  0.1352, -0.0782,  0.0549,  0.0290,  0.1451, -0.0199,
                      -0.0307,  0.0852, -0.0665,  0.1382,  0.0749,  0.0806,  0.0194, -0.0519,
                       0.0742, -0.0465,  0.0888,  0.0617, -0.0588,  0.0386,  0.0434, -0.0474,
                      -0.0768, -0.0640,  0.1041, -0.0378,  0.1295, -0.0484,  0.0369,  0.1429,
                       0.0422,  0.0889, -0.0189,  0.0570, -0.0135,  0.0743, -0.0007,  0.0241,
                      -0.0308,  0.1234,  0.1193,  0.0574, -0.0533,  0.0916,  0.1268,  0.0603,
                      -0.0106,  0.0605,  0.0926,  0.0417,  0.0331,  0.0628, -0.0802, -0.0101])),
             ('gate_t.0.weight',
              tensor([[-0.1161, -0.0924,  0.0427,  ..., -0.1342, -0.2390,  0.0487],
                      [-0.0944, -0.2394,  0.1639,  ..., -0.2805, -0.1943,  0.0872],
                      [-0.2358, -0.2134,  0.0681,  ..., -0.2735, -0.2701,  0.1304],
                      ...,
                      [-0.0567, -0.0514,  0.1019,  ..., -0.2976, -0.2190,  0.2064],
                      [-0.2355, -0.2527, -0.1005,  ..., -0.0807, -0.2541,  0.0793],
                      [-0.0650, -0.4387, -0.0644,  ..., -0.3770, -0.1191,  0.2425]])),
             ('gate_t.0.bias',
              tensor([ 0.0449,  0.1880,  0.0643,  0.1555,  0.0497,  0.1271,  0.2433,  0.0643,
                       0.1494,  0.1720,  0.1645,  0.0512,  0.0902,  0.2405,  0.2284,  0.1715,
                       0.0574,  0.1004,  0.1620,  0.1753,  0.1337,  0.2014,  0.0745,  0.1079,
                       0.2272,  0.0625,  0.1170,  0.1018,  0.2197,  0.1537,  0.0448,  0.0479,
                       0.2249,  0.2307,  0.0876,  0.1766,  0.0216,  0.1033,  0.1059,  0.1384,
                      -0.0259,  0.0982,  0.1906,  0.1423,  0.0289,  0.0882,  0.2186,  0.1841,
                       0.0780,  0.0067,  0.1680, -0.0009,  0.0858,  0.0859,  0.1876,  0.0806,
                       0.0932,  0.0561,  0.2648,  0.2005, -0.0069,  0.1377,  0.0639,  0.0783])),
             ('gate_f.0.weight',
              tensor([[ 0.0786,  0.0037,  0.0792,  ...,  0.0046,  0.0651, -0.0220],
                      [-0.0603, -0.0901, -0.0730,  ..., -0.1117,  0.0346, -0.0979],
                      [ 0.0613, -0.0524,  0.0856,  ..., -0.0510, -0.0867, -0.0435],
                      ...,
                      [-0.1182,  0.0923,  0.1334,  ..., -0.1213,  0.0865, -0.0381],
                      [-0.0702, -0.0280,  0.0471,  ..., -0.0266,  0.1088, -0.0781],
                      [-0.0805, -0.0514,  0.0829,  ...,  0.0246,  0.0596, -0.0330]])),
             ('gate_f.0.bias',
              tensor([ 0.0263,  0.0452, -0.0390, -0.0778,  0.0119, -0.0913,  0.0918, -0.0288,
                      -0.0425, -0.0547, -0.0961,  0.0386, -0.0218,  0.0192, -0.0079,  0.0944,
                      -0.0303,  0.0220,  0.0289, -0.0762,  0.0640, -0.1389,  0.0645,  0.0843,
                       0.0184,  0.0547,  0.0845,  0.0263,  0.0334, -0.0362, -0.0451,  0.0456,
                       0.0043,  0.0917,  0.0907, -0.1222, -0.0325,  0.0248,  0.0553,  0.0632,
                      -0.0512, -0.0280, -0.0746,  0.0297,  0.0158,  0.0051,  0.0686, -0.1391,
                      -0.0333, -0.0250,  0.0648,  0.0039,  0.0565,  0.0553, -0.0750, -0.0484,
                      -0.0723,  0.0682, -0.0730, -0.0554, -0.0060,  0.0558,  0.0461,  0.0274])),
             ('gate_image_prefer.0.weight',
              tensor([[-0.0003,  0.0467,  0.0849,  ..., -0.0781, -0.1084, -0.1143],
                      [-0.1059,  0.0698, -0.1155,  ...,  0.0106,  0.0627,  0.1468],
                      [-0.0991,  0.0735,  0.0850,  ..., -0.0668, -0.0258, -0.0228],
                      ...,
                      [-0.1818, -0.0105,  0.0755,  ...,  0.1592, -0.0098, -0.0559],
                      [ 0.0728, -0.0023, -0.0070,  ...,  0.0269, -0.0740,  0.0483],
                      [ 0.0649,  0.0210,  0.0495,  ..., -0.0341, -0.1783, -0.1130]])),
             ('gate_image_prefer.0.bias',
              tensor([0.0977, 0.1175, 0.0954, 0.1329, 0.1121, 0.1113, 0.2220, 0.1323, 0.2626,
                      0.0871, 0.1972, 0.2285, 0.1993, 0.2743, 0.2090, 0.2266, 0.1871, 0.1073,
                      0.1754, 0.1987, 0.1825, 0.1025, 0.1727, 0.1113, 0.2611, 0.1304, 0.3377,
                      0.2469, 0.2420, 0.0993, 0.1080, 0.2115, 0.2417, 0.1839, 0.1777, 0.2096,
                      0.0893, 0.1376, 0.1853, 0.2769, 0.1551, 0.1743, 0.2498, 0.0667, 0.2629,
                      0.1152, 0.1119, 0.2047, 0.1810, 0.2205, 0.2085, 0.1601, 0.1994, 0.2589,
                      0.2912, 0.1445, 0.1427, 0.1851, 0.1810, 0.2619, 0.0798, 0.2073, 0.2353,
                      0.0759])),
             ('gate_text_prefer.0.weight',
              tensor([[ 0.0248,  0.0373,  0.0107,  ...,  0.0531, -0.1035,  0.0469],
                      [-0.1375, -0.1449,  0.0585,  ...,  0.1764, -0.1012,  0.1876],
                      [-0.0947,  0.0752, -0.0808,  ..., -0.0233,  0.0104, -0.0571],
                      ...,
                      [-0.0037,  0.1264, -0.0096,  ...,  0.0281,  0.0336, -0.0102],
                      [ 0.1165,  0.0404, -0.1173,  ...,  0.0994, -0.0261,  0.0754],
                      [ 0.0355,  0.1452, -0.1423,  ..., -0.0581, -0.0412, -0.1036]])),
             ('gate_text_prefer.0.bias',
              tensor([0.1164, 0.1094, 0.1649, 0.1714, 0.2373, 0.0704, 0.0921, 0.2383, 0.1979,

sports
The number of users: 35598
Average actions of users: 8.324540704533963
The number of items: 18357
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465195454304%
✓ Model loaded successfully!

In [26]:
import pandas as pd

In [ ]:
df_map_i_id = pd.read_csv('../data/sports/i_id_mapping.csv', sep="\t")

In [34]:
df_map_i_id.head(3)

         asin  itemID
0  1881509818       0
1  2094869245       1
2  7245456259       2

In [40]:
df_meta = pd.read_parquet(r"..\data\sports\meta_filtered.gzip.parquet")

In [42]:
df_meta.head(3)

,asin,title,price,imUrl,related,brand,categories,salesRank,description
0,1881509818,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,http://ecx.images-amazon.com/images/I/21iMxsyD...,"{'also_bought': ['B000U3YWEM', 'B000U401J6', '...",Ghost,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Ghost Armorer Tool (1). The GAT is made with a...
1,2094869245,5 LED Bicycle Rear Tail Red Bike Torch Laser B...,8.26,http://ecx.images-amazon.com/images/I/51RtwnJw...,"{'also_bought': ['B0081O93N2', 'B00EYTCHJA', '...",,"[[Sports & Outdoors, Cycling, Lights & Reflect...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",This newly-designed Laser tail light can emit ...
2,7245456313,Black Mountain Products Resistance Band Set wi...,32.99,http://ecx.images-amazon.com/images/I/51FdHlZS...,"{'also_bought': ['1612431712', 'B00GSBMW2Y', '...",Black Mountain,"[[Sports & Outdoors, Exercise & Fitness, Acces...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",[if gte mso 9]><xml> <o:OfficeDocumentSettings...

In [48]:
df_meta_map = pd.merge(left=df_meta, right=df_map_i_id, on="asin")

In [49]:
df_meta_map.info()

<class 'pandas.DataFrame'>
RangeIndex: 18357 entries, 0 to 18356
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         18357 non-null  str
 1   title        18267 non-null  str
 2   price        14764 non-null  float64
 3   imUrl        18325 non-null  str
 4   related      18236 non-null  object
 5   brand        12333 non-null  str
 6   categories   18357 non-null  object
 7   salesRank    16055 non-null  object
 8   description  16620 non-null  str
 9   itemID       18357 non-null  int64
dtypes: float64(1), int64(1), object(3), str(5)
memory usage: 13.0+ MB

In [111]:
df_meta_map.to_parquet(
    os.path.join('../data/sports', "df_meta_map.gzip.parquet"), 
    engine='pyarrow', 
    compression='gzip', 
    index=False
)

In [ ]:
df_map_u_id = pd.read_csv('../data/sports/u_id_mapping.csv', sep="\t")

In [50]:
df_map_u_id.head(3)

          user_id  userID
0    AIXZKN4ACSKI       0
1  A1L5P841VIO02V       1
2   AB2W04NI4OEAD       2

In [53]:
df_meta_reviews = pd.read_parquet(r"..\data\sports\meta_reviews_merged.gzip.parquet")

In [54]:
df_meta_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 296337 entries, 0 to 296336
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   asin            296337 non-null  str
 1   title           295091 non-null  str
 2   price           246116 non-null  float64
 3   imUrl           295896 non-null  str
 4   related         294878 non-null  object
 5   brand           217411 non-null  str
 6   categories      296337 non-null  object
 7   salesRank       256125 non-null  object
 8   description     273341 non-null  str
 9   reviewerID      296337 non-null  str
 10  reviewerName    294935 non-null  str
 11  helpful         296337 non-null  object
 12  reviewText      296337 non-null  str
 13  overall         296337 non-null  int64
 14  summary         296337 non-null  str
 15  unixReviewTime  296337 non-null  int64
 16  reviewTime      296337 non-null  str
dtypes: float64(1), int64(2), object(4), str(10)
memory usage: 389.6+ MB

In [72]:
df_user = df_meta_reviews[["reviewerID", "reviewerName"]].drop_duplicates().copy()

In [73]:
df_user.head(3)

       reviewerID     reviewerName
0    AIXZKN4ACSKI     David Briner
1  A1L5P841VIO02V  Jason A. Kramer
2   AB2W04NI4OEAD       J. Fernald

In [74]:
df_user.info()

<class 'pandas.DataFrame'>
Index: 36685 entries, 0 to 295881
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reviewerID    36685 non-null  str
 1   reviewerName  35664 non-null  str
dtypes: str(2)
memory usage: 1.7 MB

In [97]:
def get_dupes(df_user):
    duplicate_counts = df_user['reviewerID'].value_counts()
    # Lấy những ID xuất hiện > 1 lần
    print(duplicate_counts[duplicate_counts > 1])

    # keep=False sẽ đánh dấu True cho TẤT CẢ các dòng có reviewerID xuất hiện từ 2 lần trở lên
    df_all_dupes = df_user[df_user.duplicated(subset=['reviewerID'], keep=False)]

    # Sau đó bạn có thể sắp xếp lại để xem cho dễ
    df_all_dupes.sort_values(by='reviewerID', inplace=True)

    return df_all_dupes

In [98]:
df_all_dupes = get_dupes(df_user)

reviewerID
A18LMESO7EN5BQ    3
A19HT7YC1UW3D6    3
A1UKP70O8QHXRX    3
A2DG63DN704LOI    3
A2XB74S3PIU0VL    3
                 ..
AZ9QAIBGTLTLB     2
AZAK6ORS0OD75     2
AZJYKODF3GLQG     2
AZNUHQSHZHSUE     2
AZSLT1XWZ4ELG     2
Name: count, Length: 1080, dtype: int64

In [99]:
df_all_dupes.head(10)

            reviewerID   reviewerName
1510    A10CRW7XRJBJ2G          jjme9
265236  A10CRW7XRJBJ2G            NaN
117056  A10ZM3Q1NGI7LC       ShinUSMC
163079  A10ZM3Q1NGI7LC            NaN
56486   A1143YEAZYMYHJ  Jamie Ratliff
87130   A1143YEAZYMYHJ            NaN
14368   A116UOS8EL9KO1    Chuck Lynch
160482  A116UOS8EL9KO1            NaN
72413   A11I7D3736WP2K     Tonka Thom
245841  A11I7D3736WP2K            NaN

In [100]:
# 1. Sắp xếp để các dòng có reviewerName (không phải NaN) lên trên đầu
# Cấu trúc: NaN sẽ bị đẩy xuống cuối khi sắp xếp mặc định
df_user.sort_values(by=['reviewerID', 'reviewerName'], na_position='last', inplace=True)

# 2. Xóa các reviewerID trùng lặp, chỉ giữ lại dòng đầu tiên (dòng có tên tốt nhất)
df_user_unique = df_user.drop_duplicates(subset=['reviewerID'], keep='first')

# 3. (Tùy chọn) Nếu sau khi lọc vẫn còn những ID mà tên hoàn toàn là NaN ở mọi dòng
# và bạn muốn điền một giá trị mặc định để tránh lỗi khi train
df_user_unique['reviewerName'] = df_user_unique['reviewerName'].fillna('Unknown_Customer')

# 4. Kiểm tra lại kết quả
print(f"Số lượng User trước khi lọc: {len(df_user)}")
print(f"Số lượng User sau khi lọc: {len(df_user_unique)}")

# Kiểm tra xem còn ID nào bị lặp không
remaining_dupes = df_user_unique['reviewerID'].duplicated().sum()
print(f"Số lượng ID còn trùng (nên là 0): {remaining_dupes}")

Số lượng User trước khi lọc: 36685
Số lượng User sau khi lọc: 35598
Số lượng ID còn trùng (nên là 0): 0

In [89]:
df_user_unique

                   reviewerID         reviewerName
83327   A00046902LP5YSDV0VVNF         david borque
10676    A0029274J35Q1MYNKUWO                   JM
103117  A004507634IQ8TNQ3YTUI          CHRIS PARKS
12593   A005011233SVRED9Q0VY0            Robert L.
14082   A00676013IBZZQ3UYWK47             tank6192
...                       ...                  ...
7449            AZYP4FQ2L2C4O          Mom of Four
23991           AZYVD25M8Y4A2           Rambo 2000
25035           AZZ3C4IINFHZQ      Raymond Jackson
116185          AZZDLE81QHUHE         Steven Moore
71315           AZZXSM5W248P8  David Rojas "David"

[35598 rows x 2 columns]

In [101]:
get_dupes(df_user_unique)

Series([], Name: count, dtype: int64)

Empty DataFrame
Columns: [reviewerID, reviewerName]
Index: []

In [106]:
df_user_unique.info()

<class 'pandas.DataFrame'>
Index: 35598 entries, 83327 to 71315
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reviewerID    35598 non-null  str
 1   reviewerName  35598 non-null  str
dtypes: str(2)
memory usage: 1.7 MB

In [107]:
df_map_u_id.info()

<class 'pandas.DataFrame'>
RangeIndex: 35598 entries, 0 to 35597
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  35598 non-null  str
 1   userID   35598 non-null  int64
dtypes: int64(1), str(1)
memory usage: 1.0 MB

In [124]:
df_user_map = pd.merge(left=df_user_unique, right=df_map_u_id, left_on="reviewerID", right_on="user_id").drop(columns=['user_id'])

In [125]:
df_user_map.info()

<class 'pandas.DataFrame'>
RangeIndex: 35598 entries, 0 to 35597
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reviewerID    35598 non-null  str
 1   reviewerName  35598 non-null  str
 2   userID        35598 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.7 MB

In [126]:
df_user_map.head(3)

              reviewerID  reviewerName  userID
0  A00046902LP5YSDV0VVNF  david borque   30020
1   A0029274J35Q1MYNKUWO            JM    8408
2  A004507634IQ8TNQ3YTUI   CHRIS PARKS   31830

In [127]:
df_user_map.to_parquet(
    os.path.join('../data/sports', "df_user_map.gzip.parquet"), 
    engine='pyarrow', 
    compression='gzip', 
    index=False
)

## Load model

In [6]:
import os

os.chdir("src")

In [7]:
import pandas as pd
df_meta_map = pd.read_parquet(r"..\data\sports\df_meta_map.gzip.parquet")
df_user_map = pd.read_parquet(r"..\data\sports\df_user_map.gzip.parquet")

In [8]:
import torch
from utils.configurator import Config
from utils.dataset import RecDataset
from utils.dataloader import TrainDataLoader
from utils.utils import get_model

def load_model(config: Config):
    # Load dataset
    dataset = RecDataset(config)

    # FIX: Trigger inter_num calculation
    print(dataset)  # This calls __str__() which sets inter_num
    # OR manually set it:
    # dataset.inter_num = len(dataset.df)

    # Now this works
    train_data = TrainDataLoader(config, dataset, batch_size=config['train_batch_size'], shuffle=False)

    # Convert list hyperparameters to scalars (pick first value)
    if isinstance(config['dropout_rate'], list):
        config['dropout_rate'] = config['dropout_rate'][0]
    if isinstance(config['n_ui_layers'], list):
        config['n_ui_layers'] = config['n_ui_layers'][0]
    if isinstance(config['image_knn_k'], list):
        config['image_knn_k'] = config['image_knn_k'][0]
    if isinstance(config['text_knn_k'], list):
        config['text_knn_k'] = config['text_knn_k'][0]
    if isinstance(config['reg_weight'], list):
        config['reg_weight'] = config['reg_weight'][0]

    # Now instantiate model
    model = get_model('SMORE')(config, train_data).to(config['device']) 

    return model

In [9]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

Using device: cpu

In [24]:
checkpoint = torch.load('./saved/SMORE_sports_seed999_n_ui_layers3_image_knn_k10_text_knn_k10_reg_weight0.0001_dropout_rate0_best.pth', weights_only=False, map_location=device)
checkpoint

{'epoch': 0,
 'config':
 gpu_id=0
 use_gpu=True
 seed=999
 data_path=../data/
 inter_splitting_label=x_label
 filter_out_cod_start_users=True
 is_multimodal_model=True
 checkpoint_dir=saved
 save_recommended_topk=True
 recommend_topk=recommend_topk/
 embedding_size=64
 weight_decay=0.0
 req_training=True
 epochs=1
 stopping_step=20
 train_batch_size=2048
 learner=adam
 learning_rate=0.001
 learning_rate_scheduler=[0.96, 50]
 eval_step=1
 training_neg_sample_num=1
 use_neg_sampling=True
 use_full_sampling=False
 NEG_PREFIX=neg__
 USER_ID_FIELD=userID
 ITEM_ID_FIELD=itemID
 TIME_FIELD=timestamp
 field_separator=
 metrics=['Recall', 'NDCG', 'Precision', 'MAP']
 topk=[5, 10, 20, 50]
 valid_metric=Recall@20
 eval_batch_size=4096
 use_raw_features=False
 max_txt_len=32
 max_img_size=256
 vocab_size=30522
 type_vocab_size=2
 hidden_size=4
 pad_token_id=0
 max_position_embeddings=512
 layer_norm_eps=1e-12
 hidden_dropout_prob=0.1
 end2end=False
 hyper_parameters=['seed', 'n_ui_layers', 'image_knn_k', 'text_knn_k', 'reg_weight', 'dropout_rate']
 inter_file_name=sports.inter
 vision_feature_file=image_feat.npy
 text_feature_file=text_feat.npy
 user_graph_dict_file=user_graph_dict.npy
 n_ui_layers=3
 n_layers=1
 lambda_coeff=0.9
 reg_weight=0.0001
 cl_loss=0.03
 temperature=0.2
 image_knn_k=10
 text_knn_k=10
 dropout_rate=0
 model=SMORE
 dataset=sports
 valid_metric_bigger=True
 device=cpu
 ,
 'cur_step': 0,
 'model_state_dict': OrderedDict([('image_complex_weight',
               tensor([[[-0.7803,  0.5151],
                        [ 0.3260, -0.8946],
                        [-2.2070,  0.5558],
                        [-0.8119,  0.2269],
                        [ 0.1907,  0.6837],
                        [-0.2569,  1.2938],
                        [ 0.5806, -1.4814],
                        [-3.2705, -0.6131],
                        [-1.3433, -0.2198],
                        [-0.0825,  0.6358],
                        [ 0.3826,  1.0346],
                        [ 0.7010,  1.9126],
                        [ 2.2455,  0.9741],
                        [-0.5455,  1.0943],
                        [ 0.5329,  0.3099],
                        [ 1.6390,  0.5951],
                        [-1.7329,  0.9973],
                        [-0.5316,  0.3880],
                        [ 0.2999, -0.9648],
                        [-1.4227,  0.2992],
                        [-1.8636,  0.3038],
                        [ 0.4898,  0.0182],
                        [ 1.5709,  0.0599],
                        [ 0.4855,  0.1270],
                        [ 1.0611,  1.4640],
                        [-0.0995,  0.2504],
                        [-0.7842,  0.2760],
                        [ 1.0852, -0.8787],
                        [ 0.7007,  1.6366],
                        [ 1.2729,  0.0937],
                        [ 0.9427, -0.4361],
                        [ 1.9856, -0.2591],
                        [-0.6983, -2.2491]]])),
              ('text_complex_weight',
               tensor([[[ 1.1947, -0.1765],
                        [ 0.7904, -1.2787],
                        [-0.7233, -0.1534],
                        [-1.1998,  0.5615],
                        [-0.9194, -1.8397],
                        [-0.4856, -1.9240],
                        [ 0.3603, -1.5588],
                        [-1.1217, -0.2673],
                        [-0.7386, -0.2055],
                        [-0.9141, -1.7950],
                        [ 0.4611, -0.5920],
                        [ 0.0747,  0.1220],
                        [ 0.1057, -0.0898],
                        [ 0.2497,  0.9190],
                        [ 0.6183,  1.7704],
                        [-0.9158,  0.0848],
                        [ 0.3281,  0.7695],
                        [ 1.1809, -0.0225],
                        [ 1.2818, -1.7815],
                        [-1.4822,  0.0515],
                        [ 1.2701, -0.8624],
                        [-0.3085,  0.0456],
                        [-2.2293,  1.0002],
                        [ 0.8270,  0.6286],
                        [ 1.3442,  0.7070],
                        [ 0.5681,  1.5586],
                        [ 1.0545, -0.8645],
                        [-0.9848,  2.0711],
                        [-0.4555,  0.8225],
                        [-1.0698,  1.8094],
                        [-0.1184,  0.4165],
                        [-1.3205,  1.6666],
                        [ 0.5787,  2.0615]]])),
              ('fusion_complex_weight',
               tensor([[[-0.9103, -1.5227],
                        [-0.4855,  0.4526],
                        [-0.3934, -1.1291],
                        [-0.0407,  0.9025],
                        [-1.3824, -0.1689],
                        [ 0.0805,  1.1927],
                        [-0.2993, -0.7984],
                        [-1.1645,  0.8707],
                        [-2.2074,  0.9625],
                        [-0.6726,  1.2495],
                        [ 1.0604, -0.0857],
                        [-1.1390, -1.6536],
                        [ 0.6001, -0.2551],
                        [-3.2135,  0.4970],
                        [ 0.2112, -0.9291],
                        [ 2.6690, -0.3161],
                        [-0.8727,  0.1337],
                        [ 0.7187, -1.1118],
                        [-0.8450,  0.3371],
                        [ 0.7030,  0.2034],
                        [-0.2664,  0.2332],
                        [ 0.0937,  1.1815],
                        [-0.0642, -0.2627],
                        [ 0.1079, -0.6514],
                        [-0.7837,  0.7069],
                        [-0.2290,  0.3327],
                        [ 0.0772, -2.2220],
                        [ 0.8795,  0.2652],
                        [ 0.2879, -2.0764],
                        [-0.7952, -0.9741],
                        [-0.5786, -1.8961],
                        [ 1.0447,  0.8619],
                        [-1.3455,  1.1054]]])),
              ('user_embedding.weight',
               tensor([[ 1.4839e-02, -1.6287e-02, -1.6017e-02,  ...,  1.8355e-02,
                         1.4997e-02,  1.5357e-02],
                       [ 1.0332e-02,  4.7333e-04, -1.6682e-02,  ...,  1.4855e-02,
                        -2.2156e-03,  1.5340e-02],
                       [ 5.2834e-03, -9.4019e-03, -1.7432e-02,  ...,  1.3994e-03,
                        -5.4617e-03,  1.5820e-02],
                       ...,
                       [-2.6687e-05, -4.4672e-03, -3.5811e-03,  ...,  3.8499e-03,
                        -2.3174e-03, -3.2857e-03],
                       [-7.8879e-03, -1.1206e-02, -1.7175e-03,  ...,  2.8017e-04,
                         9.0009e-03,  1.1925e-02],
                       [-9.0589e-03, -7.3118e-03, -6.5164e-03,  ..., -4.0111e-03,
                         1.4103e-02, -1.9697e-03]])),
              ('item_id_embedding.weight',
               tensor([[ 0.0302,  0.0014, -0.0192,  ...,  0.0391,  0.0191,  0.0184],
                       [-0.0170, -0.0299, -0.0153,  ...,  0.0237, -0.0014,  0.0025],
                       [-0.0223,  0.0087, -0.0180,  ...,  0.0125,  0.0121,  0.0009],
                       ...,
                       [-0.0108,  0.0059, -0.0140,  ...,  0.0077, -0.0061, -0.0101],
                       [-0.0033, -0.0103,  0.0136,  ...,  0.0013, -0.0102, -0.0214],
                       [ 0.0024, -0.0012, -0.0135,  ..., -0.0051,  0.0135, -0.0260]])),
              ('image_embedding.weight',
               tensor([[ 3.6178e-04,  5.2710e+00, -5.0889e-04,  ..., -1.7189e-03,
                         1.3044e-03, -3.2565e-05],
                       [ 9.7369e-04,  1.2633e-03,  4.5882e-04,  ...,  2.9891e+00,
                         4.1475e-01,  6.3154e-04],
                       [ 2.6558e-04, -6.2276e-05,  2.1216e-05,  ..., -2.6143e-04,
                         1.7266e+00,  2.3502e-04],
                       ...,
                       [ 2.1961e-04,  1.2993e-04,  7.6092e-04,  ...,  4.4459e-04,
                        -2.3203e-04, -6.9447e-04],
                       [-1.0743e-04,  3.4525e+00,  3.1248e-04,  ..., -8.9183e-04,
                         1.0761e-03, -5.8603e-04],
                       [ 7.2550e-04,  7.6169e-04,  9.7738e-04,  ...,  8.8998e-04,
                         9.3321e-04,  1.3090e+00]])),
              ('text_embedding.weight',
               tensor([[-0.1193,  0.0327, -0.0178,  ..., -0.1180,  0.0600,  0.0648],
                       [ 0.0168,  0.0126, -0.0116,  ...,  0.0339,  0.0362,  0.0565],
                       [-0.1261,  0.0548, -0.0154,  ..., -0.2002,  0.0401,  0.0588],
                       ...,
                       [-0.0014,  0.0103, -0.0172,  ..., -0.0895, -0.0152, -0.0109],
                       [-0.0648,  0.0461,  0.0231,  ..., -0.0662, -0.0617, -0.0095],
                       [-0.1186, -0.0197,  0.0038,  ..., -0.0540,  0.0148,  0.0323]])),
              ('image_trs.weight',
               tensor([[ 0.0027,  0.0044, -0.0084,  ..., -0.0112, -0.0143,  0.0083],
                       [ 0.0053,  0.0015,  0.0134,  ...,  0.0011,  0.0034,  0.0136],
                       [ 0.0061,  0.0112,  0.0018,  ..., -0.0160,  0.0189, -0.0068],
                       ...,
                       [-0.0053,  0.0102,  0.0021,  ..., -0.0346, -0.0161,  0.0110],
                       [ 0.0009, -0.0023, -0.0016,  ...,  0.0163, -0.0047, -0.0099],
                       [ 0.0317,  0.0123,  0.0147,  ..., -0.0051,  0.0046,  0.0161]])),
              ('image_trs.bias',
               tensor([ 8.3382e-03,  1.3234e-02,  4.8666e-03,  1.8253e-02, -1.3210e-02,
                       -1.5340e-03, -1.0010e-02,  1.1106e-02, -1.6828e-02,  3.0844e-03,
                       -1.2558e-02,  1.3977e-02,  1.0622e-02, -5.9865e-04, -7.0327e-03,
                       -3.4442e-03, -1.8906e-02, -9.4393e-03,  9.7324e-03,  2.5697e-02,
                       -1.8517e-02,  1.9028e-02, -6.2973e-03, -1.2289e-02, -7.2041e-03,
                        2.6440e-02,  7.3122e-04,  7.2193e-03, -3.1250e-03,  3.7031e-03,
                        1.0287e-02, -2.3083e-03,  3.9658e-05,  1.3649e-02,  2.5345e-02,
                        1.7751e-02,  1.4891e-02,  1.1126e-02,  4.9521e-03,  3.0144e-03,
                        1.4029e-02, -2.0590e-02, -1.5229e-02,  1.5766e-04, -1.2687e-02,
                       -2.0457e-03, -3.5373e-03,  8.3563e-03, -2.7216e-04,  9.5288e-03,
                        2.2143e-02, -3.8271e-03, -2.1224e-02, -5.9045e-03, -7.0455e-03,
                       -6.4887e-03,  2.1575e-02,  1.6355e-03,  2.4011e-02,  4.9823e-03,
                       -9.4460e-03, -1.8321e-03,  7.9288e-03,  1.5642e-02])),
              ('text_trs.weight',
               tensor([[ 0.0155,  0.0213,  0.0224,  ..., -0.0050, -0.0222,  0.0071],
                       [-0.0274, -0.0268,  0.0005,  ..., -0.0234,  0.0216, -0.0104],
                       [-0.0061, -0.0538,  0.0008,  ...,  0.0164, -0.0535,  0.0377],
                       ...,
                       [ 0.0096, -0.0484, -0.0011,  ..., -0.0067, -0.0004, -0.0157],
                       [-0.0130, -0.0270, -0.0316,  ...,  0.0067, -0.0239, -0.0133],
                       [ 0.0186, -0.0528,  0.0227,  ..., -0.0418, -0.0281,  0.0605]])),
              ('text_trs.bias',
               tensor([ 0.0173,  0.0380,  0.0130,  0.0288,  0.0046,  0.0217, -0.0115, -0.0302,
                       -0.0430,  0.0220, -0.0213, -0.0484,  0.0416,  0.0303,  0.0260, -0.0172,
                       -0.0258, -0.0109,  0.0307,  0.0103,  0.0466, -0.0432,  0.0216, -0.0022,
                        0.0313, -0.0035, -0.0273,  0.0338, -0.0049, -0.0181,  0.0088, -0.0025,
                        0.0137,  0.0446, -0.0442,  0.0492,  0.0214, -0.0041,  0.0379, -0.0441,
                       -0.0245,  0.0231, -0.0118, -0.0112, -0.0371,  0.0354,  0.0344,  0.0069,
                        0.0433, -0.0291,  0.0204, -0.0447, -0.0434,  0.0198,  0.0426, -0.0328,
                       -0.0168, -0.0163,  0.0222, -0.0023, -0.0357, -0.0349,  0.0136,  0.0328])),
              ('query_v.0.weight',
               tensor([[ 0.0368,  0.0507, -0.0152,  ..., -0.0009,  0.0875,  0.0516],
                       [-0.1075, -0.0425,  0.1012,  ..., -0.0504, -0.1042, -0.0683],
                       [-0.0855, -0.0658, -0.0458,  ..., -0.0369, -0.0497,  0.0393],
                       ...,
                       [ 0.0762, -0.0900, -0.0690,  ...,  0.0502,  0.0214,  0.0188],
                       [-0.0828, -0.0130, -0.1062,  ...,  0.1301,  0.0009,  0.1129],
                       [-0.0371, -0.0474, -0.0162,  ..., -0.1050, -0.0603,  0.1021]])),
              ('query_v.0.bias',
               tensor([-0.0873, -0.0797, -0.0183,  0.0985, -0.0899,  0.0422,  0.0621,  0.0252,
                       -0.0836,  0.0195,  0.0886,  0.0672,  0.0377,  0.0363,  0.0728,  0.1293,
                        0.0136, -0.0338, -0.0787,  0.1293,  0.1593, -0.0975,  0.1342, -0.1338,
                       -0.1178,  0.1440,  0.0041,  0.0878, -0.1137,  0.0763,  0.1045, -0.0720,
                       -0.0909, -0.0536, -0.0931, -0.0343, -0.0975,  0.0291,  0.0344, -0.0808,
                       -0.0856, -0.0584,  0.0074,  0.0951,  0.1279, -0.0767, -0.0167, -0.0647,
                       -0.0864, -0.0767,  0.0539,  0.0545,  0.1144, -0.1112,  0.0174, -0.1122,
                        0.1045,  0.0102,  0.0680, -0.1154, -0.0569, -0.0062, -0.1117,  0.0113])),
              ('query_v.2.weight',
               tensor([[ 0.0861, -0.0538, -0.0736,  ...,  0.0818,  0.1152, -0.1215],
                       [ 0.0926, -0.1083,  0.0572,  ..., -0.0970, -0.0254, -0.0818],
                       [ 0.1109,  0.1223, -0.1017,  ..., -0.0034,  0.0653, -0.0892],
                       ...,
                       [ 0.0211,  0.0195, -0.0386,  ...,  0.1161, -0.0270,  0.0748],
                       [-0.0646,  0.0571,  0.0897,  ..., -0.0662,  0.1336,  0.0613],
                       [ 0.0954, -0.0291,  0.1020,  ...,  0.0273,  0.0065,  0.0355]])),
              ('query_t.0.weight',
               tensor([[-0.1102, -0.0553,  0.0101,  ...,  0.1089,  0.0189, -0.0504],
                       [-0.0956,  0.0131, -0.0220,  ..., -0.0025, -0.0401,  0.0553],
                       [ 0.0648, -0.0254, -0.0820,  ..., -0.0174,  0.1129, -0.1246],
                       ...,
                       [ 0.0026, -0.1105,  0.1247,  ..., -0.0279,  0.1152,  0.0350],
                       [-0.0740, -0.0257, -0.0923,  ...,  0.1182,  0.0131, -0.0809],
                       [ 0.0953, -0.0375, -0.0724,  ...,  0.0308, -0.0673,  0.0889]])),
              ('query_t.0.bias',
               tensor([ 0.1039,  0.0358, -0.1215,  0.0322, -0.0736, -0.0191,  0.0164, -0.0071,
                        0.0057, -0.0367,  0.1378,  0.0808,  0.0876, -0.0885, -0.0636,  0.0870,
                        0.1042,  0.1090, -0.0860, -0.1038, -0.1281,  0.0495,  0.0102,  0.0092,
                        0.0598,  0.0749, -0.0411,  0.1022, -0.0776, -0.1082, -0.1162, -0.1210,
                        0.0143,  0.0937,  0.0591,  0.0325, -0.0527,  0.0009, -0.0901, -0.0893,
                        0.1125, -0.0588, -0.0738,  0.1374, -0.0828,  0.0917, -0.1004,  0.0418,
                       -0.0391, -0.0965,  0.1091, -0.0380,  0.0752, -0.1036, -0.0930, -0.0628,
                        0.0584, -0.0693,  0.0899, -0.0751,  0.1308,  0.0549, -0.0582,  0.0563])),
              ('query_t.2.weight',
               tensor([[-0.0150, -0.0280,  0.0168,  ..., -0.0384,  0.0385,  0.0768],
                       [ 0.0817, -0.0377, -0.0565,  ...,  0.0188,  0.0270,  0.0984],
                       [-0.0893, -0.0143, -0.0616,  ..., -0.0370, -0.0314,  0.1058],
                       ...,
                       [-0.0805,  0.0136, -0.0680,  ...,  0.0795,  0.1294, -0.0861],
                       [ 0.0694, -0.1049,  0.0081,  ..., -0.1199,  0.0159, -0.0412],
                       [ 0.1031, -0.0540,  0.0520,  ...,  0.0620,  0.0747,  0.1082]])),
              ('gate_v.0.weight',
               tensor([[ 0.0554, -0.1392,  0.0911,  ..., -0.0650, -0.1032, -0.0855],
                       [ 0.0389, -0.0492, -0.0688,  ..., -0.0208, -0.1050, -0.0411],
                       [-0.0631, -0.0819, -0.0489,  ..., -0.0160,  0.0465,  0.1035],
                       ...,
                       [ 0.0325, -0.0354,  0.0795,  ...,  0.1043,  0.1027, -0.0426],
                       [-0.1025, -0.0219, -0.1348,  ..., -0.0714,  0.0270, -0.0532],
                       [ 0.0950,  0.0603, -0.1129,  ...,  0.1160,  0.1150, -0.0684]])),
              ('gate_v.0.bias',
               tensor([ 0.0577, -0.0694,  0.0318,  0.0959, -0.1035,  0.0506, -0.0296,  0.1271,
                        0.0388,  0.1160,  0.1276, -0.0912,  0.0503,  0.0236,  0.1398, -0.0264,
                       -0.0413,  0.0775, -0.0698,  0.1343,  0.0618,  0.0778,  0.0110, -0.0560,
                        0.0694, -0.0507,  0.0610,  0.0499, -0.0658,  0.0342,  0.0364, -0.0528,
                       -0.0812, -0.0729,  0.0951, -0.0459,  0.1265, -0.0547,  0.0327,  0.1316,
                        0.0373,  0.0797, -0.0335,  0.0518, -0.0198,  0.0721, -0.0052,  0.0198,
                       -0.0448,  0.1150,  0.1135,  0.0503, -0.0589,  0.0840,  0.1219,  0.0497,
                       -0.0235,  0.0520,  0.0780,  0.0353,  0.0297,  0.0555, -0.0872, -0.0151])),
              ('gate_t.0.weight',
               tensor([[-5.5606e-02,  4.2662e-02,  3.2376e-03,  ...,  9.6619e-02,
                        -9.4321e-02, -6.2895e-02],
                       [ 6.1441e-05,  2.7196e-02,  7.6632e-02,  ...,  6.2473e-02,
                        -1.9951e-02, -1.1252e-01],
                       [-1.2036e-01, -1.9356e-02, -1.4352e-02,  ..., -3.2997e-02,
                        -9.6329e-02,  5.0547e-02],
                       ...,
                       [ 4.8989e-02,  6.2669e-02,  1.0312e-01,  ..., -1.1337e-01,
                        -6.1468e-02,  4.1111e-02],
                       [-1.3956e-01,  5.1793e-02, -1.3417e-01,  ...,  8.2991e-02,
                        -1.1150e-01, -9.0775e-02],
                       [ 2.0388e-02, -1.2574e-01, -1.0447e-01,  ..., -1.4087e-01,
                         1.1262e-02,  1.1489e-01]])),
              ('gate_t.0.bias',
               tensor([-0.0520,  0.1034, -0.0628,  0.0740, -0.0287,  0.0281,  0.1261, -0.0114,
                        0.0095,  0.1213,  0.1463, -0.0728,  0.0004,  0.1358,  0.1463,  0.1195,
                       -0.0695, -0.0057,  0.0429,  0.0886,  0.0266,  0.1071, -0.0222, -0.0071,
                        0.1235, -0.0646,  0.0306,  0.0255,  0.1462,  0.0691, -0.0635, -0.0552,
                        0.1207,  0.1324, -0.0121,  0.0803, -0.0710,  0.0364,  0.0148,  0.0055,
                       -0.0925, -0.0385,  0.1479,  0.0991, -0.0754,  0.0136,  0.1228,  0.0959,
                       -0.0467, -0.0597,  0.0754, -0.0753,  0.0089, -0.0117,  0.1131, -0.0304,
                       -0.0037, -0.0297,  0.1498,  0.1002, -0.0812,  0.0301, -0.0088, -0.0035])),
              ('gate_f.0.weight',
               tensor([[ 0.0741,  0.0022,  0.0793,  ...,  0.0307,  0.0714,  0.0165],
                       [-0.0710, -0.1256, -0.0901,  ..., -0.0886,  0.0246, -0.1154],
                       [ 0.0762, -0.0679,  0.0630,  ..., -0.0469, -0.1146, -0.0317],
                       ...,
                       [-0.1380,  0.0852,  0.1204,  ..., -0.1132,  0.0778, -0.0389],
                       [-0.1259, -0.0492,  0.0259,  ..., -0.0020,  0.1036, -0.1090],
                       [-0.1240, -0.0958,  0.0468,  ...,  0.0417,  0.0624, -0.0246]])),
              ('gate_f.0.bias',
               tensor([ 0.0449,  0.0708, -0.0121, -0.0505,  0.0388, -0.0586,  0.1123, -0.0044,
                       -0.0111, -0.0281, -0.0722,  0.0706, -0.0027,  0.0404,  0.0176,  0.1217,
                       -0.0058,  0.0377,  0.0582, -0.0515,  0.0872, -0.1178,  0.0877,  0.1273,
                        0.0559,  0.0818,  0.1089,  0.0461,  0.0597,  0.0009, -0.0201,  0.0703,
                        0.0231,  0.1121,  0.1213, -0.0912, -0.0044,  0.0517,  0.0623,  0.0915,

In [11]:
checkpoint.keys()

dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'scheduler_state_dict', 'best_valid_score', 'best_valid_result', 'best_test_upon_valid'])

In [30]:
print(checkpoint["epoch"])
print(checkpoint["cur_step"])

0
0

In [12]:
checkpoint_tac_gia = torch.load('./saved/BM3-Apr-11-2023-13-24-15.pth', weights_only=False, map_location=device)
checkpoint_tac_gia

c:\projects\MMRec\.venv\Lib\site-packages\torch\serialization.py:2143: VisibleDeprecationWarning: dtype(): align should be passed as Python or NumPy boolean but got `align=0`. Did you mean to pass a tuple to create a subarray type? (Deprecated NumPy 2.4)
  result = unpickler.load()

{'config':
 gpu_id=7
 use_gpu=True
 seed=999
 data_path=../data/
 inter_splitting_label=x_label
 filter_out_cod_start_users=True
 is_multimodal_model=True
 checkpoint_dir=saved
 save_recommended_topk=True
 recommend_topk=recommend_topk/
 embedding_size=64
 epochs=1000
 stopping_step=20
 train_batch_size=2048
 learner=adam
 learning_rate=0.001
 learning_rate_scheduler=[1.0, 50]
 eval_step=1
 training_neg_sample_num=1
 use_neg_sampling=False
 use_full_sampling=False
 NEG_PREFIX=neg__
 USER_ID_FIELD=userID
 ITEM_ID_FIELD=itemID
 TIME_FIELD=timestamp
 field_separator=
 metrics=['Recall', 'NDCG', 'Precision', 'MAP']
 topk=[5, 10, 20, 50]
 valid_metric=Recall@20
 eval_batch_size=4096
 use_raw_features=False
 max_txt_len=32
 max_img_size=256
 vocab_size=30522
 type_vocab_size=2
 hidden_size=4
 pad_token_id=0
 max_position_embeddings=512
 layer_norm_eps=1e-12
 hidden_dropout_prob=0.1
 end2end=False
 hyper_parameters=['n_layers', 'reg_weight', 'dropout', 'seed']
 inter_file_name=sports14-indexed-v4.inter
 vision_feature_file=image_feat.npy
 text_feature_file=text_feat-v1.npy
 user_graph_dict_file=user_graph_dict.npy
 feat_embed_dim=64
 n_layers=1
 dropout=0.5
 reg_weight=0.01
 cl_weight=2.0
 model=BM3
 dataset=sports
 valid_metric_bigger=True
 device=cuda
 ,
 'epoch': 237,
 'cur_step': 0,
 'best_valid_score': np.float64(0.0962),
 'state_dict': OrderedDict([('user_embedding.weight',
               tensor([[-2.1196e-01, -9.6717e-02,  2.3216e-01,  ..., -1.1524e-01,
                        -3.2315e-02,  5.7769e-02],
                       [ 6.9919e-02, -3.6342e-01,  1.5663e-01,  ..., -1.1853e-02,
                        -8.5660e-02, -1.9808e-02],
                       [-5.7603e-02, -1.9437e-01,  1.7314e-01,  ...,  4.9979e-02,
                        -5.9130e-03, -4.6551e-02],
                       ...,
                       [ 1.7105e-01,  1.8195e-01,  2.2336e-01,  ..., -2.1690e-02,
                        -1.7718e-01,  1.7421e-01],
                       [ 6.4586e-02,  1.9345e-01,  5.1303e-03,  ...,  1.8928e-04,
                        -5.4906e-04,  1.5335e-01],
                       [ 3.6971e-02,  2.6268e-01,  1.7601e-02,  ..., -8.1829e-02,
                        -8.4475e-02,  1.1679e-01]])),
              ('item_id_embedding.weight',
               tensor([[ 0.0722, -0.0718,  0.1055,  ..., -0.2042, -0.0254, -0.0552],
                       [-0.0626, -0.0745, -0.2667,  ...,  0.2361, -0.0611,  0.0457],
                       [ 0.0406,  0.0228, -0.0412,  ..., -0.0490, -0.0921,  0.0518],
                       ...,
                       [ 0.2017,  0.0405,  0.1713,  ...,  0.0171, -0.1703,  0.2671],
                       [ 0.2163,  0.0426,  0.2697,  ...,  0.0923, -0.1579,  0.2409],
                       [ 0.1731,  0.0183,  0.2192,  ...,  0.0686, -0.1539,  0.2337]])),
              ('predictor.weight',
               tensor([[ 0.9561,  0.0410,  0.0074,  ..., -0.0897, -0.0917,  0.0014],
                       [ 0.0485,  0.7631,  0.0808,  ...,  0.2513, -0.1155,  0.1664],
                       [ 0.0162,  0.0651,  0.7028,  ..., -0.0697, -0.0549, -0.2962],
                       ...,
                       [-0.0805,  0.2715, -0.0704,  ...,  0.7711,  0.0753, -0.1076],
                       [-0.0931, -0.1199, -0.0431,  ...,  0.0515,  1.0707, -0.2261],
                       [ 0.0080,  0.1707, -0.2618,  ..., -0.1106, -0.1943,  1.0025]])),
              ('predictor.bias',
               tensor([ 0.0151, -0.0256,  0.0041,  0.0166, -0.0404, -0.0064,  0.0077, -0.0211,
                       -0.0023, -0.0215, -0.0097, -0.0447,  0.0013, -0.0145, -0.0220,  0.0318,
                        0.0069,  0.0037,  0.0013, -0.0183, -0.0115,  0.0059,  0.0167,  0.0016,
                        0.0160, -0.0150, -0.0425, -0.0055, -0.0459, -0.0517, -0.0049, -0.0111,
                       -0.0333,  0.0708,  0.0325,  0.0197,  0.0298, -0.0014, -0.0233,  0.0137,
                       -0.0335, -0.0105,  0.0154,  0.0359,  0.0267, -0.0280, -0.0121, -0.0323,
                        0.0351, -0.0008,  0.0217,  0.0341, -0.0493, -0.0161, -0.0290, -0.0319,
                       -0.0041, -0.0234,  0.0519, -0.0118, -0.0211, -0.0534,  0.0042,  0.0058])),
              ('image_embedding.weight',
               tensor([[-0.0798,  5.4166,  0.3581,  ...,  0.1615,  0.0769,  0.1191],
                       [ 0.3315, -0.2218,  0.1327,  ...,  2.8868,  0.5015, -0.0802],
                       [-0.0952,  0.0626,  0.0396,  ...,  0.0972,  1.6919,  0.1841],
                       ...,
                       [-0.0173,  0.0906,  0.1777,  ...,  0.1513, -0.0774,  0.2995],
                       [ 0.0834,  3.4683,  0.2710,  ...,  0.1352, -0.1163,  0.4633],
                       [ 0.0107, -0.0135,  0.2731,  ...,  0.2219, -0.2041,  1.5877]])),
              ('image_trs.weight',
               tensor([[ 0.2119,  0.1574,  0.0013,  ...,  0.0061, -0.0010,  0.0334],
                       [-0.1985, -0.1285,  0.0977,  ...,  0.0692, -0.1054, -0.0761],
                       [-0.0536,  0.1243,  0.0019,  ..., -0.2615, -0.0725,  0.1520],
                       ...,
                       [ 0.0625, -0.2990,  0.0096,  ..., -0.0027, -0.1570,  0.0076],
                       [-0.2918, -0.1210, -0.0388,  ...,  0.0095, -0.1975, -0.1121],
                       [-0.2906,  0.0344, -0.0513,  ...,  0.1397, -0.0097,  0.0047]])),
              ('image_trs.bias',
               tensor([ 0.0432, -0.0084,  0.0124, -0.0283, -0.0443,  0.0121,  0.0165, -0.0142,
                       -0.0010,  0.0021, -0.0083, -0.0528,  0.0214,  0.0199, -0.0124, -0.0014,
                       -0.0161,  0.0381, -0.0101, -0.0097, -0.0310, -0.0019,  0.0045,  0.0213,
                        0.0539,  0.0024, -0.0915, -0.0237, -0.0241, -0.0483,  0.0440,  0.0033,
                       -0.0292,  0.0545,  0.0186,  0.0657,  0.0087,  0.0004, -0.0468, -0.0009,
                       -0.0041, -0.0329, -0.0318,  0.0098, -0.0080, -0.0041,  0.0146,  0.0084,
                        0.0468,  0.0082,  0.0019,  0.0410,  0.0042, -0.0220, -0.0606, -0.0444,
                       -0.0326, -0.0084,  0.0348, -0.0089, -0.0057, -0.0241,  0.0134,  0.0014])),
              ('text_embedding.weight',
               tensor([[-0.1171,  0.1168,  0.0846,  ..., -0.1138,  0.1232,  0.2224],
                       [ 0.0460, -0.0093, -0.1554,  ...,  0.1254, -0.0314, -0.0049],
                       [-0.2074, -0.2008,  0.4144,  ..., -0.0516,  0.0292,  0.3518],
                       ...,
                       [-0.0335,  0.1122,  0.1513,  ..., -0.2410,  0.0531, -0.1017],
                       [-0.0782,  0.1508,  0.2031,  ..., -0.1915, -0.0253, -0.1784],
                       [-0.2455,  0.1552,  0.1724,  ..., -0.2619,  0.0764, -0.0280]])),
              ('text_trs.weight',
               tensor([[-2.3285e-01,  5.2452e-03, -3.2947e-02,  ..., -1.4890e-01,
                        -2.1417e-02, -1.1919e-01],
                       [ 1.0034e-01,  1.4174e-01,  1.0088e-01,  ..., -3.5682e-04,
                         3.0180e-02, -6.5340e-02],
                       [ 9.3230e-02, -7.8052e-02,  4.7934e-01,  ..., -1.6514e-01,
                         7.8814e-02, -3.5246e-01],
                       ...,
                       [ 1.5758e-02,  1.1035e-01,  8.3748e-02,  ...,  1.6445e-02,
                        -1.7522e-01, -7.2123e-02],
                       [ 1.6102e-01,  5.0079e-02, -1.8019e-01,  ..., -7.9302e-02,
                         5.6709e-02,  2.5403e-01],
                       [ 1.1562e-01,  1.0113e-01, -2.4583e-01,  ...,  3.1709e-02,
                        -2.8516e-02, -4.8924e-02]])),
              ('text_trs.bias',
               tensor([ 0.1019, -0.0067,  0.0690,  0.0183, -0.1687, -0.0664, -0.0153, -0.1447,
                        0.0567, -0.1305, -0.2337, -0.2918,  0.1888, -0.1517, -0.0909,  0.1077,
                       -0.0068,  0.0181, -0.0556, -0.1133, -0.1943, -0.0101,  0.0519, -0.0883,
                        0.1535, -0.2125, -0.3243, -0.0560, -0.2953, -0.2984, -0.1881, -0.0018,
                       -0.2982,  0.3512,  0.1323,  0.1051,  0.0789,  0.0424, -0.1228, -0.0595,
                       -0.0769,  0.0382,  0.1047,  0.1675,  0.0900, -0.2842,  0.0259, -0.0789,
                        0.1409,  0.1240,  0.1531,  0.0766, -0.1264, -0.1212, -0.2274, -0.1146,
                       -0.1160,  0.0100,  0.2760, -0.0229, -0.0901, -0.2098,  0.1581,  0.1756]))]),
 'optimizer': {'state': {0: {'step': 25466,
    'exp_avg': tensor([[-6.8882e-07, -1.2241e-06,  2.8265e-06,  ..., -2.4468e-07,
              2.9447e-06,  1.4239e-06],
            [-3.3804e-06,  1.4585e-06,  6.0607e-07,  ...,  1.7338e-06,
              1.6452e-06, -5.8073e-07],
            [ 1.3612e-07,  3.9212e-07, -3.0821e-07,  ..., -1.5826e-06,
              8.2550e-07, -2.9203e-09],
            ...,
            [-1.2538e-07,  3.0764e-07,  4.3960e-07,  ...,  3.4618e-07,
              4.4492e-07, -4.1024e-07],
            [ 4.2428e-07,  4.2641e-07,  9.4519e-08,  ..., -5.1350e-07,
             -1.1095e-07, -2.8555e-08],
            [-5.7176e-07, -4.7089e-07,  3.6439e-07,  ...,  1.6590e-07,
             -3.1449e-07, -9.9818e-07]]),
    'exp_avg_sq': tensor([[2.4350e-11, 3.8118e-11, 4.0473e-11,  ..., 5.3999e-11, 2.4134e-11,
             4.1539e-11],
            [1.2830e-10, 7.1565e-11, 1.1640e-10,  ..., 9.3058e-11, 1.1748e-10,
             6.2279e-11],
            [1.1436e-10, 8.6529e-11, 9.3927e-11,  ..., 1.0502e-10, 1.3093e-10,
             1.0909e-10],
            ...,
            [4.1110e-11, 3.1298e-11, 4.8042e-11,  ..., 2.7429e-11, 4.8199e-11,
             4.6144e-11],
            [1.0923e-11, 1.9817e-11, 1.0303e-11,  ..., 1.1908e-11, 1.2553e-11,
             2.9496e-11],
            [1.8666e-11, 1.5134e-11, 1.3236e-11,  ..., 1.5648e-11, 1.5505e-11,
             1.6881e-11]])},
   1: {'step': 25466,
    'exp_avg': tensor([[-1.7944e-06,  4.2537e-06,  9.6247e-06,  ..., -2.8216e-06,
             -4.4882e-07, -9.8047e-06],
            [ 1.6023e-06,  5.6850e-07,  5.2786e-07,  ..., -1.8350e-06,
             -1.4585e-06,  1.2608e-06],
            [ 3.8986e-08, -5.6923e-09,  2.2339e-07,  ..., -1.3081e-07,
             -1.7680e-07,  1.7956e-07],
            ...,
            [-1.6285e-06, -4.7656e-07, -9.5756e-08,  ...,  1.7464e-06,
              1.0213e-06, -3.9722e-06],
            [-1.7458e-06,  1.3963e-06,  1.0821e-06,  ...,  5.6512e-07,
              1.4612e-06, -1.2368e-06],
            [ 2.6149e-06, -6.1973e-06,  3.1629e-06,  ...,  9.4115e-07,
             -1.3167e-06, -6.4031e-07]]),
    'exp_avg_sq': tensor([[3.7424e-11, 5.7044e-11, 4.2935e-11,  ..., 3.8069e-11, 5.9506e-11,
             5.3896e-11],
            [6.4286e-11, 7.9898e-11, 9.9533e-11,  ..., 1.0057e-10, 9.3030e-11,
             7.6151e-11],
            [6.4704e-11, 5.1684e-11, 3.3996e-11,  ..., 4.9504e-11, 5.4908e-11,
             4.9496e-11],
            ...,
            [4.3515e-11, 7.7462e-11, 5.3293e-11,  ..., 5.0491e-11, 6.8379e-11,
             9.1987e-11],
            [7.3121e-11, 7.8377e-11, 6.6156e-11,  ..., 4.2328e-11, 6.5155e-11,
             8.0113e-11],
            [1.4804e-10, 2.0677e-10, 1.2232e-10,  ..., 1.3477e-10, 1.6226e-10,
             2.0551e-10]])},
   2: {'step': 25466,
    'exp_avg': tensor([[ 3.1745e-05,  2.1286e-04,  2.7400e-04,  ...,  5.3471e-05,
             -4.9711e-05, -1.4807e-04],
            [-4.5539e-05, -3.7175e-05,  4.8313e-05,  ...,  3.0555e-04,
             -2.6003e-05,  1.5438e-04],
            [ 1.8004e-04, -1.8557e-04,  9.2253e-05,  ..., -6.2662e-04,
             -1.5712e-04,  5.0491e-04],
            ...,
            [ 1.0551e-04, -3.3530e-04, -3.3887e-05,  ..., -4.3571e-04,
              1.4166e-04,  4.7197e-04],
            [-1.5432e-04, -1.8377e-05, -4.6743e-04,  ..., -4.4243e-05,
              3.6597e-04, -2.6414e-04],
            [-1.5739e-04, -1.1826e-05,  2.2381e-04,  ..., -4.8946e-05,
              3.1290e-04,  3.4759e-04]]),
    'exp_avg_sq': tensor([[2.0710e-06, 1.0396e-06, 8.2512e-07,  ..., 9.4493e-07, 8.6556e-07,
             8.7723e-07],
            [1.0391e-06, 2.2131e-06, 7.9275e-07,  ..., 1.1872e-06, 9.3343e-07,
             8.9332e-07],
            [9.3602e-07, 8.5710e-07, 1.8251e-06,  ..., 8.7148e-07, 7.7940e-07,
             8.8171e-07],
            ...,
            [1.1167e-06, 1.3906e-06, 1.0431e-06,  ..., 2.3585e-06, 9.9765e-07,
             1.0929e-06],
            [8.6108e-07, 9.1258e-07, 7.5808e-07,  ..., 8.6397e-07, 1.7453e-06,
             8.2543e-07],
            [1.0133e-06, 9.4192e-07, 8.9940e-07,  ..., 9.5842e-07, 9.3956e-07,
             2.0630e-06]])},
   3: {'step': 25466,
    'exp_avg': tensor([ 5.7573e-05,  5.1172e-04,  1.1658e-03,  6.1219e-04,  5.9063e-04,
             5.0534e-04, -4.3469e-04,  8.2431e-04, -1.7169e-04,  4.8339e-04,
            -1.7830e-04, -2.4881e-04,  4.0731e-04,  6.9726e-05,  1.6270e-03,
             7.8834e-04,  3.4018e-04,  3.0592e-04, -2.4590e-05, -4.6947e-04,
            -4.8241e-04, -8.3476e-04,  3.2338e-04, -3.8594e-04,  5.8963e-04,
            -6.4308e-04, -3.5524e-04, -6.3260e-04, -8.7888e-04,  6.9460e-04,
             2.6742e-04, -2.1074e-04, -2.4516e-04, -8.5108e-05, -2.7057e-04,
            -9.0349e-04, -6.0197e-04, -1.2212e-03, -7.0757e-04, -1.6043e-04,
             4.4824e-04, -2.1388e-04,  5.4602e-04, -8.4051e-04,  5.6832e-04,
            -7.5425e-04,  7.1439e-05,  2.6860e-04, -1.3378e-04, -2.3059e-04,
             7.5780e-05,  1.3787e-04, -3.9868e-04,  8.5162e-04, -7.5851e-04,
            -3.3129e-04,  8.1340e-05, -2.5241e-05,  1.1226e-03,  6.9721e-04,
             7.4918e-04,  1.0388e-03,  1.6886e-04,  1.9916e-04]),
    'exp_avg_sq': tensor([5.2894e-06, 5.7098e-06, 4.7016e-06, 5.1283e-06, 5.6755e-06, 5.1779e-06,
            4.7099e-06, 5.4932e-06, 5.2269e-06, 5.2821e-06, 4.6742e-06, 5.4992e-06,
            5.6513e-06, 7.9896e-06, 5.8315e-06, 5.6618e-06, 5.3710e-06, 4.9015e-06,
            4.3590e-06, 6.4448e-06, 5.8409e-06, 4.8098e-06, 5.3077e-06, 7.2195e-06,
            4.1373e-06, 5.5414e-06, 4.4163e-06, 5.5214e-06, 7.0238e-06, 5.7006e-06,
            5.8404e-06, 5.0275e-06, 5.1220e-06, 7.8614e-06, 6.1662e-06, 6.6653e-06,
            5.7279e-06, 4.8403e-06, 6.0310e-06, 6.2543e-06, 5.2401e-06, 5.1362e-06,
            5.1012e-06, 5.5715e-06, 5.5610e-06, 4.7760e-06, 5.1593e-06, 5.6838e-06,
            6.2105e-06, 5.3372e-06, 6.7097e-06, 4.5811e-06, 5.9714e-06, 5.4714e-06,
            5.8526e-06, 4.5993e-06, 5.0860e-06, 6.2164e-06, 6.0440e-06, 6.6191e-06,
            5.1486e-06, 6.8201e-06, 4.5797e-06, 5.2812e-06])},
   4: {'step': 25466,
    'exp_avg': tensor([[-6.4196e-08, -6.7959e-08, -1.4142e-07,  ...,  8.1632e-08,
             -3.2467e-08,  3.3017e-08],
            [-1.2667e-07,  5.9611e-08,  1.6313e-08,  ...,  2.3607e-08,
              4.1834e-08, -3.0052e-08],
            [-1.8714e-09, -1.2262e-09, -9.0745e-12,  ...,  1.3914e-09,
             -1.7562e-10, -9.7912e-10],
            ...,
            [-9.6106e-08, -2.4146e-10,  2.0119e-08,  ...,  3.2335e-08,
             -3.6385e-08, -3.2627e-08],
            [-3.4475e-08, -1.9314e-08,  7.9438e-09,  ..., -2.3370e-08,
             -1.2744e-08, -5.8714e-09],
            [-1.9435e-09, -2.9608e-08,  1.0325e-07,  ...,  4.9532e-08,
              4.5195e-08, -5.1564e-08]]),
    'exp_avg_sq': tensor([[9.1681e-14, 1.7692e-14, 1.6092e-14,  ..., 2.1214e-14, 1.3488e-14,
             1.2437e-14],
            [2.0378e-13, 2.9372e-14, 2.6900e-14,  ..., 5.4150e-14, 1.9889e-14,
             2.5900e-14],
            [1.4765e-13, 1.6125e-14, 1.9809e-14,  ..., 2.4215e-14, 1.1484e-14,
             1.5906e-14],
            ...,
            [7.8217e-14, 1.0915e-14, 1.1629e-14,  ..., 2.1564e-14, 1.8463e-14,
             1.4174e-14],
            [9.6789e-14, 1.7663e-14, 2.2071e-14,  ..., 2.5303e-14, 2.1354e-14,
             1.7520e-14],
            [2.2324e-13, 6.4006e-14, 5.9078e-14,  ..., 6.8946e-14, 4.9475e-14,
             6.0563e-14]])},
   5: {'step': 25466,
    'exp_avg': tensor([[-4.4805e-06, -1.3523e-05,  1.4421e-07,  ..., -1.3396e-05,
             -1.2260e-05, -4.1537e-05],
            [ 4.2038e-06, -3.8751e-06, -1.8659e-05,  ...,  8.6050e-08,
              1.3881e-05,  4.0396e-08],
            [ 1.7183e-06,  8.6666e-06, -1.4694e-05,  ..., -3.0782e-06,
              2.5251e-05,  6.6523e-06],
            ...,
            [ 6.0799e-06,  5.8322e-06, -1.9335e-06,  ..., -1.5012e-05,
              2.1915e-05, -8.3021e-06],
            [ 4.0429e-07,  9.2324e-06,  1.1769e-05,  ...,  1.6008e-05,
              1.0158e-05,  1.9762e-05],
            [ 4.8644e-06,  3.5918e-06,  7.9067e-06,  ...,  1.9133e-05,
              1.4555e-05,  3.0552e-05]]),
    'exp_avg_sq': tensor([[3.3489e-10, 2.2542e-09, 3.6849e-09,  ..., 2.3803e-09, 3.5110e-09,
             2.9907e-09],
            [3.5780e-10, 2.4704e-09, 4.0839e-09,  ..., 3.0578e-09, 3.9467e-09,
             3.4108e-09],
            [3.0837e-10, 2.0310e-09, 3.3853e-09,  ..., 2.4774e-09, 3.4659e-09,
             2.9203e-09],
            ...,
            [3.3469e-10, 2.2227e-09, 4.0891e-09,  ..., 2.6758e-09, 4.0224e-09,
             3.2085e-09],
            [3.1625e-10, 2.3592e-09, 3.3517e-09,  ..., 2.9335e-09, 3.4412e-09,
             3.1047e-09],
            [3.2904e-10, 2.5029e-09, 3.7007e-09,  ..., 2.8637e-09, 3.7237e-09,
             3.5322e-09]])},
   6: {'step': 25466,
    'exp_avg': tensor([-1.6904e-05, -3.1698e-07,  8.4752e-06, -4.5345e-06,  4.7824e-06,
             8.0076e-06, -2.9926e-06, -1.1366e-06,  6.8291e-07, -5.8913e-06,
            -1.1483e-05, -1.7683e-07, -9.5143e-06,  6.5537e-06, -2.6186e-06,
             8.2392e-06,  2.0685e-06,  1.2162e-05,  5.3730e-06, -4.5670e-07,
            -5.8902e-06, -2.5093e-06,  5.0774e-06,  1.7203e-05,  8.4152e-06,
             6.3144e-06, -4.0568e-06,  5.0088e-06,  4.8998e-07,  7.5156e-06,
            -8.0159e-06, -2.9799e-06,  2.3812e-06,  1.2080e-05,  1.0586e-05,
             4.2158e-06, -1.1316e-05, -1.0368e-05, -1.3832e-05,  3.0492e-06,
             6.9317e-06,  1.1496e-05,  2.7199e-06, -1.7022e-05,  9.3297e-06,
            -7.9600e-06,  2.8116e-06,  8.9941e-06, -1.2423e-05,  8.5282e-06,
             1.9819e-05,  1.9853e-06, -3.6456e-06,  2.4752e-06,  1.2339e-05,
             9.7104e-06,  1.4634e-05,  2.5684e-06, -2.3393e-06,  9.5076e-07,
            -2.2450e-06,  1.2940e-05,  6.1885e-06,  8.3815e-06]),
    'exp_avg_sq': tensor([1.6587e-09, 1.9710e-09, 1.5690e-09, 1.6951e-09, 1.8896e-09, 1.8543e-09,
            1.6779e-09, 2.0023e-09, 1.7436e-09, 1.6818e-09, 1.6071e-09, 1.6499e-09,
            2.0328e-09, 2.3735e-09, 1.8858e-09, 1.7886e-09, 1.8566e-09, 1.9085e-09,
            1.9123e-09, 2.2000e-09, 1.9680e-09, 2.0035e-09, 1.8411e-09, 2.2349e-09,
            1.3855e-09, 1.5939e-09, 1.9375e-09, 1.7109e-09, 2.0175e-09, 1.8864e-09,
            1.9443e-09, 1.5167e-09, 1.8077e-09, 2.2352e-09, 1.9312e-09, 2.0800e-09,
            2.0512e-09, 1.6168e-09, 1.9725e-09, 1.8994e-09, 1.9844e-09, 1.6881e-09,
            1.6608e-09, 1.9152e-09, 1.9093e-09, 1.9228e-09, 1.8183e-09, 2.0153e-09,
            2.0640e-09, 1.9096e-09, 2.1743e-09, 1.5625e-09, 1.6271e-09, 1.8189e-09,
            1.8050e-09, 1.6867e-09, 1.8109e-09, 1.8376e-09, 1.8315e-09, 2.1059e-09,
            1.7758e-09, 1.8394e-09, 1.7332e-09, 1.9006e-09])},
   7: {'step': 25466,
    'exp_avg': tensor([[ 7.5063e-07, -1.3477e-06,  4.7240e-06,  ...,  1.1682e-06,
             -2.3180e-06,  1.1009e-06],
            [ 1.4154e-06, -6.3627e-07,  6.4246e-07,  ...,  6.5502e-07,
              1.5029e-06,  2.0598e-07],
            [ 1.5244e-08, -1.7817e-08, -2.2984e-08,  ..., -2.6278e-08,
             -4.9057e-08,  4.8047e-08],
            ...,
            [ 1.1579e-06,  1.4518e-08,  2.3195e-07,  ...,  4.3085e-07,
              1.8191e-07,  1.1377e-06],
            [-7.0963e-07,  1.3818e-07,  7.5716e-07,  ..., -3.7438e-07,
              5.6683e-07, -2.1265e-07],
            [-1.7313e-06,  1.4222e-06, -2.6199e-06,  ..., -1.5281e-06,
             -1.6057e-06,  2.9270e-06]]),
    'exp_avg_sq': tensor([[4.0785e-12, 1.2035e-11, 1.1493e-11,  ..., 2.8503e-12, 5.3063e-12,

In [26]:
checkpoint_tac_gia.keys()

dict_keys(['config', 'epoch', 'cur_step', 'best_valid_score', 'state_dict', 'optimizer'])

In [31]:
checkpoint_tac_gia["epoch"]

237

In [25]:
set(checkpoint.keys()) - set(checkpoint_tac_gia.keys())

{'best_test_upon_valid',
 'best_valid_result',
 'model_state_dict',
 'optimizer_state_dict',
 'scheduler_state_dict'}

In [22]:
checkpoint_tac_gia["optimizer"]

{'state': {0: {'step': 25466,
   'exp_avg': tensor([[-6.8882e-07, -1.2241e-06,  2.8265e-06,  ..., -2.4468e-07,
             2.9447e-06,  1.4239e-06],
           [-3.3804e-06,  1.4585e-06,  6.0607e-07,  ...,  1.7338e-06,
             1.6452e-06, -5.8073e-07],
           [ 1.3612e-07,  3.9212e-07, -3.0821e-07,  ..., -1.5826e-06,
             8.2550e-07, -2.9203e-09],
           ...,
           [-1.2538e-07,  3.0764e-07,  4.3960e-07,  ...,  3.4618e-07,
             4.4492e-07, -4.1024e-07],
           [ 4.2428e-07,  4.2641e-07,  9.4519e-08,  ..., -5.1350e-07,
            -1.1095e-07, -2.8555e-08],
           [-5.7176e-07, -4.7089e-07,  3.6439e-07,  ...,  1.6590e-07,
            -3.1449e-07, -9.9818e-07]]),
   'exp_avg_sq': tensor([[2.4350e-11, 3.8118e-11, 4.0473e-11,  ..., 5.3999e-11, 2.4134e-11,
            4.1539e-11],
           [1.2830e-10, 7.1565e-11, 1.1640e-10,  ..., 9.3058e-11, 1.1748e-10,
            6.2279e-11],
           [1.1436e-10, 8.6529e-11, 9.3927e-11,  ..., 1.0502e-10, 1.3093e-10,
            1.0909e-10],
           ...,
           [4.1110e-11, 3.1298e-11, 4.8042e-11,  ..., 2.7429e-11, 4.8199e-11,
            4.6144e-11],
           [1.0923e-11, 1.9817e-11, 1.0303e-11,  ..., 1.1908e-11, 1.2553e-11,
            2.9496e-11],
           [1.8666e-11, 1.5134e-11, 1.3236e-11,  ..., 1.5648e-11, 1.5505e-11,
            1.6881e-11]])},
  1: {'step': 25466,
   'exp_avg': tensor([[-1.7944e-06,  4.2537e-06,  9.6247e-06,  ..., -2.8216e-06,
            -4.4882e-07, -9.8047e-06],
           [ 1.6023e-06,  5.6850e-07,  5.2786e-07,  ..., -1.8350e-06,
            -1.4585e-06,  1.2608e-06],
           [ 3.8986e-08, -5.6923e-09,  2.2339e-07,  ..., -1.3081e-07,
            -1.7680e-07,  1.7956e-07],
           ...,
           [-1.6285e-06, -4.7656e-07, -9.5756e-08,  ...,  1.7464e-06,
             1.0213e-06, -3.9722e-06],
           [-1.7458e-06,  1.3963e-06,  1.0821e-06,  ...,  5.6512e-07,
             1.4612e-06, -1.2368e-06],
           [ 2.6149e-06, -6.1973e-06,  3.1629e-06,  ...,  9.4115e-07,
            -1.3167e-06, -6.4031e-07]]),
   'exp_avg_sq': tensor([[3.7424e-11, 5.7044e-11, 4.2935e-11,  ..., 3.8069e-11, 5.9506e-11,
            5.3896e-11],
           [6.4286e-11, 7.9898e-11, 9.9533e-11,  ..., 1.0057e-10, 9.3030e-11,
            7.6151e-11],
           [6.4704e-11, 5.1684e-11, 3.3996e-11,  ..., 4.9504e-11, 5.4908e-11,
            4.9496e-11],
           ...,
           [4.3515e-11, 7.7462e-11, 5.3293e-11,  ..., 5.0491e-11, 6.8379e-11,
            9.1987e-11],
           [7.3121e-11, 7.8377e-11, 6.6156e-11,  ..., 4.2328e-11, 6.5155e-11,
            8.0113e-11],
           [1.4804e-10, 2.0677e-10, 1.2232e-10,  ..., 1.3477e-10, 1.6226e-10,
            2.0551e-10]])},
  2: {'step': 25466,
   'exp_avg': tensor([[ 3.1745e-05,  2.1286e-04,  2.7400e-04,  ...,  5.3471e-05,
            -4.9711e-05, -1.4807e-04],
           [-4.5539e-05, -3.7175e-05,  4.8313e-05,  ...,  3.0555e-04,
            -2.6003e-05,  1.5438e-04],
           [ 1.8004e-04, -1.8557e-04,  9.2253e-05,  ..., -6.2662e-04,
            -1.5712e-04,  5.0491e-04],
           ...,
           [ 1.0551e-04, -3.3530e-04, -3.3887e-05,  ..., -4.3571e-04,
             1.4166e-04,  4.7197e-04],
           [-1.5432e-04, -1.8377e-05, -4.6743e-04,  ..., -4.4243e-05,
             3.6597e-04, -2.6414e-04],
           [-1.5739e-04, -1.1826e-05,  2.2381e-04,  ..., -4.8946e-05,
             3.1290e-04,  3.4759e-04]]),
   'exp_avg_sq': tensor([[2.0710e-06, 1.0396e-06, 8.2512e-07,  ..., 9.4493e-07, 8.6556e-07,
            8.7723e-07],
           [1.0391e-06, 2.2131e-06, 7.9275e-07,  ..., 1.1872e-06, 9.3343e-07,
            8.9332e-07],
           [9.3602e-07, 8.5710e-07, 1.8251e-06,  ..., 8.7148e-07, 7.7940e-07,
            8.8171e-07],
           ...,
           [1.1167e-06, 1.3906e-06, 1.0431e-06,  ..., 2.3585e-06, 9.9765e-07,
            1.0929e-06],
           [8.6108e-07, 9.1258e-07, 7.5808e-07,  ..., 8.6397e-07, 1.7453e-06,
            8.2543e-07],
           [1.0133e-06, 9.4192e-07, 8.9940e-07,  ..., 9.5842e-07, 9.3956e-07,
            2.0630e-06]])},
  3: {'step': 25466,
   'exp_avg': tensor([ 5.7573e-05,  5.1172e-04,  1.1658e-03,  6.1219e-04,  5.9063e-04,
            5.0534e-04, -4.3469e-04,  8.2431e-04, -1.7169e-04,  4.8339e-04,
           -1.7830e-04, -2.4881e-04,  4.0731e-04,  6.9726e-05,  1.6270e-03,
            7.8834e-04,  3.4018e-04,  3.0592e-04, -2.4590e-05, -4.6947e-04,
           -4.8241e-04, -8.3476e-04,  3.2338e-04, -3.8594e-04,  5.8963e-04,
           -6.4308e-04, -3.5524e-04, -6.3260e-04, -8.7888e-04,  6.9460e-04,
            2.6742e-04, -2.1074e-04, -2.4516e-04, -8.5108e-05, -2.7057e-04,
           -9.0349e-04, -6.0197e-04, -1.2212e-03, -7.0757e-04, -1.6043e-04,
            4.4824e-04, -2.1388e-04,  5.4602e-04, -8.4051e-04,  5.6832e-04,
           -7.5425e-04,  7.1439e-05,  2.6860e-04, -1.3378e-04, -2.3059e-04,
            7.5780e-05,  1.3787e-04, -3.9868e-04,  8.5162e-04, -7.5851e-04,
           -3.3129e-04,  8.1340e-05, -2.5241e-05,  1.1226e-03,  6.9721e-04,
            7.4918e-04,  1.0388e-03,  1.6886e-04,  1.9916e-04]),
   'exp_avg_sq': tensor([5.2894e-06, 5.7098e-06, 4.7016e-06, 5.1283e-06, 5.6755e-06, 5.1779e-06,
           4.7099e-06, 5.4932e-06, 5.2269e-06, 5.2821e-06, 4.6742e-06, 5.4992e-06,
           5.6513e-06, 7.9896e-06, 5.8315e-06, 5.6618e-06, 5.3710e-06, 4.9015e-06,
           4.3590e-06, 6.4448e-06, 5.8409e-06, 4.8098e-06, 5.3077e-06, 7.2195e-06,
           4.1373e-06, 5.5414e-06, 4.4163e-06, 5.5214e-06, 7.0238e-06, 5.7006e-06,
           5.8404e-06, 5.0275e-06, 5.1220e-06, 7.8614e-06, 6.1662e-06, 6.6653e-06,
           5.7279e-06, 4.8403e-06, 6.0310e-06, 6.2543e-06, 5.2401e-06, 5.1362e-06,
           5.1012e-06, 5.5715e-06, 5.5610e-06, 4.7760e-06, 5.1593e-06, 5.6838e-06,
           6.2105e-06, 5.3372e-06, 6.7097e-06, 4.5811e-06, 5.9714e-06, 5.4714e-06,
           5.8526e-06, 4.5993e-06, 5.0860e-06, 6.2164e-06, 6.0440e-06, 6.6191e-06,
           5.1486e-06, 6.8201e-06, 4.5797e-06, 5.2812e-06])},
  4: {'step': 25466,
   'exp_avg': tensor([[-6.4196e-08, -6.7959e-08, -1.4142e-07,  ...,  8.1632e-08,
            -3.2467e-08,  3.3017e-08],
           [-1.2667e-07,  5.9611e-08,  1.6313e-08,  ...,  2.3607e-08,
             4.1834e-08, -3.0052e-08],
           [-1.8714e-09, -1.2262e-09, -9.0745e-12,  ...,  1.3914e-09,
            -1.7562e-10, -9.7912e-10],
           ...,
           [-9.6106e-08, -2.4146e-10,  2.0119e-08,  ...,  3.2335e-08,
            -3.6385e-08, -3.2627e-08],
           [-3.4475e-08, -1.9314e-08,  7.9438e-09,  ..., -2.3370e-08,
            -1.2744e-08, -5.8714e-09],
           [-1.9435e-09, -2.9608e-08,  1.0325e-07,  ...,  4.9532e-08,
             4.5195e-08, -5.1564e-08]]),
   'exp_avg_sq': tensor([[9.1681e-14, 1.7692e-14, 1.6092e-14,  ..., 2.1214e-14, 1.3488e-14,
            1.2437e-14],
           [2.0378e-13, 2.9372e-14, 2.6900e-14,  ..., 5.4150e-14, 1.9889e-14,
            2.5900e-14],
           [1.4765e-13, 1.6125e-14, 1.9809e-14,  ..., 2.4215e-14, 1.1484e-14,
            1.5906e-14],
           ...,
           [7.8217e-14, 1.0915e-14, 1.1629e-14,  ..., 2.1564e-14, 1.8463e-14,
            1.4174e-14],
           [9.6789e-14, 1.7663e-14, 2.2071e-14,  ..., 2.5303e-14, 2.1354e-14,
            1.7520e-14],
           [2.2324e-13, 6.4006e-14, 5.9078e-14,  ..., 6.8946e-14, 4.9475e-14,
            6.0563e-14]])},
  5: {'step': 25466,
   'exp_avg': tensor([[-4.4805e-06, -1.3523e-05,  1.4421e-07,  ..., -1.3396e-05,
            -1.2260e-05, -4.1537e-05],
           [ 4.2038e-06, -3.8751e-06, -1.8659e-05,  ...,  8.6050e-08,
             1.3881e-05,  4.0396e-08],
           [ 1.7183e-06,  8.6666e-06, -1.4694e-05,  ..., -3.0782e-06,
             2.5251e-05,  6.6523e-06],
           ...,
           [ 6.0799e-06,  5.8322e-06, -1.9335e-06,  ..., -1.5012e-05,
             2.1915e-05, -8.3021e-06],
           [ 4.0429e-07,  9.2324e-06,  1.1769e-05,  ...,  1.6008e-05,
             1.0158e-05,  1.9762e-05],
           [ 4.8644e-06,  3.5918e-06,  7.9067e-06,  ...,  1.9133e-05,
             1.4555e-05,  3.0552e-05]]),
   'exp_avg_sq': tensor([[3.3489e-10, 2.2542e-09, 3.6849e-09,  ..., 2.3803e-09, 3.5110e-09,
            2.9907e-09],
           [3.5780e-10, 2.4704e-09, 4.0839e-09,  ..., 3.0578e-09, 3.9467e-09,
            3.4108e-09],
           [3.0837e-10, 2.0310e-09, 3.3853e-09,  ..., 2.4774e-09, 3.4659e-09,
            2.9203e-09],
           ...,
           [3.3469e-10, 2.2227e-09, 4.0891e-09,  ..., 2.6758e-09, 4.0224e-09,
            3.2085e-09],
           [3.1625e-10, 2.3592e-09, 3.3517e-09,  ..., 2.9335e-09, 3.4412e-09,
            3.1047e-09],
           [3.2904e-10, 2.5029e-09, 3.7007e-09,  ..., 2.8637e-09, 3.7237e-09,
            3.5322e-09]])},
  6: {'step': 25466,
   'exp_avg': tensor([-1.6904e-05, -3.1698e-07,  8.4752e-06, -4.5345e-06,  4.7824e-06,
            8.0076e-06, -2.9926e-06, -1.1366e-06,  6.8291e-07, -5.8913e-06,
           -1.1483e-05, -1.7683e-07, -9.5143e-06,  6.5537e-06, -2.6186e-06,
            8.2392e-06,  2.0685e-06,  1.2162e-05,  5.3730e-06, -4.5670e-07,
           -5.8902e-06, -2.5093e-06,  5.0774e-06,  1.7203e-05,  8.4152e-06,
            6.3144e-06, -4.0568e-06,  5.0088e-06,  4.8998e-07,  7.5156e-06,
           -8.0159e-06, -2.9799e-06,  2.3812e-06,  1.2080e-05,  1.0586e-05,
            4.2158e-06, -1.1316e-05, -1.0368e-05, -1.3832e-05,  3.0492e-06,
            6.9317e-06,  1.1496e-05,  2.7199e-06, -1.7022e-05,  9.3297e-06,
           -7.9600e-06,  2.8116e-06,  8.9941e-06, -1.2423e-05,  8.5282e-06,
            1.9819e-05,  1.9853e-06, -3.6456e-06,  2.4752e-06,  1.2339e-05,
            9.7104e-06,  1.4634e-05,  2.5684e-06, -2.3393e-06,  9.5076e-07,
           -2.2450e-06,  1.2940e-05,  6.1885e-06,  8.3815e-06]),
   'exp_avg_sq': tensor([1.6587e-09, 1.9710e-09, 1.5690e-09, 1.6951e-09, 1.8896e-09, 1.8543e-09,
           1.6779e-09, 2.0023e-09, 1.7436e-09, 1.6818e-09, 1.6071e-09, 1.6499e-09,
           2.0328e-09, 2.3735e-09, 1.8858e-09, 1.7886e-09, 1.8566e-09, 1.9085e-09,
           1.9123e-09, 2.2000e-09, 1.9680e-09, 2.0035e-09, 1.8411e-09, 2.2349e-09,
           1.3855e-09, 1.5939e-09, 1.9375e-09, 1.7109e-09, 2.0175e-09, 1.8864e-09,
           1.9443e-09, 1.5167e-09, 1.8077e-09, 2.2352e-09, 1.9312e-09, 2.0800e-09,
           2.0512e-09, 1.6168e-09, 1.9725e-09, 1.8994e-09, 1.9844e-09, 1.6881e-09,
           1.6608e-09, 1.9152e-09, 1.9093e-09, 1.9228e-09, 1.8183e-09, 2.0153e-09,
           2.0640e-09, 1.9096e-09, 2.1743e-09, 1.5625e-09, 1.6271e-09, 1.8189e-09,
           1.8050e-09, 1.6867e-09, 1.8109e-09, 1.8376e-09, 1.8315e-09, 2.1059e-09,
           1.7758e-09, 1.8394e-09, 1.7332e-09, 1.9006e-09])},
  7: {'step': 25466,
   'exp_avg': tensor([[ 7.5063e-07, -1.3477e-06,  4.7240e-06,  ...,  1.1682e-06,
            -2.3180e-06,  1.1009e-06],
           [ 1.4154e-06, -6.3627e-07,  6.4246e-07,  ...,  6.5502e-07,
             1.5029e-06,  2.0598e-07],
           [ 1.5244e-08, -1.7817e-08, -2.2984e-08,  ..., -2.6278e-08,
            -4.9057e-08,  4.8047e-08],
           ...,
           [ 1.1579e-06,  1.4518e-08,  2.3195e-07,  ...,  4.3085e-07,
             1.8191e-07,  1.1377e-06],
           [-7.0963e-07,  1.3818e-07,  7.5716e-07,  ..., -3.7438e-07,
             5.6683e-07, -2.1265e-07],
           [-1.7313e-06,  1.4222e-06, -2.6199e-06,  ..., -1.5281e-06,
            -1.6057e-06,  2.9270e-06]]),
   'exp_avg_sq': tensor([[4.0785e-12, 1.2035e-11, 1.1493e-11,  ..., 2.8503e-12, 5.3063e-12,
            1.0714e-11],
           [1.8104e-11, 2.2264e-11, 2.7794e-11,  ..., 6.5999e-12, 2.0570e-11,
            1.7373e-11],
           [9.0008e-12, 9.2000e-12, 9.0662e-12,  ..., 5.3652e-12, 8.5443e-12,
            1.2159e-11],
           ...,
           [1.4733e-11, 7.0997e-12, 8.5134e-12,  ..., 4.6733e-12, 5.8736e-12,
            1.3243e-11],
           [1.6742e-11, 1.3061e-11, 1.6735e-11,  ..., 7.3535e-12, 1.2579e-11,
            1.4169e-11],
           [3.9438e-11, 3.7423e-11, 5.5736e-11,  ..., 2.2195e-11, 4.1214e-11,
            7.9336e-11]])},
  8: {'step': 25466,
   'exp_avg': tensor([[ 8.0969e-06, -1.3985e-06, -2.5085e-06,  ...,  1.8846e-06,
             3.1530e-05, -6.7437e-06],
           [ 2.4618e-06, -9.0392e-06,  1.9518e-05,  ..., -3.2660e-05,
             4.6980e-06, -1.0362e-05],
           [-1.9275e-05,  2.3776e-05, -1.7476e-05,  ..., -1.5958e-05,
            -2.3204e-05,  1.1114e-05],
           ...,
           [ 7.8149e-06,  8.8683e-06, -1.3656e-05,  ..., -3.1827e-06,
             3.0163e-05, -1.5388e-05],
           [ 6.3914e-06, -3.4619e-05,  1.9352e-07,  ..., -6.5595e-06,
             3.7439e-05,  1.2402e-05],
           [ 1.2916e-06,  1.8724e-05,  1.7153e-05,  ...,  2.4193e-05,
             4.9866e-06, -2.1155e-05]]),
   'exp_avg_sq': tensor([[9.4257e-09, 7.8750e-09, 7.3050e-09,  ..., 8.1303e-09, 7.9188e-09,
            7.3630e-09],
           [1.0003e-08, 7.7839e-09, 7.6340e-09,  ..., 8.5972e-09, 8.6655e-09,
            7.4178e-09],
           [8.2455e-09, 6.8552e-09, 6.8907e-09,  ..., 8.0010e-09, 7.2022e-09,
            6.6475e-09],
           ...,
           [9.1302e-09, 8.0431e-09, 7.5690e-09,  ..., 8.3222e-09, 8.3623e-09,
            7.2394e-09],
           [8.6683e-09, 6.9810e-09, 7.0375e-09,  ..., 8.0138e-09, 7.8264e-09,
            7.4413e-09],
           [9.3849e-09, 8.4407e-09, 7.7714e-09,  ..., 9.0677e-09, 7.9307e-09,
            7.3686e-09]])},
  9: {'step': 25466,
   'exp_avg': tensor([-7.3871e-05,  3.8103e-07,  2.0341e-04,  2.2810e-05,  2.0242e-04,
            7.9679e-05, -1.5696e-04,  1.8485e-04, -7.0328e-05,  3.3503e-05,
            2.1037e-05,  5.5324e-05,  1.6142e-04, -7.0524e-05, -1.7173e-04,
            8.2912e-05,  1.6653e-04,  1.0558e-04, -1.3587e-05,  1.2649e-04,
           -1.6522e-04,  7.0196e-06,  1.5928e-04,  5.6695e-05,  2.3587e-04,
           -1.7322e-04, -1.0492e-04, -2.0630e-04, -2.9293e-04,  5.2957e-05,
           -1.1783e-04, -5.3412e-05,  1.0269e-04,  1.5372e-04, -2.7793e-04,
           -7.9384e-06, -1.0711e-04, -3.0927e-04, -2.7489e-05,  1.0277e-04,
            1.3660e-04, -5.1566e-05, -2.4361e-06, -8.8249e-05,  2.2841e-04,
           -7.9703e-05,  1.0628e-04,  1.4959e-04, -2.1790e-04,  2.1226e-04,
            6.6061e-05,  6.5672e-05, -1.4631e-05,  1.6661e-04, -2.5734e-04,
           -7.6961e-05,  2.9712e-04, -6.0308e-05, -1.0585e-04,  4.2826e-06,
            8.0694e-05,  2.3090e-04, -4.3736e-05,  5.3923e-05]),
   'exp_avg_sq': tensor([3.0449e-07, 3.2374e-07, 2.9130e-07, 3.1949e-07, 3.3169e-07, 3.1136e-07,
           2.8511e-07, 3.6898e-07, 3.5378e-07, 3.2185e-07, 3.0053e-07, 2.9965e-07,
           3.3356e-07, 4.3706e-07, 3.5051e-07, 3.4293e-07, 3.3610e-07, 3.1968e-07,
           3.1454e-07, 3.6321e-07, 3.3341e-07, 3.3674e-07, 3.2058e-07, 4.0516e-07,
           2.4928e-07, 2.8505e-07, 3.2372e-07, 2.9810e-07, 3.7924e-07, 3.4380e-07,
           3.4038e-07, 2.8221e-07, 3.3684e-07, 3.5801e-07, 2.9109e-07, 3.9872e-07,
           3.4975e-07, 2.9196e-07, 3.4863e-07, 2.9795e-07, 3.4023e-07, 3.0696e-07,
           2.9179e-07, 3.2708e-07, 3.4521e-07, 3.1891e-07, 3.0054e-07, 3.5085e-07,
           3.5580e-07, 3.3232e-07, 3.7830e-07, 2.9265e-07, 2.8473e-07, 3.1268e-07,
           3.2032e-07, 3.0039e-07, 3.1832e-07, 3.4284e-07, 3.2943e-07, 3.7509e-07,
           3.2568e-07, 3.3035e-07, 2.9134e-07, 3.3477e-07])}},
 'param_groups': [{'lr': 0.001,
   'betas': (0.9, 0.999),
   'eps': 1e-08,
   'weight_decay': 0,
   'amsgrad': False,
   'maximize': False,
   'initial_lr': 0.001,
   'params': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}]}

In [23]:
checkpoint_tac_gia["cur_step"]

0

In [27]:
checkpoint["optimizer_state_dict"]

{'state': {0: {'step': tensor(107.),
   'exp_avg': tensor([[[-2.7719e-10,  0.0000e+00],
            [-5.6067e-11,  1.8220e-09],
            [ 2.6489e-09,  1.2190e-09],
            [ 7.4208e-10,  1.4702e-10],
            [-9.2638e-10, -1.1515e-09],
            [ 2.9451e-10,  1.1827e-11],
            [ 3.3442e-10,  7.4270e-10],
            [ 1.3193e-10,  4.0197e-09],
            [-2.0278e-09, -1.1741e-09],
            [ 3.6137e-09, -7.6694e-10],
            [-1.6399e-09, -7.4172e-10],
            [ 4.4916e-10,  1.9305e-09],
            [ 1.7786e-10,  1.5803e-10],
            [-1.7657e-10,  3.4630e-10],
            [-2.8825e-10, -9.1156e-10],
            [ 1.7928e-09,  9.9423e-10],
            [ 2.6300e-09, -1.9239e-09],
            [-7.1809e-10, -1.2952e-10],
            [ 1.5179e-09,  1.7493e-10],
            [ 2.6992e-09,  1.9394e-11],
            [ 1.2887e-09,  3.8907e-10],
            [ 2.3594e-10, -3.2283e-10],
            [-2.2606e-09, -4.6463e-10],
            [-1.0048e-11, -3.3749e-10],
            [ 9.9333e-10,  3.1815e-10],
            [ 2.0547e-10,  5.0789e-10],
            [ 5.7656e-11,  6.4817e-10],
            [ 3.7713e-10,  1.8938e-10],
            [ 1.8490e-09, -5.5351e-10],
            [ 7.0039e-10,  7.1383e-10],
            [ 4.1894e-10, -6.6805e-10],
            [ 4.8272e-10, -2.7449e-10],
            [-9.2433e-11,  0.0000e+00]]]),
   'exp_avg_sq': tensor([[[1.2184e-16, 0.0000e+00],
            [3.8423e-14, 4.1205e-14],
            [2.7667e-14, 6.0460e-15],
            [5.6237e-15, 1.1333e-14],
            [9.0722e-15, 1.9940e-14],
            [1.0410e-14, 5.6005e-14],
            [8.4260e-14, 2.7802e-14],
            [2.7394e-14, 6.5976e-14],
            [2.5937e-14, 2.0899e-14],
            [5.1345e-14, 3.3195e-14],
            [4.9238e-14, 1.7064e-13],
            [5.7885e-15, 9.8442e-15],
            [1.4986e-14, 1.8703e-15],
            [4.9402e-15, 1.5643e-15],
            [1.0256e-15, 2.9308e-15],
            [8.5547e-15, 7.5772e-15],
            [8.6845e-14, 3.5427e-13],
            [9.6549e-15, 1.4149e-14],
            [3.8370e-15, 3.1259e-15],
            [2.0356e-14, 7.3944e-15],
            [8.3340e-15, 1.4409e-14],
            [5.3910e-14, 3.8003e-15],
            [1.0528e-13, 1.1104e-14],
            [4.6726e-15, 6.9474e-15],
            [8.2025e-15, 4.4559e-14],
            [1.6990e-15, 1.3470e-15],
            [2.0783e-15, 2.9203e-15],
            [1.6794e-15, 4.4315e-16],
            [1.3224e-14, 4.3573e-14],
            [9.0476e-15, 4.9675e-15],
            [6.0096e-15, 6.3654e-15],
            [7.2905e-16, 1.6750e-15],
            [1.5106e-15, 0.0000e+00]]])},
  1: {'step': tensor(107.),
   'exp_avg': tensor([[[-4.6948e-10,  0.0000e+00],
            [-6.4960e-10, -1.4964e-10],
            [-1.7746e-10,  7.1236e-10],
            [ 1.9733e-09,  1.5168e-10],
            [ 1.1015e-09,  4.8760e-09],
            [ 1.2363e-09, -1.5725e-10],
            [-5.5240e-09,  1.9055e-08],
            [ 1.9895e-09,  1.8451e-10],
            [ 1.1772e-09, -8.1691e-10],
            [ 1.1486e-09,  1.7645e-09],
            [ 4.7148e-11, -2.9168e-10],
            [ 6.5882e-11, -1.5410e-10],
            [ 6.2219e-11,  1.8029e-09],
            [ 4.2536e-10, -8.1314e-10],
            [-1.1135e-09, -4.8857e-09],
            [ 2.9832e-09, -5.6530e-10],
            [-1.4065e-09, -1.7841e-09],
            [-3.3559e-10,  2.5718e-09],
            [-3.6604e-09,  6.2246e-09],
            [ 3.4555e-09, -6.7304e-10],
            [-2.8239e-11,  1.8185e-09],
            [ 2.8630e-10, -5.3654e-09],
            [ 9.3569e-09, -7.5094e-10],
            [-2.9077e-09, -3.8844e-10],
            [-1.1270e-09, -8.9006e-10],
            [-3.8585e-09, -1.1061e-08],
            [-5.4530e-10,  8.7824e-10],
            [ 6.0445e-10, -1.8995e-09],
            [-1.4469e-09,  1.0546e-09],
            [ 6.4267e-11, -1.3543e-09],
            [-1.7029e-10,  2.2277e-10],
            [ 1.0915e-09,  2.6082e-10],
            [-5.2568e-10,  0.0000e+00]]]),
   'exp_avg_sq': tensor([[[1.2532e-18, 0.0000e+00],
            [1.1812e-17, 6.0027e-18],
            [2.9151e-18, 2.9969e-18],
            [8.8032e-17, 7.0437e-17],
            [2.9058e-17, 2.3593e-16],
            [3.2848e-18, 3.4632e-18],
            [5.1259e-17, 7.2625e-16],
            [1.4485e-17, 6.2039e-18],
            [1.0687e-17, 7.6952e-18],
            [9.5457e-17, 2.1878e-17],
            [1.0350e-17, 9.7024e-18],
            [9.0633e-18, 1.2949e-17],
            [1.4652e-17, 4.0333e-17],
            [8.1565e-18, 2.4675e-17],
            [4.1832e-17, 1.3612e-16],
            [1.2759e-16, 1.3414e-17],
            [1.0306e-17, 1.1747e-17],
            [3.6078e-17, 2.0367e-17],
            [3.3323e-17, 4.3223e-17],
            [1.1819e-17, 1.0108e-17],
            [2.5394e-18, 3.9498e-18],
            [4.1995e-17, 1.1394e-16],
            [7.5159e-17, 1.9290e-17],
            [1.2695e-17, 4.2795e-18],
            [2.4933e-17, 3.5905e-17],
            [1.8274e-16, 4.4756e-16],
            [1.9754e-17, 1.3163e-17],
            [1.3081e-17, 1.0912e-17],
            [8.8246e-18, 9.5017e-18],
            [3.0088e-18, 3.5559e-18],
            [3.1795e-17, 7.8586e-18],
            [2.5745e-17, 4.3797e-18],
            [1.5320e-18, 0.0000e+00]]])},
  2: {'step': tensor(107.),
   'exp_avg': tensor([[[ 6.3075e-08,  0.0000e+00],
            [ 1.8224e-06, -8.8163e-07],
            [-2.4929e-07,  1.1274e-06],
            [ 1.2733e-07, -3.6972e-07],
            [ 6.0442e-07,  1.8953e-06],
            [ 6.2331e-07, -2.0891e-06],
            [ 6.2330e-07, -8.8972e-07],
            [ 1.2358e-06, -4.1506e-07],
            [-6.1288e-07, -4.2939e-07],
            [-4.5913e-08, -8.9164e-07],
            [-8.5528e-07,  5.9480e-07],
            [ 6.6536e-08,  8.9798e-07],
            [-2.7650e-07,  2.0625e-07],
            [ 2.7491e-07, -2.8672e-07],
            [-5.2285e-08,  1.5519e-07],
            [-2.5759e-07, -2.1447e-07],
            [ 5.0806e-06,  1.0108e-06],
            [ 6.6157e-07,  1.5996e-06],
            [ 8.3633e-07,  2.6951e-07],
            [-7.0574e-07, -1.7581e-06],
            [ 1.3251e-06, -1.0601e-06],
            [-5.2806e-07,  1.9130e-06],
            [ 4.3884e-07,  9.4035e-07],
            [-9.9876e-07,  4.5337e-07],
            [ 2.2153e-06, -1.6554e-06],
            [ 4.2447e-07, -2.2682e-07],
            [-2.0806e-07,  7.5601e-07],
            [-9.3537e-07, -4.1709e-07],
            [ 6.5641e-07,  8.0237e-07],
            [ 1.1440e-06,  5.8025e-07],
            [ 4.4013e-07,  8.5015e-07],
            [-3.4876e-07, -3.2840e-07],
            [ 2.0014e-07,  0.0000e+00]]]),
   'exp_avg_sq': tensor([[[9.6498e-15, 0.0000e+00],
            [1.3411e-12, 1.3940e-12],
            [1.0628e-12, 1.3019e-12],
            [1.6028e-13, 1.6164e-13],
            [1.2125e-11, 1.0625e-11],
            [1.7456e-12, 1.9353e-12],
            [2.5441e-11, 2.0704e-11],
            [3.6549e-12, 3.9050e-12],
            [2.0518e-12, 1.9098e-12],
            [1.4110e-12, 1.9476e-12],
            [6.3815e-12, 3.2775e-12],
            [3.4780e-13, 3.9383e-13],
            [1.3642e-12, 1.2966e-12],
            [9.2967e-13, 1.0336e-12],
            [8.4998e-13, 7.7362e-13],
            [4.0901e-12, 4.2805e-12],
            [6.7236e-12, 7.9253e-12],
            [1.9271e-12, 1.4061e-12],
            [7.3099e-13, 8.9405e-13],
            [3.1062e-12, 2.6872e-12],
            [8.6193e-13, 1.1313e-12],
            [4.7502e-12, 4.9911e-12],
            [6.4101e-12, 1.2597e-11],
            [2.3729e-13, 1.7602e-13],
            [2.4114e-12, 1.8650e-12],
            [7.8720e-13, 5.3777e-13],
            [1.2885e-13, 1.5661e-13],
            [5.7474e-13, 7.6559e-13],
            [1.2278e-12, 1.4603e-12],
            [5.8671e-13, 8.0450e-13],
            [2.6562e-13, 2.6982e-13],
            [4.5383e-13, 4.7997e-13],
            [4.8958e-14, 0.0000e+00]]])},
  3: {'step': tensor(107.),
   'exp_avg': tensor([[ 2.3103e-07,  1.0403e-06,  1.0029e-06,  ..., -7.0030e-07,
             4.6831e-07, -1.1734e-06],
           [ 7.8599e-07,  8.9144e-07,  1.1131e-06,  ..., -1.2175e-06,
             1.4770e-06, -2.0762e-06],
           [-7.2400e-06,  3.6737e-06,  1.0233e-06,  ...,  3.5602e-06,
            -1.0677e-06, -1.6995e-06],
           ...,
           [-1.0701e-07, -4.5697e-07,  1.3214e-07,  ..., -1.7934e-09,
            -1.4198e-08,  8.5027e-08],
           [-8.1090e-07,  1.0155e-06, -2.1203e-07,  ...,  1.0897e-06,
            -1.7710e-06,  9.4949e-07],
           [-8.6344e-07,  1.4118e-06,  1.1115e-06,  ..., -2.3058e-07,
            -3.0770e-06, -8.9351e-07]]),
   'exp_avg_sq': tensor([[1.7197e-11, 4.3158e-12, 1.3057e-11,  ..., 1.3532e-12, 5.3847e-12,
            6.7925e-12],
           [5.2045e-12, 3.2792e-11, 5.7461e-12,  ..., 3.1862e-11, 1.2032e-11,
            4.4428e-11],
           [1.1614e-10, 1.4902e-11, 5.9542e-11,  ..., 1.1677e-11, 1.5158e-11,
            1.0272e-11],
           ...,
           [1.0355e-11, 2.6694e-11, 1.6898e-11,  ..., 3.6301e-11, 2.8416e-11,
            4.0036e-12],
           [3.7530e-12, 8.8813e-12, 1.0321e-12,  ..., 2.0108e-11, 2.3516e-11,
            1.2045e-12],
           [3.6880e-12, 5.7514e-12, 1.7696e-12,  ..., 3.7483e-12, 1.2709e-11,
            4.0899e-12]])},
  4: {'step': tensor(107.),
   'exp_avg': tensor([[-3.2790e-06,  3.5892e-06,  6.1601e-06,  ..., -4.2335e-06,
             2.8478e-06, -3.8660e-06],
           [-5.9200e-07,  1.6992e-07, -7.5403e-08,  ..., -9.9569e-07,
            -6.1853e-07,  1.2011e-06],
           [ 1.4073e-06, -2.8389e-07, -2.9425e-06,  ..., -1.6044e-07,
             1.2838e-06,  2.7855e-07],
           ...,
           [ 1.1421e-06,  4.1604e-07, -7.1967e-07,  ...,  1.4597e-06,
            -1.8978e-06, -9.6547e-07],
           [ 8.8306e-08, -1.1122e-06,  7.3494e-07,  ..., -9.2274e-07,
             1.2415e-06,  2.1117e-06],
           [-5.3142e-07,  2.6830e-07,  1.3902e-06,  ..., -5.9903e-07,
             2.8715e-07,  2.1961e-06]]),
   'exp_avg_sq': tensor([[9.3147e-11, 4.3510e-11, 6.8832e-11,  ..., 7.1716e-11, 8.4444e-11,
            4.0102e-11],
           [1.1656e-11, 1.8192e-11, 9.4590e-12,  ..., 9.8492e-12, 7.6601e-12,
            1.4637e-11],
           [4.0969e-11, 2.9594e-11, 1.5447e-11,  ..., 2.2950e-11, 5.6575e-11,
            2.0915e-11],
           ...,
           [2.4973e-11, 1.3463e-11, 1.0682e-11,  ..., 1.7052e-11, 1.1617e-11,
            3.8667e-11],
           [2.4430e-11, 3.0451e-11, 6.2245e-11,  ..., 4.7332e-11, 3.2696e-11,
            7.1942e-11],
           [5.1186e-11, 4.9557e-11, 5.7231e-11,  ..., 7.5150e-11, 6.9091e-11,
            4.7706e-11]])},
  5: {'step': tensor(107.),
   'exp_avg': tensor([[-4.1142e-11, -6.9265e-12, -1.0296e-10,  ..., -1.2190e-10,
            -6.1960e-11, -3.0249e-10],
           [ 4.4147e-11,  7.4893e-11,  4.7313e-11,  ...,  2.5135e-11,
             1.2180e-10,  3.6847e-11],
           [ 4.0600e-13, -3.3289e-11,  1.2606e-11,  ...,  4.3187e-11,
             4.6841e-11, -1.3687e-11],
           ...,
           [ 4.6705e-11, -1.6781e-11, -3.8858e-11,  ...,  1.3448e-11,
            -3.5547e-11,  1.8744e-11],
           [-3.1252e-11,  4.3123e-11,  2.6281e-11,  ...,  4.5587e-11,
             9.7780e-12, -4.9567e-11],
           [-3.6599e-11, -5.0538e-11, -1.1584e-11,  ...,  3.0267e-11,
            -9.9358e-11, -2.1368e-12]]),
   'exp_avg_sq': tensor([[9.8919e-21, 1.6000e-20, 1.4706e-20,  ..., 3.6664e-20, 3.3279e-20,
            4.5939e-20],
           [1.1065e-20, 2.0551e-20, 5.6059e-21,  ..., 4.6411e-21, 3.2692e-20,
            9.8178e-21],
           [8.1263e-21, 1.0041e-20, 7.7765e-21,  ..., 5.5959e-21, 8.9059e-21,
            1.4911e-20],
           ...,
           [2.5185e-21, 2.1280e-21, 3.4099e-21,  ..., 4.2923e-21, 2.2176e-21,
            7.8563e-21],
           [7.1006e-21, 1.6708e-20, 3.0455e-20,  ..., 6.8933e-21, 2.5214e-20,
            8.9567e-21],
           [2.7222e-20, 3.2484e-20, 9.0138e-21,  ..., 1.2812e-20, 1.5951e-20,
            1.8519e-20]])},
  6: {'step': tensor(107.),
   'exp_avg': tensor([[-8.9674e-08, -6.9266e-08, -5.9488e-08,  ..., -2.8837e-08,
            -4.6899e-08, -1.0715e-08],
           [-1.6369e-09,  8.3251e-10,  7.0344e-10,  ...,  1.4662e-09,
            -5.1628e-09,  5.1997e-09],
           [ 2.0285e-08, -1.1245e-08, -7.8591e-09,  ..., -3.0467e-08,
            -6.7769e-10,  1.7534e-08],
           ...,
           [ 2.2719e-08, -2.0814e-08, -5.5428e-09,  ..., -1.1602e-08,
             2.3280e-09, -1.1755e-08],
           [ 4.4363e-09,  2.1850e-08,  8.4954e-09,  ...,  3.9393e-09,
             2.4625e-08,  1.6741e-09],
           [ 1.3763e-08, -2.9740e-09, -5.4496e-09,  ..., -2.4733e-09,
             2.9837e-08, -3.3820e-09]]),
   'exp_avg_sq': tensor([[1.4643e-15, 1.5770e-15, 1.2301e-15,  ..., 4.9791e-16, 7.9421e-16,
            1.0930e-15],
           [5.6802e-17, 8.7512e-17, 2.2846e-16,  ..., 7.9437e-17, 8.9036e-17,
            2.0440e-16],
           [5.8315e-16, 6.2770e-16, 7.6865e-16,  ..., 9.9673e-16, 7.0450e-16,
            8.7696e-16],
           ...,
           [3.9313e-16, 1.4249e-16, 2.0296e-16,  ..., 2.8651e-16, 2.8166e-16,
            2.6052e-16],
           [1.1604e-15, 1.2949e-15, 9.4995e-16,  ..., 1.6015e-15, 1.0903e-15,
            9.0787e-16],
           [4.2843e-16, 6.0207e-16, 5.7551e-16,  ..., 4.0992e-16, 6.2372e-16,
            4.2868e-16]])},
  7: {'step': tensor(107.),
   'exp_avg': tensor([[ 8.4341e-08, -6.9650e-08, -7.9593e-08,  ..., -8.2987e-08,
             6.0040e-08,  1.7654e-07],
           [ 7.4244e-09,  9.9930e-09, -2.7446e-07,  ..., -1.2292e-08,
            -2.2922e-07, -7.1243e-08],
           [ 2.9948e-08,  1.2423e-07,  1.4550e-08,  ...,  1.6169e-07,
            -8.9097e-08, -1.0120e-07],
           ...,
           [-2.9717e-08, -3.6810e-08, -1.5787e-07,  ...,  1.0878e-07,
            -2.5657e-08,  1.0786e-07],
           [-3.1692e-08,  1.9716e-07,  1.4524e-07,  ...,  4.5557e-08,
             7.3947e-08, -9.0805e-08],
           [-7.3000e-08,  1.5840e-07,  8.2934e-08,  ..., -6.5527e-08,
            -3.1849e-08, -6.8548e-08]]),
   'exp_avg_sq': tensor([[1.1784e-14, 4.8375e-14, 1.3797e-13,  ..., 4.9385e-14, 1.2680e-13,
            1.1046e-13],
           [1.1028e-14, 5.2817e-14, 1.8096e-13,  ..., 7.0464e-14, 8.2367e-14,
            1.3171e-13],
           [8.7788e-15, 8.4355e-14, 1.2546e-13,  ..., 1.0878e-13, 1.1360e-13,
            1.0341e-13],
           ...,
           [9.8799e-15, 6.7000e-14, 1.8047e-13,  ..., 9.1886e-14, 1.4425e-13,
            1.3947e-13],
           [7.4534e-15, 7.6699e-14, 1.2546e-13,  ..., 6.4864e-14, 1.2061e-13,
            8.8049e-14],
           [1.1010e-14, 7.2759e-14, 1.8502e-13,  ..., 1.1354e-13, 1.0542e-13,
            1.3305e-13]])},
  8: {'step': tensor(107.),
   'exp_avg': tensor([ 1.2857e-08, -1.2108e-07,  1.0649e-07, -3.9300e-08,  1.8994e-07,
            2.4590e-08,  1.1075e-07,  1.6191e-07,  2.5934e-08,  2.2940e-08,
            2.3398e-08, -4.2506e-08,  6.6549e-08, -9.0493e-08, -3.1121e-08,
            9.4243e-09,  2.4424e-07,  8.4665e-08, -2.1431e-07, -1.0908e-07,
            1.5448e-07, -2.0842e-08, -3.9582e-08,  8.6293e-08,  1.2714e-07,
            3.9561e-08, -1.4335e-07, -1.2557e-07,  1.0439e-07, -1.9836e-08,
           -1.1768e-07,  1.3086e-08,  5.5774e-08, -4.7503e-08, -5.9465e-08,
           -2.4661e-07,  6.4036e-08, -1.3666e-08, -2.5532e-08,  4.8036e-08,
            7.4604e-08,  1.7582e-07, -1.4151e-08, -4.8223e-08,  1.5189e-07,
           -3.1554e-08,  3.9928e-08, -7.6478e-08, -1.0446e-07, -9.0172e-08,
            8.4761e-08, -5.7153e-09, -3.5592e-08,  8.9747e-08, -5.2506e-09,
            2.3297e-07, -8.9715e-08,  3.3078e-08, -3.9203e-08, -7.0798e-09,
           -9.6940e-08,  4.3877e-09,  9.0006e-08, -9.0015e-08]),
   'exp_avg_sq': tensor([8.3807e-14, 7.7336e-14, 1.0180e-13, 1.3548e-13, 9.7571e-14, 1.0205e-13,
           7.0381e-14, 8.4473e-14, 9.2125e-14, 1.0893e-13, 7.9773e-14, 1.0285e-13,
           6.9130e-14, 7.5173e-14, 7.2554e-14, 6.7129e-14, 7.8062e-14, 1.4769e-13,
           7.0065e-14, 9.7401e-14, 9.7116e-14, 8.2602e-14, 6.9552e-14, 1.0076e-13,
           8.9619e-14, 8.6549e-14, 1.3206e-13, 1.2476e-13, 1.0041e-13, 5.3224e-14,
           9.1195e-14, 6.8559e-14, 1.0964e-13, 1.0002e-13, 9.1159e-14, 8.7800e-14,
           5.9044e-14, 1.0211e-13, 1.0547e-13, 9.3154e-14, 5.4098e-14, 1.1398e-13,
           5.4144e-14, 9.2407e-14, 1.3045e-13, 6.6206e-14, 8.6917e-14, 1.0745e-13,
           6.2120e-14, 7.8512e-14, 8.9938e-14, 8.8002e-14, 8.0064e-14, 8.6259e-14,
           8.0090e-14, 1.0983e-13, 1.1578e-13, 8.0562e-14, 7.6274e-14, 6.9891e-14,
           1.0542e-13, 1.3200e-13, 1.0031e-13, 1.1640e-13])},
  9: {'step': tensor(107.),
   'exp_avg': tensor([[ 2.1599e-06,  1.3085e-07,  1.6959e-07,  ..., -2.0671e-08,
             7.7283e-07, -1.3338e-06],
           [ 3.2306e-07,  1.2441e-06,  3.3009e-07,  ...,  8.3653e-07,
            -1.8285e-07,  7.1873e-08],
           [-4.8910e-07,  2.1450e-07, -3.9121e-07,  ..., -6.6387e-07,
            -6.8160e-07,  1.2346e-07],
           ...,
           [ 9.6394e-08, -1.7141e-06,  5.4554e-07,  ...,  7.2164e-07,
             5.8781e-07, -1.3393e-07],
           [ 8.0919e-07,  9.0654e-08,  4.3397e-07,  ..., -1.0051e-07,
             6.6353e-07, -5.3937e-07],
           [ 1.8728e-07,  1.7371e-07, -1.7943e-07,  ...,  9.5458e-07,
            -1.2289e-06, -1.4097e-06]]),
   'exp_avg_sq': tensor([[4.0624e-12, 3.0813e-12, 1.8960e-12,  ..., 7.2435e-12, 2.8123e-12,
            2.1484e-12],
           [4.2998e-12, 2.6538e-12, 1.7070e-12,  ..., 7.3808e-12, 2.5267e-12,
            2.5062e-12],
           [3.2439e-12, 2.3285e-12, 1.5259e-12,  ..., 7.7896e-12, 2.7036e-12,
            1.9499e-12],
           ...,
           [4.1952e-12, 3.3951e-12, 2.2748e-12,  ..., 6.4338e-12, 2.6371e-12,
            2.9592e-12],
           [2.1422e-12, 1.4526e-12, 1.0136e-12,  ..., 4.0294e-12, 1.4001e-12,
            1.3950e-12],
           [4.8196e-12, 3.3859e-12, 2.0862e-12,  ..., 8.8297e-12, 2.6259e-12,
            2.8612e-12]])},
  10: {'step': tensor(107.),
   'exp_avg': tensor([-1.8020e-05, -6.3220e-08,  2.5519e-05, -1.7525e-06, -1.5187e-05,
           -2.1738e-05, -1.1117e-05,  2.7799e-06, -1.9016e-05, -3.2345e-05,
           -2.5568e-05,  3.7386e-05,  5.2867e-07,  2.7971e-06,  1.1131e-05,
           -1.3969e-05,  3.0502e-06, -2.0056e-05,  1.6526e-05,  1.3325e-05,
            1.1493e-05,  1.7318e-06, -8.0272e-07,  3.2555e-05, -4.0709e-06,
           -2.7176e-05,  2.9361e-05,  6.4840e-06, -1.8417e-05, -2.5736e-05,
           -3.1299e-06,  2.7135e-05,  2.3420e-06, -5.0564e-06, -2.9314e-05,
           -7.0568e-06, -9.5969e-07,  1.6750e-06,  2.7848e-05,  1.9227e-05,
           -8.8707e-06,  7.9547e-06, -1.9059e-05, -3.0382e-05, -1.1237e-05,
            1.6935e-05,  4.3949e-05,  2.7228e-05, -2.6465e-06, -3.8878e-05,
           -7.6465e-06,  1.6387e-05, -5.3731e-06,  5.6928e-05, -2.8935e-07,
            1.4176e-05, -8.0461e-06, -1.5934e-05, -6.1309e-06, -1.4880e-05,
            1.6521e-05, -2.2212e-05,  1.2536e-06,  7.5572e-06]),
   'exp_avg_sq': tensor([1.4497e-09, 1.4751e-09, 1.3835e-09, 1.2347e-09, 1.3469e-09, 1.9950e-09,
           1.5686e-09, 1.0494e-09, 1.8606e-09, 1.1100e-09, 1.4659e-09, 1.5590e-09,
           1.5283e-09, 1.1218e-09, 2.7830e-09, 1.3200e-09, 8.7600e-10, 2.2808e-09,
           2.2430e-09, 1.4656e-09, 1.1344e-09, 1.2306e-09, 1.5092e-09, 1.5478e-09,
           1.2401e-09, 1.1089e-09, 1.9418e-09, 1.3713e-09, 1.3200e-09, 1.6860e-09,
           1.3673e-09, 2.2146e-09, 1.3180e-09, 1.0270e-09, 1.4549e-09, 1.6291e-09,
           1.7258e-09, 7.7555e-10, 1.0480e-09, 1.0798e-09, 1.9530e-09, 1.4002e-09,
           9.8541e-10, 1.7146e-09, 6.7727e-10, 2.3410e-09, 1.5405e-09, 2.0906e-09,
           2.1843e-09, 2.1607e-09, 2.0421e-09, 1.9688e-09, 1.4023e-09, 1.4131e-09,
           1.0385e-09, 2.7824e-09, 1.7979e-09, 1.2084e-09, 1.8170e-09, 1.7740e-09,
           1.4927e-09, 1.5576e-09, 7.8372e-10, 1.8751e-09])},
  11: {'step': tensor(107.),

In [28]:
set(checkpoint_tac_gia.keys()) - set(checkpoint.keys())

{'optimizer', 'state_dict'}

In [15]:
checkpoint['model_state_dict']

OrderedDict([('image_complex_weight',
              tensor([[[-0.7795,  0.5151],
                       [ 0.3265, -0.8950],
                       [-2.2076,  0.5592],
                       [-0.8124,  0.2277],
                       [ 0.1892,  0.6833],
                       [-0.2569,  1.2942],
                       [ 0.5806, -1.4800],
                       [-3.2718, -0.6123],
                       [-1.3429, -0.2191],
                       [-0.0834,  0.6362],
                       [ 0.3822,  1.0347],
                       [ 0.6993,  1.9135],
                       [ 2.2441,  0.9717],
                       [-0.5467,  1.0909],
                       [ 0.5332,  0.3112],
                       [ 1.6389,  0.5942],
                       [-1.7335,  0.9973],
                       [-0.5315,  0.3880],
                       [ 0.2993, -0.9630],
                       [-1.4210,  0.2978],
                       [-1.8644,  0.3032],
                       [ 0.4897,  0.0164],
                       [ 1.5709,  0.0584],
                       [ 0.4865,  0.1272],
                       [ 1.0615,  1.4636],
                       [-0.0993,  0.2494],
                       [-0.7849,  0.2751],
                       [ 1.0854, -0.8806],
                       [ 0.6988,  1.6375],
                       [ 1.2722,  0.0956],
                       [ 0.9437, -0.4365],
                       [ 1.9843, -0.2609],
                       [-0.6976, -2.2491]]])),
             ('text_complex_weight',
              tensor([[[ 1.6830, -0.1765],
                       [ 1.4131, -1.9964],
                       [-1.9969, -0.1866],
                       [-1.8477,  0.5070],
                       [-2.2422, -3.3746],
                       [-1.6885, -3.9279],
                       [ 0.7564, -2.9968],
                       [-2.7708, -0.8465],
                       [-2.5677, -1.4755],
                       [-1.8904, -3.2411],
                       [ 0.9568, -1.2811],
                       [-0.0877, -0.2968],
                       [ 0.4254, -0.3815],
                       [ 0.0219,  1.6651],
                       [ 1.3128,  2.7966],
                       [-2.3842,  0.1477],
                       [ 1.4858,  2.3607],
                       [ 2.3854, -0.1891],
                       [ 3.2635, -3.6636],
                       [-2.7218,  0.6152],
                       [ 2.1043, -1.3968],
                       [-0.2092,  0.5233],
                       [-3.9736,  2.0740],
                       [ 1.7160,  1.2487],
                       [ 2.9466,  1.9740],
                       [ 2.6762,  4.0576],
                       [ 1.5449, -1.1904],
                       [-1.4830,  3.0541],
                       [-1.5447,  2.2520],
                       [-1.9776,  3.3304],
                       [-0.5336,  1.2323],
                       [-2.0049,  2.5171],
                       [ 0.5501,  2.0615]]])),
             ('fusion_complex_weight',
              tensor([[[-1.3944, -1.5227],
                       [-0.8715,  0.7571],
                       [-0.4660, -1.3703],
                       [-0.0974,  1.4864],
                       [-1.4831, -0.1835],
                       [ 0.0861,  1.3566],
                       [-0.3654, -0.9953],
                       [-1.2530,  0.9339],
                       [-2.2308,  0.9645],
                       [-0.7505,  1.4215],
                       [ 1.2835, -0.1011],
                       [-1.2379, -1.7663],
                       [ 1.0684, -0.4666],
                       [-3.2032,  0.5023],
                       [ 0.3292, -1.3331],
                       [ 2.6786, -0.3227],
                       [-1.0954,  0.1716],
                       [ 0.8468, -1.3169],
                       [-1.2347,  0.4865],
                       [ 1.1011,  0.3173],
                       [-0.7699,  0.7163],
                       [ 0.1029,  1.3733],
                       [-0.1347, -0.4451],
                       [ 0.2232, -1.2773],
                       [-0.9897,  0.8736],
                       [-0.2534,  0.3665],
                       [ 0.0907, -2.3748],
                       [ 1.3387,  0.4052],
                       [ 0.2827, -2.1395],
                       [-0.9614, -1.1509],
                       [-0.6734, -2.1066],
                       [ 1.2859,  1.0560],
                       [-1.7007,  1.1054]]])),
             ('user_embedding.weight',
              tensor([[ 0.3206, -0.5063, -0.2246,  ...,  0.2442,  0.5974,  0.2569],
                      [ 0.2112, -0.1267, -0.5186,  ...,  0.2416,  0.2709,  0.3943],
                      [ 0.0474, -0.5523,  0.0519,  ..., -0.5074,  0.2758,  0.3016],
                      ...,
                      [ 0.0269, -0.1948, -0.5178,  ...,  0.2758, -0.1752, -0.4473],
                      [ 0.1213, -0.6196, -0.1530,  ...,  0.2784,  0.3963,  0.3812],
                      [ 0.0144, -0.3643, -0.3081,  ..., -0.0387,  0.2521, -0.1906]])),
             ('item_id_embedding.weight',
              tensor([[ 0.3583, -0.6409, -0.4428,  ...,  0.3149,  0.1707,  0.7071],
                      [-0.3959, -0.4909,  0.2521,  ...,  0.3905,  0.3591,  0.3866],
                      [-0.4718,  0.0576, -0.0037,  ...,  0.1730,  0.3741, -0.3174],
                      ...,
                      [-0.4024, -0.3595,  0.1269,  ..., -0.3702, -0.5999, -0.4420],
                      [-0.0505, -0.4608, -0.3657,  ..., -0.1708, -0.3511, -0.3977],
                      [ 0.0165, -0.0826, -0.0282,  ..., -0.0415,  0.4130, -0.4625]])),
             ('image_embedding.weight',
              tensor([[ 1.3192e-03,  5.2707e+00, -2.3776e-04,  ...,  1.3668e-03,
                        4.0829e-03,  2.4771e-04],
                      [ 4.6694e-03,  1.7553e-03,  6.5934e-04,  ...,  2.9930e+00,
                        4.1630e-01,  4.1209e-03],
                      [ 1.1802e-03,  7.2503e-04,  6.4659e-05,  ...,  5.0880e-04,
                        1.7272e+00,  1.0857e-03],
                      ...,
                      [ 1.6760e-03,  3.9204e-05,  5.9990e-04,  ...,  2.1854e-03,
                        1.8988e-03,  3.9059e-04],
                      [-8.7932e-04,  3.4516e+00, -6.8174e-04,  ..., -2.0973e-03,
                        9.2799e-05, -1.2397e-03],
                      [ 1.9964e-03,  5.6128e-04,  3.0221e-03,  ...,  1.3808e-03,
                        6.0698e-03,  1.3095e+00]])),
             ('text_embedding.weight',
              tensor([[-0.0864,  0.0095, -0.0377,  ..., -0.1754,  0.1218,  0.0501],
                      [-0.0584, -0.0029, -0.0592,  ...,  0.0081,  0.1057,  0.1043],
                      [-0.1612,  0.1014, -0.0210,  ..., -0.2483,  0.0123,  0.0953],
                      ...,
                      [-0.0149,  0.0348, -0.0401,  ..., -0.1198, -0.0347, -0.0367],
                      [-0.0491,  0.0183,  0.0390,  ..., -0.0198, -0.0858, -0.0064],
                      [-0.0511, -0.0751,  0.0656,  ...,  0.0762,  0.0448, -0.0469]])),
             ('image_trs.weight',
              tensor([[-0.0252, -0.0132, -0.0514,  ..., -0.0425, -0.0446, -0.0266],
                      [ 0.0636,  0.0115,  0.0074,  ...,  0.0314,  0.0425,  0.0707],
                      [-0.0137,  0.0150, -0.0288,  ...,  0.0272, -0.0060, -0.0084],
                      ...,
                      [-0.0491, -0.0841, -0.0461,  ..., -0.0992, -0.0983, -0.0618],
                      [-0.0241,  0.0012, -0.0209,  ...,  0.0238,  0.0379, -0.0209],
                      [ 0.0957,  0.0824,  0.0724,  ...,  0.0248,  0.0962,  0.1053]])),
             ('image_trs.bias',
              tensor([-0.0127,  0.0976, -0.0148,  0.0687, -0.1106, -0.0235, -0.1278, -0.0304,
                      -0.0538, -0.0332, -0.0566,  0.0506, -0.0779,  0.1118,  0.0029, -0.0005,
                      -0.1082, -0.1331,  0.1047,  0.1864, -0.1778,  0.0146,  0.0403, -0.0510,
                      -0.1402,  0.1430,  0.1274,  0.0621, -0.0747, -0.0657,  0.0449,  0.0077,
                       0.1297,  0.1150,  0.0487,  0.2225,  0.0768,  0.1183,  0.0293, -0.0468,
                       0.0851, -0.0794, -0.1259, -0.0006, -0.0747, -0.1017, -0.0489,  0.1438,
                       0.0501,  0.1126,  0.0404, -0.0613, -0.0461,  0.0083,  0.0475, -0.1301,
                       0.1642,  0.0190,  0.1640,  0.0004, -0.0267, -0.1225,  0.0121,  0.1181])),
             ('text_trs.weight',
              tensor([[-0.0043,  0.0085,  0.0263,  ..., -0.0365, -0.0437,  0.0282],
                      [-0.0201, -0.0540, -0.0258,  ...,  0.0007,  0.0561, -0.0253],
                      [ 0.0230, -0.0826,  0.0236,  ...,  0.0418, -0.1010,  0.0439],
                      ...,
                      [-0.0093, -0.0401, -0.0392,  ..., -0.0385, -0.0255, -0.0175],
                      [-0.0111, -0.0050, -0.0382,  ..., -0.0080, -0.0638, -0.0033],
                      [ 0.0115, -0.0536,  0.0416,  ..., -0.0692, -0.0289,  0.0751]])),
             ('text_trs.bias',
              tensor([ 0.0468,  0.0347, -0.0461, -0.0005, -0.0357, -0.0137,  0.0504,  0.0336,
                      -0.0272,  0.0840,  0.0382, -0.0800, -0.0217,  0.0192, -0.0123, -0.0446,
                      -0.0474,  0.0008,  0.0583, -0.0218,  0.0213, -0.0881,  0.0482, -0.0128,
                       0.0863,  0.0571, -0.0597,  0.1404, -0.0427, -0.0607, -0.0185,  0.0435,
                      -0.0136,  0.0062, -0.0524,  0.0992,  0.0243, -0.0406,  0.0413, -0.0687,
                       0.0875,  0.0401, -0.0282,  0.0026, -0.0398, -0.0298, -0.0331, -0.0265,
                       0.1066, -0.0039, -0.0258, -0.0542, -0.0504, -0.0409,  0.0090, -0.0508,
                       0.0537, -0.0541,  0.0231,  0.0156,  0.0135,  0.0139,  0.0233,  0.0719])),
             ('query_v.0.weight',
              tensor([[ 0.3075,  1.0699,  0.1370,  ...,  0.2130,  0.2471,  0.3486],
                      [ 0.0382, -0.0811,  0.1432,  ..., -0.3010,  0.0892, -0.2823],
                      [ 0.1520, -0.0443,  0.0115,  ...,  0.3209, -0.0341,  0.2241],
                      ...,
                      [ 0.2624, -0.5116,  0.1603,  ...,  0.3212,  0.0281, -0.0625],
                      [-0.4247, -0.0119, -0.2502,  ..., -0.1467, -0.1028, -0.0356],
                      [-0.0597, -0.7457,  0.1054,  ..., -0.2398, -0.1649, -0.0480]])),
             ('query_v.0.bias',
              tensor([-0.4514, -0.3457, -0.1266,  0.3547, -0.4610,  0.0288,  0.1516,  0.2781,
                      -0.1937, -0.0108,  0.3289,  0.5914,  0.1794,  0.2416,  0.3032,  0.1360,
                       0.2848, -0.0601, -0.4653,  0.3875,  0.4402, -0.2983,  0.1979, -0.6003,
                      -0.4682,  0.5326,  0.4401,  0.2966, -0.3814,  0.4755,  0.3495, -0.0446,
                      -0.2426,  0.0047, -0.3098, -0.3848, -0.2337,  0.3998,  0.2052, -0.1307,
                      -0.3422, -0.0875, -0.3139,  0.1768,  0.2935, -0.3044, -0.3660, -0.3462,
                      -0.2667, -0.5028,  0.4054,  0.2174,  0.2366, -0.4362,  0.1962, -0.4754,
                       0.1178, -0.2512,  0.2864, -0.4124, -0.2485,  0.0652, -0.6259,  0.1301])),
             ('query_v.2.weight',
              tensor([[ 0.2859,  0.2673,  0.0976,  ..., -0.0981,  0.4370, -0.2537],
                      [ 0.4306, -0.2697,  0.1340,  ..., -0.1990, -0.0033, -0.4194],
                      [ 0.1620,  0.4922, -0.2668,  ..., -0.2862,  0.4851,  0.2183],
                      ...,
                      [ 0.2438,  0.3342,  0.1669,  ...,  0.2866,  0.1407, -0.2023],
                      [ 0.0049,  0.3782,  0.2430,  ..., -0.0399,  0.3931,  0.2892],
                      [ 0.2523,  0.4132,  0.1346,  ..., -0.5723,  0.3930, -0.1554]])),
             ('query_t.0.weight',
              tensor([[-0.2449, -0.4333,  0.0713,  ...,  0.3608,  0.1416, -0.2651],
                      [-0.2580, -0.4277,  0.3365,  ...,  0.3841,  0.1019,  0.1891],
                      [-0.3311,  0.0237, -0.1723,  ..., -0.3539,  0.2102,  0.1448],
                      ...,
                      [ 0.2989, -0.3151,  0.2857,  ..., -0.1901,  0.1272,  0.0869],
                      [-0.3178,  0.4072, -0.2545,  ..., -0.1887,  0.1672,  0.3884],
                      [ 0.4920,  0.1852, -0.3268,  ...,  0.1685, -0.3985, -0.4489]])),
             ('query_t.0.bias',
              tensor([ 0.0288,  0.5722, -0.2622,  0.1394, -0.1236,  0.1243,  0.2704, -0.0364,
                      -0.0217, -0.0708,  0.3442,  0.1861,  0.2347,  0.0544, -0.1166, -0.1483,
                       0.2914,  0.3038, -0.3071, -0.0159, -0.5021,  0.0858, -0.3301,  0.1321,
                       0.2308,  0.0566, -0.1679,  0.3161, -0.1251, -0.2732, -0.2883, -0.4075,
                       0.0518,  0.1257,  0.5183, -0.0598, -0.3379, -0.1529, -0.3671, -0.2240,
                       0.1749,  0.1176,  0.0273,  0.3127, -0.0736,  0.3295, -0.3042,  0.0831,
                      -0.2617, -0.0806,  0.6233, -0.5313, -0.2645, -0.2877, -0.1521,  0.0495,
                       0.2576, -0.3367,  0.5217, -0.0641,  0.2683,  0.2932, -0.2051, -0.0491])),
             ('query_t.2.weight',
              tensor([[ 0.0381,  0.0288,  0.4892,  ..., -0.2232,  0.5775, -0.2141],
                      [-0.0868, -0.7146,  0.0240,  ..., -0.6295,  0.2026,  0.0021],
                      [-0.2576, -0.3980,  0.4577,  ..., -0.3742,  0.4906,  0.5647],
                      ...,
                      [-0.4060, -0.4848, -0.0815,  ..., -0.2032,  0.3564, -0.0662],
                      [ 0.3488, -0.0136,  0.0526,  ..., -0.4036, -0.0225, -0.5293],
                      [-0.2689,  0.3511, -0.0852,  ...,  0.2538,  0.2679, -0.2699]])),
             ('gate_v.0.weight',
              tensor([[ 0.0553, -0.1396,  0.0908,  ..., -0.0647, -0.1030, -0.0857],
                      [ 0.0388, -0.0493, -0.0690,  ..., -0.0206, -0.1051, -0.0412],
                      [-0.0632, -0.0819, -0.0490,  ..., -0.0158,  0.0466,  0.1034],
                      ...,
                      [ 0.0322, -0.0355,  0.0792,  ...,  0.1045,  0.1029, -0.0428],
                      [-0.1025, -0.0221, -0.1350,  ..., -0.0712,  0.0271, -0.0532],
                      [ 0.0950,  0.0610, -0.1129,  ...,  0.1159,  0.1149, -0.0683]])),
             ('gate_v.0.bias',
              tensor([ 0.0580, -0.0693,  0.0320,  0.0961, -0.1036,  0.0504, -0.0296,  0.1271,
                       0.0389,  0.1162,  0.1276, -0.0914,  0.0505,  0.0239,  0.1394, -0.0262,
                      -0.0414,  0.0777, -0.0698,  0.1343,  0.0619,  0.0778,  0.0108, -0.0559,
                       0.0694, -0.0506,  0.0610,  0.0501, -0.0658,  0.0343,  0.0365, -0.0528,
                      -0.0811, -0.0728,  0.0953, -0.0460,  0.1266, -0.0545,  0.0328,  0.1315,
                       0.0371,  0.0794, -0.0331,  0.0518, -0.0198,  0.0720, -0.0052,  0.0197,
                      -0.0448,  0.1149,  0.1136,  0.0505, -0.0589,  0.0841,  0.1220,  0.0498,
                      -0.0235,  0.0522,  0.0783,  0.0352,  0.0295,  0.0557, -0.0872, -0.0153])),
             ('gate_t.0.weight',
              tensor([[ 0.3926, -0.2206,  0.4301,  ..., -0.2590, -0.2254,  0.5171],
                      [ 0.1658, -0.1669,  0.6228,  ..., -0.1912, -0.2138,  0.2387],
                      [ 0.0822, -0.1341,  0.3051,  ..., -0.3198, -0.1410,  0.6854],
                      ...,
                      [ 0.2787, -0.0650,  0.4149,  ..., -0.2875, -0.1787,  0.6941],
                      [-0.1449, -0.2050,  0.2098,  ..., -0.2173, -0.3924,  0.4312],
                      [ 0.0442, -0.6271,  0.4615,  ..., -0.6246, -0.2618,  0.8164]])),
             ('gate_t.0.bias',
              tensor([0.3185, 0.3666, 0.2777, 0.3734, 0.4430, 0.3729, 0.6565, 0.4575, 0.3823,
                      0.5197, 0.5557, 0.3204, 0.4513, 0.5920, 0.6351, 0.4557, 0.3934, 0.3196,
                      0.3400, 0.4209, 0.4126, 0.4389, 0.5527, 0.4043, 0.7388, 0.3064, 0.4116,
                      0.5107, 0.5510, 0.4408, 0.3001, 0.3858, 0.5488, 0.4598, 0.5561, 0.4704,
                      0.3911, 0.5271, 0.4362, 0.4328, 0.4797, 0.3001, 0.6351, 0.5877, 0.2167,
                      0.4992, 0.4579, 0.5728, 0.2499, 0.3736, 0.4172, 0.4119, 0.5105, 0.4094,
                      0.5867, 0.5572, 0.4450, 0.4783, 0.4400, 0.4388, 0.3939, 0.3359, 0.3668,
                      0.3909])),
             ('gate_f.0.weight',
              tensor([[ 0.1299,  0.0216,  0.0527,  ...,  0.1137,  0.0527, -0.0370],
                      [-0.0280, -0.1218, -0.1356,  ..., -0.1252, -0.0380, -0.0772],
                      [ 0.0461, -0.1317, -0.0104,  ..., -0.1190, -0.2553,  0.0003],
                      ...,
                      [-0.2429,  0.1576,  0.1651,  ..., -0.0901,  0.1335, -0.0531],
                      [-0.1380, -0.0009, -0.0162,  ...,  0.0100,  0.3197, -0.1351],
                      [-0.1849, -0.1019,  0.0625,  ...,  0.0303, -0.0339, -0.1103]])),
             ('gate_f.0.bias',
              tensor([ 0.0330,  0.0644, -0.0161, -0.0556,  0.0376, -0.0317,  0.1286,  0.0279,
                      -0.0031, -0.0030, -0.0711,  0.0792, -0.0198,  0.0688,  0.0437,  0.1571,
                       0.0290,  0.0360,  0.0801, -0.0299,  0.0790, -0.1039,  0.1094,  0.1405,
                       0.0927,  0.1146,  0.1194,  0.0676,  0.0793,  0.0158, -0.0018,  0.0884,
                       0.0467,  0.1252,  0.1417, -0.0671,  0.0133,  0.0617,  0.0969,  0.1012,
                      -0.0124,  0.0342, -0.0490,  0.0666,  0.0604,  0.0265,  0.1015, -0.0813,
                       0.0227,  0.0008,  0.0984,  0.0256,  0.1018,  0.0813, -0.0127,  0.0028,
                      -0.0320,  0.1162, -0.0235, -0.0039,  0.0454,  0.1207,  0.0832,  0.0701])),
             ('gate_image_prefer.0.weight',
              tensor([[ 0.1596,  0.4010, -0.0171,  ...,  0.1777, -0.1550, -0.3144],
                      [ 1.3626,  2.2924, -0.5229,  ...,  0.4348, -0.4469, -1.1977],
                      [-0.1231,  0.5891, -0.5153,  ..., -0.0734, -0.5258, -0.4971],
                      ...,
                      [ 0.0841,  0.2332, -0.1259,  ...,  0.3663,  0.1029, -0.1798],
                      [-0.1909, -0.0972, -0.0158,  ...,  0.1762,  0.0321, -0.0403],
                      [ 0.0691,  0.2384, -0.1878,  ...,  0.0209, -0.2931, -0.2944]])),
             ('gate_image_prefer.0.bias',
              tensor([0.8527, 2.4637, 0.8564, 0.5790, 0.5924, 2.8939, 2.4304, 0.6795, 1.4090,
                      0.7135, 2.8690, 2.8256, 1.0696, 1.0731, 2.8279, 1.3977, 0.6862, 0.5050,
                      1.0045, 0.8558, 1.1126, 1.1829, 1.5008, 1.1817, 1.5163, 2.0031, 0.1263,
                      2.5947, 2.8062, 2.5093, 1.6410, 0.7142, 1.2687, 1.3425, 0.8265, 0.6849,
                      0.9498, 0.6273, 2.7845, 2.2563, 0.7449, 2.6647, 1.3927, 1.0151, 1.2524,
                      0.8958, 2.4945, 1.2269, 0.7245, 1.0636, 2.5975, 0.8436, 2.6649, 2.7382,
                      1.2435, 0.9058, 0.7984, 0.5887, 0.9175, 1.6229, 0.5534, 1.0248, 1.2246,
                      0.5579])),
             ('gate_text_prefer.0.weight',
              tensor([[-1.0975, -0.1327,  0.0652,  ..., -0.1431,  0.6031,  0.7797],
                      [-0.2544,  0.0722,  0.1907,  ...,  0.2155,  0.0444,  0.3075],
                      [-0.2800,  0.2842, -0.2712,  ..., -0.2330, -0.0833,  0.1452],
                      ...,
                      [-0.2677,  0.1677, -0.2161,  ..., -0.3510,  0.3237,  0.0844],
                      [-1.0026, -0.7020,  0.2395,  ..., -0.0805,  0.5402,  0.8557],
                      [-1.0631, -0.0662,  0.4100,  ...,  0.2493,  0.7869,  1.4291]])),
             ('gate_text_prefer.0.bias',
              tensor([1.6807, 0.7959, 1.1478, 1.3733, 2.3984, 1.3920, 2.7852, 2.9341, 1.6487,
                      1.9824, 2.2234, 1.8588, 2.6344, 2.8720, 2.1952, 1.1476, 2.1680, 1.5384,
                      1.0282, 1.0584, 2.0548, 1.4910, 2.8869, 1.8670, 2.4469, 1.2771, 2.3274,
                      2.5364, 1.8015, 2.5944, 1.6613, 2.7352, 1.9109, 0.9786, 2.8969, 2.0336,
                      2.6334, 2.2105, 1.8437, 1.1786, 2.7339, 0.8973, 2.6968, 2.1740, 1.0227,

In [16]:
set(checkpoint_tac_gia.keys()) - set(checkpoint.keys())

{'config', 'cur_step', 'optimizer', 'state_dict'}

In [17]:
set(checkpoint_tac_gia["state_dict"]) - set(checkpoint['model_state_dict'])

{'predictor.bias', 'predictor.weight'}

In [18]:
set(checkpoint['model_state_dict']) - set(checkpoint_tac_gia["state_dict"])

{'fusion_complex_weight',
 'gate_f.0.bias',
 'gate_f.0.weight',
 'gate_fusion_prefer.0.bias',
 'gate_fusion_prefer.0.weight',
 'gate_image_prefer.0.bias',
 'gate_image_prefer.0.weight',
 'gate_t.0.bias',
 'gate_t.0.weight',
 'gate_text_prefer.0.bias',
 'gate_text_prefer.0.weight',
 'gate_v.0.bias',
 'gate_v.0.weight',
 'image_complex_weight',
 'query_t.0.bias',
 'query_t.0.weight',
 'query_t.2.weight',
 'query_v.0.bias',
 'query_v.0.weight',
 'query_v.2.weight',
 'text_complex_weight'}

In [245]:
def load_model_tac_gia(checkpoint_tac_gia):
    # 1. Khởi tạo model trống với kiến trúc hiện tại của bạn
    config = Config('SMORE', 'sports', {}, mg=False)
    model = load_model(config) 

    # 2. Lấy state_dict từ checkpoint
    ckpt_dict = checkpoint_tac_gia['state_dict'] if 'state_dict' in checkpoint_tac_gia else checkpoint_tac_gia

    # 3. Lọc lấy các lớp trùng tên VÀ trùng kích thước
    model_dict = model.state_dict()
    valid_weights = {}

    for k, v in ckpt_dict.items():
        if k in model_dict:
            if v.shape == model_dict[k].shape:
                valid_weights[k] = v
            else:
                print(f"⚠️ Bỏ qua {k} do lệch size: Checkpoint {v.shape} vs Model {model_dict[k].shape}")
        else:
            print(f"❓ Lớp {k} trong checkpoint không có trong code hiện tại.")

    # 4. Nạp đè vào model
    model_dict.update(valid_weights)
    model.load_state_dict(model_dict)
    print(f"✅ Đã nạp thành công {len(valid_weights)} lớp!")

    return model

model_tac_gia = load_model_tac_gia(checkpoint_tac_gia)

sports
The number of users: 35598
Average actions of users: 8.324540704533963
The number of items: 18357
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465195454304%
❓ Lớp predictor.weight trong checkpoint không có trong code hiện tại.
❓ Lớp predictor.bias trong checkpoint không có trong code hiện tại.
✅ Đã nạp thành công 8 lớp!

In [248]:
config = Config('SMORE', 'sports', {}, mg=False)
model = load_model(config=config)  # We only need the model architecture to load weights
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

print(f"✓ Model loaded successfully!")
print(f"  Epoch: {checkpoint['epoch']}")

sports
The number of users: 35598
Average actions of users: 8.324540704533963
The number of items: 18357
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465195454304%
✓ Model loaded successfully!
  Epoch: 43

In [ ]:
def test_model(model):
    # Your loaded model (from previous cells)
    # model.eval()  # Make sure it's in eval mode

    # Get all user and item embeddings
    user_embeddings, item_embeddings = model.forward(model.norm_adj)

    print(f"User embeddings shape: {user_embeddings.shape}")  # [n_users, embedding_dim]
    print(f"Item embeddings shape: {item_embeddings.shape}")  # [n_items, embedding_dim]

    # Get recommendations for multiple users - call separately
    user_ids = [0, 1, 2]
    top_k = 10

    for user_id in user_ids:
        user_tensor = torch.tensor([user_id])
        scores = model.full_sort_predict(user_tensor)
        
        # Get top for this user
        _, top_items = torch.topk(scores, top_k)
        print(f"Top {top_k} items for user {user_id}: {top_items.tolist()}")

In [128]:
df_user_map.info()

<class 'pandas.DataFrame'>
RangeIndex: 35598 entries, 0 to 35597
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reviewerID    35598 non-null  str
 1   reviewerName  35598 non-null  str
 2   userID        35598 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.7 MB

In [129]:
df_user_map[df_user_map["userID"] == 0]

         reviewerID  reviewerName  userID
31083  AIXZKN4ACSKI  David Briner       0

In [130]:
df_meta_map.info()

<class 'pandas.DataFrame'>
RangeIndex: 18357 entries, 0 to 18356
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         18357 non-null  str
 1   title        18267 non-null  str
 2   price        14764 non-null  float64
 3   imUrl        18325 non-null  str
 4   related      18236 non-null  object
 5   brand        12333 non-null  str
 6   categories   18357 non-null  object
 7   salesRank    16055 non-null  object
 8   description  16620 non-null  str
 9   itemID       18357 non-null  int64
dtypes: float64(1), int64(1), object(3), str(5)
memory usage: 13.0+ MB

In [134]:
df_meta_map[df_meta_map["itemID"] == 16459]

,asin,title,price,imUrl,related,brand,categories,salesRank,description,itemID
16459,B008W0DRNM,Solo Pot 900: Lightweight Stainless Steel Back...,34.99,http://ecx.images-amazon.com/images/I/41ZDziR5...,"{'also_bought': ['B007DBD3IU', 'B008VZ91WO', '...",NaN,"[[Sports & Outdoors, Outdoor Gear, Camping & H...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",The lightweight Solo Pot 900 is the companion ...,16459

In [116]:
test_model(model)

User embeddings shape: torch.Size([35598, 64])
Item embeddings shape: torch.Size([18357, 64])
Top 10 items for user 0: [4199, 5217, 11362, 7101, 7950, 14657, 2032, 5170, 11981, 11361]
Top 10 items for user 1: [8802, 14212, 2875, 9250, 9841, 4424, 7101, 6090, 7950, 14990]
Top 10 items for user 2: [7101, 9250, 4199, 7950, 2875, 5217, 11362, 10958, 8184, 10057]

In [251]:
test_model(model)

User embeddings shape: torch.Size([35598, 64])
Item embeddings shape: torch.Size([18357, 64])
Top 10 items for user 0: [4199, 5217, 11362, 7101, 7950, 14657, 2032, 5170, 11981, 11361]
Top 10 items for user 1: [8802, 14212, 2875, 9250, 9841, 4424, 7101, 6090, 7950, 14990]
Top 10 items for user 2: [7101, 9250, 4199, 7950, 2875, 5217, 11362, 10958, 8184, 10057]

In [236]:
df_meta_map[df_meta_map["itemID"] == 8802]

,asin,title,price,imUrl,related,brand,categories,salesRank,description,itemID
8801,B002E6X44C,Tapco Intrafuse AR Stock Spanner Wrench TOOL0904,10.99,http://ecx.images-amazon.com/images/I/316xmD2E...,"{'also_bought': ['B005J13VCO', 'B00KFR6YZS', '...",Tapco,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...","Precision machined from heat treated steel, ou...",8802

In [252]:
test_model(model_state)

User embeddings shape: torch.Size([35598, 64])
Item embeddings shape: torch.Size([18357, 64])
Top 10 items for user 0: [18182, 16459, 18264, 18266, 17861, 18352, 18265, 18071, 15362, 18070]
Top 10 items for user 1: [17959, 18341, 18030, 18301, 15936, 18333, 4154, 18328, 18167, 13014]
Top 10 items for user 2: [10937, 10938, 11378, 11361, 4199, 10053, 13014, 8776, 9468, 11360]

In [253]:
test_model(model_tac_gia)

User embeddings shape: torch.Size([35598, 64])
Item embeddings shape: torch.Size([18357, 64])
Top 10 items for user 0: [7101, 7950, 4199, 5217, 7102, 500, 248, 11981, 2585, 11362]
Top 10 items for user 1: [7101, 7950, 9250, 7102, 15075, 9735, 10057, 9841, 12981, 6779]
Top 10 items for user 2: [7101, 7950, 9250, 7102, 15075, 9735, 2875, 248, 10057, 10958]

In [235]:
df_meta_map[df_meta_map["itemID"] == 7101]

,asin,title,price,imUrl,related,brand,categories,salesRank,description,itemID
7101,B001HBHNHE,Butler Creek Lula Universal Pistol Magazine Lo...,27.49,http://ecx.images-amazon.com/images/I/31gyd1PY...,"{'also_bought': ['B003ITKHM6', 'B001HBHNHY', '...",MagLula,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Speed up and simplify the pistol loading proce...,7101

In [212]:
import json

def get_recommendations_json(model, df_user_map, df_meta_map, user_ids=[0, 1, 2], top_k=5, filename="results.json"):
    model.eval()
    all_recommendations = {}

    with torch.no_grad():
        for u_id in user_ids:
            # 1. Dự đoán
            user_tensor = torch.tensor([u_id])
            scores = model.full_sort_predict(user_tensor)
            _, top_items_indices = torch.topk(scores, top_k)
            top_items_list = top_items_indices.flatten().tolist()

            # 2. Lấy thông tin người dùng từ df_user_map
            user_row = df_user_map[df_user_map['userID'] == u_id]
            
            # Khởi tạo thông tin user mặc định
            user_data = {
                "userID": u_id,
                "reviewerID": "Unknown",
                "reviewerName": "Unknown"
            }

            if not user_row.empty:
                # Trích xuất đúng tên cột từ dataframe gốc của bạn
                user_data["reviewerID"] = user_row.iloc[0]['reviewerID']
                # Xử lý NaN cho reviewerName
                name = user_row.iloc[0]['reviewerName']
                user_data["reviewerName"] = name if pd.notna(name) else None

            # 3. Lấy danh sách sản phẩm (giống như các bước trước)
            product_details = []
            for i_id in top_items_list:
                product_row = df_meta_map[df_meta_map['itemID'] == i_id]
                if not product_row.empty:
                    cols_to_keep = ['itemID', 'asin', 'title', 'price', 'imUrl']
                    existing_cols = [c for c in cols_to_keep if c in product_row.columns]
                    item_dict = product_row[existing_cols].to_dict('records')[0]
                    # Fix NaN cho item
                    item_dict = {k: (v if pd.notna(v) else None) for k, v in item_dict.items()}
                    product_details.append(item_dict)
                else:
                    product_details.append({"itemID": i_id, "error": "Not found"})

            # 4. Gộp vào kết quả với cấu trúc tách biệt
            all_recommendations[str(u_id)] = {
                "reviewerID": user_data["reviewerID"],
                "reviewerName": user_data["reviewerName"],
                "recommendations": product_details
            }

    # Ghi trực tiếp vào file
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(all_recommendations, f, indent=4, ensure_ascii=False)
    
    print(f"Đã lưu kết quả vào file: {filename}")
    return all_recommendations

# --- CÁCH SỬ DỤNG ---
# results = get_recommendations_json(model, df_user_map, df_meta_map, filename="amazon_rec.json")

In [257]:
# --- CÁCH SỬ DỤNG ---
json_result = get_recommendations_json(model, df_user_map, df_meta_map)
print(json_result)

Đã lưu kết quả vào file: results.json
{'0': {'reviewerID': 'AIXZKN4ACSKI', 'reviewerName': 'David Briner', 'recommendations': [{'itemID': 4199, 'asin': 'B000U3YWEM', 'title': 'Glock Bench Mat', 'price': 11.39, 'imUrl': 'http://ecx.images-amazon.com/images/I/51DyX9CXVkL._SX300_.jpg'}, {'itemID': 5217, 'asin': 'B0014VX2M2', 'title': 'GLOCK DISASSEMBLY TOOL', 'price': 8.18, 'imUrl': 'http://ecx.images-amazon.com/images/I/31c-ZYX%2BLcL._SX300_.jpg'}, {'itemID': 11362, 'asin': 'B003WG95H8', 'title': 'Gen 1-3 Grip Plug for Medium &amp; Large Frames Glocks 17 19 20 21 22 23 24 25 31 32 34 35', 'price': 6.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/41EY1By7UlL._SY300_.jpg'}, {'itemID': 7101, 'asin': 'B001HBHNHE', 'title': 'Butler Creek Lula Universal Pistol Magazine Loader', 'price': 27.49, 'imUrl': 'http://ecx.images-amazon.com/images/I/31gyd1PYsfL._SX300_.jpg'}, {'itemID': 7950, 'asin': 'B001T7QJ9O', 'title': 'Howard Leight R-01526 Impact Sport Electronic Earmuff', 'price': 48.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/41bcSICIjBL._SY300_.jpg'}]}, '1': {'reviewerID': 'A1L5P841VIO02V', 'reviewerName': 'Jason A. Kramer', 'recommendations': [{'itemID': 8802, 'asin': 'B002E6X44C', 'title': 'Tapco Intrafuse AR Stock Spanner Wrench TOOL0904', 'price': 10.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/316xmD2EM3L._SY300_.jpg'}, {'itemID': 14212, 'asin': 'B005J13VCO', 'title': 'Squirrel Daddy Ar15 / M16 Lower Receiver Magazine Vise Block Made In Usa', 'price': 9.78, 'imUrl': 'http://ecx.images-amazon.com/images/I/31gwKoD%2BYdL._SY300_.jpg'}, {'itemID': 2875, 'asin': 'B000JZ7JM8', 'title': 'Hogue Handall Full Size Grip Sleeve', 'price': 7.3, 'imUrl': 'http://ecx.images-amazon.com/images/I/31yBHArbjqL.jpg'}, {'itemID': 9250, 'asin': 'B002OKWHVO', 'title': '.223 Caliber Cartridge Laser Bore Sighter Boresighter', 'price': 7.75, 'imUrl': 'http://ecx.images-amazon.com/images/I/41LOIHxdfZL._SY300_.jpg'}, {'itemID': 9841, 'asin': 'B0030V95P2', 'title': 'Tapco Intrafuse T6 Rubber Butt Pad', 'price': 4.21, 'imUrl': 'http://ecx.images-amazon.com/images/I/31wJun0woQL._SY300_.jpg'}]}, '2': {'reviewerID': 'AB2W04NI4OEAD', 'reviewerName': 'J. Fernald', 'recommendations': [{'itemID': 7101, 'asin': 'B001HBHNHE', 'title': 'Butler Creek Lula Universal Pistol Magazine Loader', 'price': 27.49, 'imUrl': 'http://ecx.images-amazon.com/images/I/31gyd1PYsfL._SX300_.jpg'}, {'itemID': 9250, 'asin': 'B002OKWHVO', 'title': '.223 Caliber Cartridge Laser Bore Sighter Boresighter', 'price': 7.75, 'imUrl': 'http://ecx.images-amazon.com/images/I/41LOIHxdfZL._SY300_.jpg'}, {'itemID': 4199, 'asin': 'B000U3YWEM', 'title': 'Glock Bench Mat', 'price': 11.39, 'imUrl': 'http://ecx.images-amazon.com/images/I/51DyX9CXVkL._SX300_.jpg'}, {'itemID': 7950, 'asin': 'B001T7QJ9O', 'title': 'Howard Leight R-01526 Impact Sport Electronic Earmuff', 'price': 48.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/41bcSICIjBL._SY300_.jpg'}, {'itemID': 2875, 'asin': 'B000JZ7JM8', 'title': 'Hogue Handall Full Size Grip Sleeve', 'price': 7.3, 'imUrl': 'http://ecx.images-amazon.com/images/I/31yBHArbjqL.jpg'}]}}

In [171]:
df_meta_reviews.head(3)

,asin,title,price,imUrl,related,brand,categories,salesRank,description,reviewerID,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,1881509818,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,http://ecx.images-amazon.com/images/I/21iMxsyD...,"{'also_bought': ['B000U3YWEM', 'B000U401J6', '...",Ghost,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Ghost Armorer Tool (1). The GAT is made with a...,AIXZKN4ACSKI,David Briner,"[0, 0]",This came in on time and I am veru happy with ...,5,Woks very good,1390694400,"01 26, 2014"
1,1881509818,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,http://ecx.images-amazon.com/images/I/21iMxsyD...,"{'also_bought': ['B000U3YWEM', 'B000U401J6', '...",Ghost,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Ghost Armorer Tool (1). The GAT is made with a...,A1L5P841VIO02V,Jason A. Kramer,"[1, 1]",I had a factory Glock tool that I was using fo...,5,Works as well as the factory tool,1328140800,"02 2, 2012"
2,1881509818,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,http://ecx.images-amazon.com/images/I/21iMxsyD...,"{'also_bought': ['B000U3YWEM', 'B000U401J6', '...",Ghost,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Ghost Armorer Tool (1). The GAT is made with a...,AB2W04NI4OEAD,J. Fernald,"[2, 2]",If you don't have a 3/32 punch or would like t...,4,"It's a punch, that's all.",1330387200,"02 28, 2012"

In [172]:
df_meta_map.head(3)

,asin,title,price,imUrl,related,brand,categories,salesRank,description,itemID
0,1881509818,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,http://ecx.images-amazon.com/images/I/21iMxsyD...,"{'also_bought': ['B000U3YWEM', 'B000U401J6', '...",Ghost,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Ghost Armorer Tool (1). The GAT is made with a...,0
1,2094869245,5 LED Bicycle Rear Tail Red Bike Torch Laser B...,8.26,http://ecx.images-amazon.com/images/I/51RtwnJw...,"{'also_bought': ['B0081O93N2', 'B00EYTCHJA', '...",,"[[Sports & Outdoors, Cycling, Lights & Reflect...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",This newly-designed Laser tail light can emit ...,1
2,7245456313,Black Mountain Products Resistance Band Set wi...,32.99,http://ecx.images-amazon.com/images/I/51FdHlZS...,"{'also_bought': ['1612431712', 'B00GSBMW2Y', '...",Black Mountain,"[[Sports & Outdoors, Exercise & Fitness, Acces...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",[if gte mso 9]><xml> <o:OfficeDocumentSettings...,3

In [180]:
df_meta_reviews_map = pd.merge(df_meta_reviews, df_meta_map[["asin", "itemID"]], on="asin")
df_meta_reviews_map.head(1)

,asin,title,price,imUrl,related,brand,categories,salesRank,description,reviewerID,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,itemID
0,1881509818,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,http://ecx.images-amazon.com/images/I/21iMxsyD...,"{'also_bought': ['B000U3YWEM', 'B000U401J6', '...",Ghost,"[[Sports & Outdoors, Hunting & Fishing, Huntin...","{'Arts, Crafts & Sewing': None, 'Automotive': ...",Ghost Armorer Tool (1). The GAT is made with a...,AIXZKN4ACSKI,David Briner,"[0, 0]",This came in on time and I am veru happy with ...,5,Woks very good,1390694400,"01 26, 2014",0

In [177]:
# Lọc dữ liệu
df_filtered = df_meta_reviews_map[df_meta_reviews_map["reviewerID"] == "AIXZKN4ACSKI"][["asin", "title", "price", "imUrl", 'itemID']]

In [178]:
# Lấy string từ pandas
json_str = df_filtered.to_json(orient='records', force_ascii=False)

# Chuyển string thành list/dict object
json_obj = json.loads(json_str)

# Ghi ra file bằng thư viện json chuẩn
with open("a.json", "w", encoding="utf-8") as f:
    json.dump(json_obj, f, indent=4, ensure_ascii=False)

In [157]:
df_inter = pd.read_csv(r"..\data\sports\sports.inter", sep="\t")

In [158]:
df_inter.info()

<class 'pandas.DataFrame'>
RangeIndex: 296337 entries, 0 to 296336
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     296337 non-null  int64
 1   itemID     296337 non-null  int64
 2   rating     296337 non-null  float64
 3   timestamp  296337 non-null  int64
 4   x_label    296337 non-null  int64
dtypes: float64(1), int64(4)
memory usage: 11.3 MB

In [159]:
df_inter["x_label"].value_counts()

x_label
0    218409
2     40029
1     37899
Name: count, dtype: int64

In [179]:
df_inter[(df_inter["userID"] == 0)&(df_inter["x_label"] == 0)]

   userID  itemID  rating   timestamp  x_label
0       0   11981     2.0  1390694400        0
1       0   15852     5.0  1390694400        0
2       0   17787     3.0  1391990400        0
3       0       0     5.0  1390694400        0
4       0    3369     5.0  1405123200        0
5       0   13372     5.0  1391990400        0

In [181]:
# df_inter[(df_inter["userID"] == 0)&(df_inter["x_label"] == 1)]
df_inter[(df_inter["x_label"] == 1)]

        userID  itemID  rating   timestamp  x_label
6            0    5458     5.0  1405123200        1
24           1    4281     5.0  1321920000        1
46           2    7950     5.0  1329696000        1
47           2    9250     5.0  1366243200        1
53           3    6244     5.0  1294099200        1
...        ...     ...     ...         ...      ...
296311   35593   18341     5.0  1402531200        1
296316   35594   18083     1.0  1396742400        1
296325   35595   18346     5.0  1405468800        1
296330   35596   18311     5.0  1397001600        1
296335   35597   18317     5.0  1401753600        1

[37899 rows x 5 columns]

In [164]:
df_inter[(df_inter["userID"] == 0)&(df_inter["x_label"] == 2)]

   userID  itemID  rating   timestamp  x_label
7       0    3327     3.0  1391990400        2