# Lọc mấy tấm hình lấy ra train dựa theo dữ liệu đã filter 5 core
File df_inter.label.parquet, df_inter.parquet lấy ở bước 1 hoặc 2 điều được

In [3]:
import os
import pandas as pd

In [4]:
PATH = "../data/2023/"

In [10]:
df = pd.read_parquet(os.path.join(PATH, "df_meta.parquet"))

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35997 entries, 0 to 35996
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    35236 non-null  str
 1   title            35997 non-null  str
 2   average_rating   35997 non-null  float64
 3   rating_number    35997 non-null  int64
 4   features         35997 non-null  object
 5   description      35997 non-null  object
 6   price            17404 non-null  float64
 7   images           35997 non-null  object
 8   videos           35997 non-null  object
 9   store            35849 non-null  str
 10  categories       35997 non-null  object
 11  details          35997 non-null  object
 12  asin             35997 non-null  str
 13  bought_together  0 non-null      float64
 14  subtitle         0 non-null      float64
 15  author           0 non-null      object
dtypes: float64(4), int64(1), object(7), str(4)
memory usage: 9.1+ MB

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35997 entries, 0 to 35996
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   itemID           35997 non-null  int64
 1   asin             35997 non-null  str
 2   main_category    35997 non-null  str
 3   title            35997 non-null  str
 4   average_rating   35997 non-null  float64
 5   rating_number    35997 non-null  int64
 6   features         35997 non-null  object
 7   description      35997 non-null  object
 8   price            17404 non-null  float64
 9   images           35997 non-null  object
 10  videos           35997 non-null  object
 11  store            35997 non-null  str
 12  categories       35997 non-null  object
 13  details          35997 non-null  object
 14  bought_together  0 non-null      float64
 15  subtitle         0 non-null      float64
 16  author           0 non-null      object
 17  combined_text    35997 non-null  str
 18  sentences        35997 non-null  str
dtypes: float64(4), int64(2), object(7), str(6)
memory usage: 104.2+ MB

In [7]:
df.head()

,userID,itemID,rating,timestamp,reviewerID,asin,x_label
0,0,4,4,1655859477958,AEO4M665ZOCBF7HEFRMTUDHLSB5Q,B004JU0H6O,0
1,0,3,5,1655860079499,AEO4M665ZOCBF7HEFRMTUDHLSB5Q,B082WJTFRR,0
2,0,2,4,1655860597696,AEO4M665ZOCBF7HEFRMTUDHLSB5Q,B08FZJ3YHH,0
3,0,1,5,1655862402295,AEO4M665ZOCBF7HEFRMTUDHLSB5Q,B017IQZ9OK,1
4,0,0,3,1657839829629,AEO4M665ZOCBF7HEFRMTUDHLSB5Q,B086QM7FVT,2

In [40]:
df_5core = pd.read_csv("ratings_Baby_5core.csv", names=['userID', 'itemID', 'rating', 'timestamp'], header=None)

In [43]:
import polars as pl
import pandas as pd

# Get unique ASINs from the review data (Polars LazyFrame)
lazy_review_asins = lazy_df_review_2023.select(pl.col('asin')).unique()

# Get unique itemIDs from df_5core (Pandas DataFrame) and convert to Polars DataFrame
df_5core_itemids_pl = pl.DataFrame({'itemID': df_5core['itemID'].unique()})

# DF1: asin from lazy_df_review_2023 that exist in df_5core['itemID']
df_review_asins_in_5core = (
    lazy_review_asins.join(
        df_5core_itemids_pl.rename({'itemID': 'asin'}).lazy(), # Convert to LazyFrame for join
        on='asin',
        how='inner'
    )
    .collect()
)

print("ASINs from reviews also found in 5-core itemIDs:")
display(df_review_asins_in_5core)

ASINs from reviews also found in 5-core itemIDs:

shape: (4_353, 1)
┌────────────┐
│ asin       │
│ ---        │
│ str        │
╞════════════╡
│ B002OOWADU │
│ B004YU23IY │
│ B000SXSMYK │
│ B0032BEFPK │
│ B004071ZO4 │
│ …          │
│ B004A9ZF3Y │
│ B004CLYZ0O │
│ B00DK9C3IA │
│ B0032FOOQ6 │
│ B00005BMDX │
└────────────┘

In [44]:
# DF2: df_5core['itemID'] not existing in lazy_df_review_2023['asin']
df_5core_itemids_not_in_review = (
    df_5core_itemids_pl.lazy().join( # Convert to LazyFrame for join
        lazy_review_asins.rename({'asin': 'itemID'}).with_columns(pl.lit(True).alias('in_review')),
        on='itemID',
        how='left'
    )
    .filter(pl.col('in_review').is_null())
    .select(pl.col('itemID'))
    .collect()
)

print("ItemIDs from 5-core not found in review ASINs:")
display(df_5core_itemids_not_in_review)

ItemIDs from 5-core not found in review ASINs:

shape: (2_697, 1)
┌────────────┐
│ itemID     │
│ ---        │
│ str        │
╞════════════╡
│ B00000IZQI │
│ B00000J3LL │
│ B00002JXFI │
│ B00004C8S8 │
│ B00004TFLB │
│ …          │
│ B00IVNEGLW │
│ B00IVNEGOO │
│ B00J8B47ME │
│ B00JB2PJ72 │
│ B00JLI73ZM │
└────────────┘

In [46]:
4353+2697

7050

In [49]:
df_5core["itemID"].drop_duplicates().count()

np.int64(7050)

In [52]:
import polars as pl
import pandas as pd

# Get unique parent_asins from the meta data (Polars LazyFrame)
lazy_meta_parent_asins = lazy_df_meta_2023.select(pl.col('parent_asin')).unique()

# Get unique itemIDs from df_5core (Pandas DataFrame) and convert to Polars DataFrame
df_5core_itemids_pl = pl.DataFrame({'itemID': df_5core['itemID'].unique()})

# DF1: parent_asin from lazy_df_meta_2023 that exist in df_5core['itemID']
df_meta_parent_asins_in_5core = (
    lazy_meta_parent_asins.join(
        df_5core_itemids_pl.rename({'itemID': 'parent_asin'}).lazy(), # Convert to LazyFrame for join
        on='parent_asin',
        how='inner'
    )
    .collect()
)

print("Parent ASINs from meta also found in 5-core itemIDs:")
display(df_meta_parent_asins_in_5core)

Parent ASINs from meta also found in 5-core itemIDs:

shape: (3_443, 1)
┌─────────────┐
│ parent_asin │
│ ---         │
│ str         │
╞═════════════╡
│ B00AAIA8PE  │
│ B00003TL7P  │
│ B003B09V2Y  │
│ B001QKJ9SC  │
│ B000R9YXWA  │
│ …           │
│ B002LZX2BG  │
│ B000T9792O  │
│ B00318CLNM  │
│ B002OOWAB2  │
│ B00H8MSEWY  │
└─────────────┘

In [54]:
# Extract parent_asin values from df_meta_parent_asins_in_5core
parent_asins_in_5core_list = df_meta_parent_asins_in_5core['parent_asin'].to_list()

# Filter lazy_df_meta_2023 to get full columns for these parent_asins
df_meta_full_columns_in_5core = (
    lazy_df_meta_2023
    .filter(pl.col('parent_asin').is_in(parent_asins_in_5core_list))
    .collect()
)

print("Filtered metadata with parent_asins found in 5-core (first 5 rows):")
display(df_meta_full_columns_in_5core.head())

Filtered metadata with parent_asins found in 5-core (first 5 rows):

shape: (5, 17)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ main_categ ┆ title     ┆ average_r ┆ rating_nu ┆ … ┆ bought_to ┆ subtitle ┆ author    ┆ df_index │
│ ory        ┆ ---       ┆ ating     ┆ mber      ┆   ┆ gether    ┆ ---      ┆ ---       ┆ ---      │
│ ---        ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ struct[3] ┆ i64      │
│ str        ┆           ┆ f64       ┆ i64       ┆   ┆ f64       ┆          ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ Baby       ┆ Nuby      ┆ 4.4       ┆ 52        ┆ … ┆ null      ┆ null     ┆ null      ┆ 3        │
│            ┆ iMonster  ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Toddler   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Bowl      ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Baby       ┆ BabyKicks ┆ 4.6       ┆ 243       ┆ … ┆ null      ┆ null     ┆ null      ┆ 100      │
│            ┆ Natural & ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Organic   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ 10…       ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Baby       ┆ Hands     ┆ 3.3       ┆ 41        ┆ … ┆ null      ┆ null     ┆ null      ┆ 113      │
│            ┆ Free Brea ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ stpump    ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Bra Halt… ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Tools &    ┆ Cloud B   ┆ 3.7       ┆ 54        ┆ … ┆ null      ┆ null     ┆ null      ┆ 143      │
│ Home Impro ┆ Twilight  ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ vement     ┆ Ladybug   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Green     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Baby       ┆ Disney    ┆ 3.9       ┆ 119       ┆ … ┆ null      ┆ null     ┆ null      ┆ 316      │
│            ┆ Cars      ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Folding   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Potty     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Seat…     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴──────────┘

In [55]:
# Save the resulting DataFrame to a Parquet file
output_parquet_path = "filtered_meta_with_5core_asins.parquet"
df_meta_full_columns_in_5core.write_parquet(output_parquet_path)

print(f"DataFrame saved to {output_parquet_path}")

DataFrame saved to filtered_meta_with_5core_asins.parquet

In [58]:
# Optionally, copy to Google Drive
!cp "filtered_meta_with_5core_asins.parquet" "{PATH}/2014/filtered_meta_with_5core_asins.parquet"

In [59]:
df_meta_full_columns_in_5core

shape: (3_443, 17)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ main_categ ┆ title     ┆ average_r ┆ rating_nu ┆ … ┆ bought_to ┆ subtitle ┆ author    ┆ df_index │
│ ory        ┆ ---       ┆ ating     ┆ mber      ┆   ┆ gether    ┆ ---      ┆ ---       ┆ ---      │
│ ---        ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ struct[3] ┆ i64      │
│ str        ┆           ┆ f64       ┆ i64       ┆   ┆ f64       ┆          ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ Baby       ┆ Nuby      ┆ 4.4       ┆ 52        ┆ … ┆ null      ┆ null     ┆ null      ┆ 3        │
│            ┆ iMonster  ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Toddler   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Bowl      ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Baby       ┆ BabyKicks ┆ 4.6       ┆ 243       ┆ … ┆ null      ┆ null     ┆ null      ┆ 100      │
│            ┆ Natural & ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Organic   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ 10…       ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Baby       ┆ Hands     ┆ 3.3       ┆ 41        ┆ … ┆ null      ┆ null     ┆ null      ┆ 113      │
│            ┆ Free Brea ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ stpump    ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Bra Halt… ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Tools &    ┆ Cloud B   ┆ 3.7       ┆ 54        ┆ … ┆ null      ┆ null     ┆ null      ┆ 143      │
│ Home Impro ┆ Twilight  ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ vement     ┆ Ladybug   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Green     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ Baby       ┆ Disney    ┆ 3.9       ┆ 119       ┆ … ┆ null      ┆ null     ┆ null      ┆ 316      │
│            ┆ Cars      ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Folding   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Potty     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Seat…     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …        │
│ Baby       ┆ Blueberry ┆ 3.1       ┆ 27        ┆ … ┆ null      ┆ null     ┆ null      ┆ 215364   │
│            ┆ Coveralls ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Hook/Loop ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ …         ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ null       ┆ Vital     ┆ 3.0       ┆ 27        ┆ … ┆ null      ┆ null     ┆ null      ┆ 215588   │
│            ┆ Baby      ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Toddler   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Trainer   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Cup…      ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ null       ┆ Blueberry ┆ 3.0       ┆ 1         ┆ … ┆ null      ┆ null     ┆ null      ┆ 215615   │
│            ┆ Minky     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Diaper    ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Snaps, …  ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ null       ┆ The Gro   ┆ 4.6       ┆ 15        ┆ … ┆ null      ┆ null     ┆ null      ┆ 216911   │
│            ┆ Company   ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ grobag    ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Baby Sl…  ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│ null       ┆ Bright    ┆ 4.1       ┆ 765       ┆ … ┆ null      ┆ null     ┆ null      ┆ 217371   │
│            ┆ Starts    ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ See &     ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ Play Auto ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
│            ┆ …         ┆           ┆           ┆   ┆           ┆          ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴──────────┘

In [61]:
df_meta_2014 = pd.read_parquet("filtered_meta_with_5core_asins.parquet")

In [62]:
df_meta_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3443 entries, 0 to 3442
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    3338 non-null   object
 1   title            3443 non-null   object
 2   average_rating   3443 non-null   float64
 3   rating_number    3443 non-null   int64
 4   features         3443 non-null   object
 5   description      3443 non-null   object
 6   price            522 non-null    float64
 7   images           3443 non-null   object
 8   videos           3443 non-null   object
 9   store            3427 non-null   object
 10  categories       3443 non-null   object
 11  details          3443 non-null   object
 12  parent_asin      3443 non-null   object
 13  bought_together  0 non-null      float64
 14  subtitle         0 non-null      float64
 15  author           0 non-null      object
 16  df_index         3443 non-null   int64
dtypes: float64(4), int64(2), object(11)
memory usage: 457.4+ KB

In [53]:
# DF2: df_5core['itemID'] not existing in lazy_df_meta_2023['parent_asin']
df_5core_itemids_not_in_meta = (
    df_5core_itemids_pl.lazy().join( # Convert to LazyFrame for join
        lazy_meta_parent_asins.rename({'parent_asin': 'itemID'}).with_columns(pl.lit(True).alias('in_meta')),
        on='itemID',
        how='left'
    )
    .filter(pl.col('in_meta').is_null())
    .select(pl.col('itemID'))
    .collect()
)

print("ItemIDs from 5-core not found in meta parent ASINs:")
display(df_5core_itemids_not_in_meta)

ItemIDs from 5-core not found in meta parent ASINs:

shape: (3_607, 1)
┌────────────┐
│ itemID     │
│ ---        │
│ str        │
╞════════════╡
│ B00000IZQI │
│ B00000J3LL │
│ B00002JV9S │
│ B00002JXFI │
│ B000046S3W │
│ …          │
│ B00J3TVRSS │
│ B00J8B47ME │
│ B00JB2PJ72 │
│ B00JEV5UI8 │
│ B00JLI73ZM │
└────────────┘

## Read 2014 dataset

In [113]:
df_filtered_meta_5core_2014 = pd.read_parquet("filtered_meta_with_5core_asins.parquet")

In [114]:
df_filtered_meta_5core_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3443 entries, 0 to 3442
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    3338 non-null   object
 1   title            3443 non-null   object
 2   average_rating   3443 non-null   float64
 3   rating_number    3443 non-null   int64
 4   features         3443 non-null   object
 5   description      3443 non-null   object
 6   price            522 non-null    float64
 7   images           3443 non-null   object
 8   videos           3443 non-null   object
 9   store            3427 non-null   object
 10  categories       3443 non-null   object
 11  details          3443 non-null   object
 12  parent_asin      3443 non-null   object
 13  bought_together  0 non-null      float64
 14  subtitle         0 non-null      float64
 15  author           0 non-null      object
 16  df_index         3443 non-null   int64
dtypes: float64(4), int64(2), object(11)
memory usage: 457.4+ KB

In [76]:
!cp "{PATH}/2014/meta_Baby.json.gz" meta_Baby.json.gz

In [77]:
!gunzip meta_Baby.json.gz

In [81]:
df_5core.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160792 entries, 0 to 160791
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     160792 non-null  object
 1   itemID     160792 non-null  object
 2   rating     160792 non-null  float64
 3   timestamp  160792 non-null  int64
dtypes: float64(1), int64(1), object(2)
memory usage: 4.9+ MB

In [84]:
asin5core = set(df_5core["itemID"].unique())

In [85]:
len(asin5core)

7050

In [96]:
!cat meta_Baby.json | head

{'asin': '0188399313', 'categories': [['Baby']], 'description': 'Wee-Go Glass baby bottles by LifeFactory (Babylife) are designed to grow with your child. The included clear cover can also serve as an easy to hold cup. Twist on the solid cap (sold separately) and use your bottles for storing juice or snacks. Perfect for a lunchbox or traveling. The bright colored silicone sleeve (patent pending) helps to protect the bottle from breakage and provides a great gripping surface and tactile experience during feeding. The bottle and sleeve can be boiled or put in the dishwasher together. They can also go in the freezer, making breast milk storage simple.', 'title': 'Lifefactory 4oz BPA Free Glass Baby Bottles - 4-pack-raspberry and Lilac', 'price': 69.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/41SwthpdD9L._SX300_.jpg', 'brand': 'Lifefactory', 'related': {'also_bought': ['B002SG7K7A', 'B003CJSXW8', 'B004PW4186', 'B002O3JH9Q', 'B002O3NLIO', 'B004HGSU28'], 'also_viewed': ['B003CJSXW8', 'B0052QOL1Q', 'B004PW4186', 'B00EN0OLZ8', 'B00EN0OOQY', 'B0049YS46K', 'B00E64CBLM', 'B00F9YOOS6', 'B00AH9RPVQ', 'B00BCU2R7G', 'B002O3NLIO', 'B008NZ4X2K', 'B005NIDFEW', 'B00DKPJCH4', 'B00CZNGWWK', 'B00DAKJIQ4', 'B005CT55IQ', 'B0049YRJM0', 'B0071IEWD0', 'B00E64CA68', 'B00IUB3SKK', 'B00A7AA6XY', 'B001F50FFE', 'B002HU9EO4', 'B007HP11SQ', 'B009WPUMX4', 'B002O3JH9Q', 'B00F2FT3K6', 'B00I5CR35A', 'B00BCTY5EK', 'B002SG7K7A', 'B00F2FLU2U', 'B0062ZK0GQ', 'B002UOFR66', 'B0055LKQQ2', 'B00A0FGN8I', 'B00HMYCG2W', 'B00DHFLUO0', 'B0040HMPA2', 'B00I5CT9XE', 'B008B5MMNO', 'B00BQYVNGO', 'B00925WM28', 'B00BGKC3EY', 'B005Q3LSDO', 'B0038JDVCE', 'B0045I6IA4'], 'bought_together': ['B002SG7K7A', 'B003CJSXW8'], 'buy_after_viewing': ['B003CJSXW8', 'B0052QOL1Q', 'B004PW4186', 'B002SG7K7A']}}
{'asin': '0188399518', 'categories': [['Baby']], 'description': 'The Planet Wise Flannel Wipes are 10 super soft, color coordinated, high-quality wipes that fit perfectly into the Planet Wise Wipe PouchTM.', 'title': 'Planetwise Flannel Wipes', 'price': 15.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/41otjnA4OGL._SY300_.jpg', 'brand': 'Planet Wise', 'related': {'also_bought': ['B00G96N3YY', 'B003XSEV2O', 'B000138GNY', 'B005WWIE3G', 'B005WWI0DA', 'B005WWIMGA', 'B00DS4WPNK', 'B0039VCRPI', 'B001QIN6ME', 'B004GMGLN8', 'B00CJ2OWUG', 'B004BDNJW8', 'B003N0JXSO', 'B003X3R6TO', 'B002T5Q01C', 'B006J2U4T0', 'B00JBJDEC2', 'B00380LVLG', 'B00GJVM2NW', 'B003AJHDQW', 'B0043EDGP0', 'B0012IJBUE', 'B001OI0YWG', 'B005DL5970', 'B00305GSKS', 'B00CQ9UUK8', 'B002Y27PQ4', 'B00AH8J448', 'B00A3JXVZY', 'B00483GAJU', 'B001J6O6B8', 'B0019ID6G2', 'B005DL7LGM', 'B00APSYDXM', 'B004D5KJJA', 'B0021HR94K', '0757302661', 'B001HX4DNE'], 'also_viewed': ['B000138GNY', 'B00G96N3YY', 'B006J2U4T0', 'B00GLBR3C0', 'B0039VCRPI', 'B0012IJBUE', 'B001IA2XGK', 'B001R2L6PS', 'B003X3R6TO', 'B00DS4WPNK', 'B005WWIE3G', 'B004BDNJW8', 'B005WWIMGA', 'B005WWI0DA', 'B003XSEV2O', 'B004A5VGPE', 'B004A5TTGC', 'B00JBJDEC2', 'B004GMGLN8', 'B009W6PM9M', 'B004RGL9I0', 'B0040IWMTK', 'B00J3C0XC6', 'B00HO1HBC8', 'B00G96N18M', 'B00A3V0XDA', 'B0032AMM9M', 'B001QIN6ME', 'B00A3V0XEY', 'B00CIUAB40', 'B00J3C0Y1G', 'B005IPE0KI', 'B00L0W5B7Y', 'B00FZGLKQW', 'B00HBYOE3W', 'B004A5TT4O', 'B00B6KS578', 'B002HOQOMA', 'B004G792KW', 'B002UD6BZS', 'B002XVRKHK', 'B002HOQOUW', 'B002UD6C1Q', 'B00APSYDXM', 'B00H07AZ42', 'B002LZX2BG', 'B00BFQVZNO', 'B00EZKNVYS', 'B00DCLYYJW', 'B00AHG8H1Q', 'B002QZ64T8', 'B003N0JXSO', 'B003AJHDQW', 'B00DN9NW32', 'B00CHPJ0I4', 'B005WXMJUY', 'B00D4LFC3W'], 'bought_together': ['B00G96N3YY', 'B003XSEV2O'], 'buy_after_viewing': ['B000138GNY', 'B006J2U4T0', 'B00G96N3YY', 'B005WWIMGA']}}
{'asin': '0188399399', 'description': 'The Planet Wise Wipe PouchTM features our patent pending no-leak design so your wipes will stay moist and not wick into your diaper bag. Features a unique snap down design to eliminate wicking from the zipper area. Most standard size wipes will fit into our Wipe PouchTM perfectly! Pouches are made of the same high quality fabrics as our Wet Bags, this pouch will last and last. Pouches are anti-microbial too! After you are done with the baby years, keep this pouch to use for just about anything you need to transport: make-up, toiletries, anything. Made in the USA!', 'title': 'Planetwise Wipe Pouch', 'price': 10.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/61x8h9u6mxL._SY300_.jpg', 'related': {'also_bought': ['B005WWI0DA', 'B005WWIMGA', 'B006J2U4T0', 'B000138GNY', 'B003XSEV2O', 'B005WWIE3G', 'B00DS4WPNK', 'B0039VCRPI', 'B003GSLCOG', 'B0018B15FE', 'B002MN3JY2'], 'also_viewed': ['B005WWIMGA', 'B00G96N3YY', 'B00DAI76TC', 'B0067GKHVS', 'B005WWIE3G', 'B004RGL9I0', 'B000138GNY', 'B00JBJDEC2', 'B00CMCJ2AS', 'B005WWI0DA', 'B002UD6C16', 'B00E401FVU', 'B004GMGLN8', 'B0012IJBUE', 'B00BFQVZNO', 'B006J2U4T0', 'B000VV21G4', 'B002HOQOUW', 'B003X3R6TO', 'B000GZJIVQ', 'B0052AIF00', 'B005GQ6606', 'B003TZHCA4', 'B001QIN6ME', 'B003XSEV2O', 'B00GLBR3C0', 'B00DW9R03G', 'B00J3C0XC6', '0188399542', 'B00DQL6CIE', 'B002UD6C1G', 'B00A3V0XDA', 'B0039VCRPI', 'B00EZKNVYS', 'B006QRFDHQ', 'B00DS4WPNK', 'B00CQ9UUK8', 'B0087A2PKS', 'B00GGNICSW', 'B0037NXP18', 'B000YCNLSC', 'B00FJG945W', 'B00FZGLKQW', 'B004A5VGPE', 'B00D4LFC3W', 'B00G96N18M', 'B00439UNR4', 'B004A5TT4O', 'B005DL7LGM', 'B006SD2JUW', 'B006Z6HXYY', 'B006QRFDZI', 'B00I0P7VYK', 'B00AZWDM0I', 'B000ZKHVMU', 'B007799PGC', 'B00H58UNMU', 'B00JKUU3TE'], 'buy_after_viewing': ['B005WWIMGA', 'B00G96N3YY', 'B00DAI76TC', 'B0067GKHVS']}, 'categories': [['Baby']]}
{'asin': '0316967297', 'description': 'Hand crafted set includes 1 full quilt (76x86 inches) and 2 standard shams (20x26 inches). Face cloth and fill are 100 natural cotton. Prewashed for out of the bag comfort. Hand crafted with embroidery. Machine washable. Made in China', 'title': 'Annas Dream Full Quilt with 2 Shams', 'price': 109.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/51%2BZ1%2BNeukL._SY300_.jpg', 'related': {'also_viewed': ['B009LTER3W', 'B00575TI5Q', 'B004NSYYJI'], 'buy_after_viewing': ['B009LTER3W', 'B001MX5EE6', 'B00575TI5Q', 'B0029009TG']}, 'categories': [['Baby']]}
{'asin': '0615447279', 'categories': [['Baby']], 'description': 'Thumbuddy To Love- The Binky Fairy helps children give up pacifier sucking without the fuss and tears. The adorable book comes with a matching Binky Fairy puppet and just like the Tooth Fairy, the book is read the night before so children understand where thier pacifiers will go. They awake to find an adorable Binky Fairy puppet under thier pillow knowing  that the Binky Fairy came! Each book comes with a success chart and stickers. Winner of  the PTPA Awards (Parent Tested, Parent Approved). Recommended for ages 2-4.', 'title': "Stop Pacifier Sucking without tears with Thumbuddy To Love's Binky Fairy Puppet and Adorable Book", 'price': 16.95, 'imUrl': 'http://ecx.images-amazon.com/images/I/51RKKENlq%2BL._SY300_.jpg', 'brand': '', 'related': {'also_bought': ['0979670004', '1601310234', 'B005G172KE', '1575422573', '1905417896', 'B0044D0HA2', 'B001GQ2CPI'], 'also_viewed': ['0979670004', '1575422573', '1493535943', '0615273645', '1601310234', '0992616727', '0615273793', '0763623644', '1907152962', '0992616719', 'B0016ZX7AI', '0698400488', '1608442713', '0451416058', '1581176848', 'B0072CTECY', 'B005G172KE', 'B0016P8K3W', '0375822704', '0979201004', '0961478020', '160131048X', '1572245859'], 'bought_together': ['B005G172KE'], 'buy_after_viewing': ['0979670004', '1575422573', 'B005G172KE', '1493535943']}}
{'asin': '0670062049', 'description': "A baby can be put at risk with an unsafe pacifier and the possibility of loose bits of silicone. That's why they created the GumDrop. The GumDrop is a safe, soft topped pacifier that's already been designed to fit your baby's face - even in the face of tubes and cannulas, so you will never have to modify the shape. And its perfect for side-lying without the hard plastic bases of most other popular pacifiers. GumDrop rests comfortably against your baby's delicate skin, offering a silicone-covered, curved surface and a familiar nipple shape that babies love. Our GumDrops also come in a soothing Vanilla scent that can calm the fussiest of babies.", 'title': '5 Pink Gumdrops + One Pacifier Clip', 'price': 9.99, 'imUrl': 'http://ecx.images-amazon.com/images/I/41u7qILNIwL._SX300_.jpg', 'related': {'also_viewed': ['B005QPE0W8', 'B00AZWDLHM', 'B004IOHN8Q', 'B002GOHLVE', 'B00BGJIJ3Y'], 'buy_after_viewing': ['B005QPE0W8', 'B00AZWDLHM', 'B004323NHS', 'B00GL6CT7E']}, 'categories': [['Baby']]}
{'asin': '0705391752', 'description': "Overview\n\nInclude the beloved Peter Rabbit in memories of your baby's first years. Record important events, milestones, photos, baby prints and more. Adorned with a green velvet ribbon, this is a Memory Book you'll look back on for years to come!", 'title': "A Tale of Baby's Days with Peter Rabbit", 'price': 65.07, 'imUrl': 'http://ecx.images-amazon.com/images/I/51%2BNFdIlpuL._SY300_.jpg', 'related': {'also_viewed': ['B001AL7GOQ', '0723256837', '0723262845', 'B001ET7NEW', 'B001G5ZKA8', '0837880114', 'B004LE8T9U', 'B004LE8T9A', 'B00HWIWRSQ', 'B00IAIXTA2', 'B00AYZFM86', 'B002AX5IR0', 'B00IK1TYTE', 'B0034G5UZC', 'B004LE8TWM', 'B001G5ZQ7A', 'B003UYU0S0', 'B008POOY8M', 'B00EO4KNWI', 'B004BDOIYQ', '0723231575', 'B00AYZFGZA', 'B003GDNTEC', 'B00AYZFKME', 'B00HVELOMG', 'B00KF1ANS8', 'B00IPCZZWI', 'B00516GAW0', 'B0034G60MO', 'B005C3HFS0', 'B0017ODENI', 'B0054S6S5O', 'B004S3LXAG', 'B0017OBHGO', 'B00JRXFTEI', 'B000G82HAW', '1599620707', 'B001H9NUT6', '177036417X', '030746542X', 'B00CMFDVYI', '1452106509', '072325804X', 'B007JXRSD8', 'B00AYZFFQU', 'B004LE8TOA', 'B00HU6IXR4', '0811868117', 'B00IRBCH8M', 'B00IPCZNMU', 'B008W8YVRA', 'B001I0GTJM', 'B004HJSQ2O'], 'bought_together': ['0723256837'], 'buy_after_viewing': ['B001AL7GOQ', '0723256837', '0723262845', 'B00AYZFGZA']}, 'categories': [['Baby']]}
{'asin': '097293751X', 'categories': [['Baby']], 'description': "Easily keep track of your baby's or child's daily schedules, activities and needs in one handy spot.  And make the drop-off and pick-up process for childcare a snap.  The Baby Tracker Daily Childcare Journal is designed to make it fast and easy to record and review meals, naps, activities, playtime, daily news, milestones and to-dos ---all in a single page view.  Get ready for doctor visits, give to childcare helpers and use this easy at-a-glance daily record to monitor schedules and prep for your baby's daily needs.  This version records daily activities from 6 a.m. to 7 p.m. and creates a visual snapshot of activities by time each day.  \nThe Baby Tracker Daily Childcare Journal is ready to keep track of up to 6 months of daily schedule tracking (180 days) and is spiral bound to make it portable and lay flat for easy recording on a countertop or nightstand.Each journal includes:*180 daily at-a-glance tracking records (90 pages)* Key Contacts List* Medical Emergency Form and Instructions* Health Facts and Immunization Record* Printed on high quality, easy writing, bright white, 100% recycled paperBirth/3months to 3 years(**PLEASE NOTE: The Newborn Baby Tracker journal is also available for night AND day schedule tracking for nursing moms and 24-hour newborns.)MUST USE.  Pick up where the caregiver leaves off.  Now every nap and bottle can be chronicled with Baby Tracker, an at-a-glance charting system. -Working MotherKEEP TRACK OF BABY.  The Baby Tracker from Time Too is by far the simplest, most stylish, most no-nonsense planner we've seen. -American BabyFOR THE RECORD. Ask your caregiver to keep you apprised of your baby's daily activities while at work.  Baby Tracker journal makes it easy. - Child MagazineIPARENTING MEDIA AWARD Winner.  Top Product Award and Hot Pick,  Just for Mom Category.  - iParenting Media (a division of Disney.com)", 'title': 'Baby Tracker&reg; - Daily Childcare Journal, Schedule Log', 'price': 17.0, 'imUrl': 'http://ecx.images-amazon.com/images/I/41Bb6wf%2BqUL._SX300_.jpg', 'brand': 'Time Too', 'related': {'also_bought': ['9729375011', 'B004FN1AE8', 'B000V5KPZ4', 'B001F8TLLU', 'B005DLCJX2', 'B009TJ3J60', 'B00DFFT8JQ', 'B001PGKPNK', 'B00295MQLU', 'B00DFFT76U', 'B0095YYAW6', 'B004A9ZF3Y', 'B0057IQG4O', 'B00DDMJ332', 'B006XISCNA', '0778801748', 'B00389VFH2', 'B0038JDVCE', 'B00K5JFIEO', 'B00028XJNA', 'B005OI8O88', 'B00B1M2TUK', 'B000XPWXK2', 'B00DFFT9SQ', 'B002TLU5JO', 'B003XDLHIU', 'B0032CJPOK', 'B00DFFT9S6', 'B003KMW4EA', 'B00DFFT5HG', 'B00HU7DLBG', 'B000CCXLNE', '0449004023', '0865734348', 'B004TGVY9C', 'B0018JWAF0', 'B003KMWATY', 'B00AA7O4CS', 'B009M63NVG', 'B004QZBEFK', 'B003Y3BGYE', 'B002NUWQUM', 'B0045I6IA4', 'B00081J3N6', 'B002BVMKF4', 'B00DFFT77E', 'B000A88JYQ', 'B005UEB96K', '0976779811', 'B0009F3POY', 'B002KGHUL4', '0976779803', 'B004HM368U', 'B00171WXII', 'B002QYW8LW', 'B000RFC3BM', 'B000LSL5ZK', 'B000N0SNHY', 'B00DFFT5IU', 'B00DFFT8J6', 'B005KG7U16', '9491882007', 'B003E6OBMA', 'B004CK97A8', 'B00A6F2QJC', 'B001I481LM', 'B00ESN885O', 'B006Z6E8AG', 'B0031E1GEG', 'B0029O9WS6', 'B00IWOZZZQ', 'B0000BX8MT', 'B009R27JJC', 'B00DGN23UI', 'B00DB5F114', 'B00D3TPGB8', 'B004AHMCKA', 'B0046GJMVC', 'B00EYDECNU', 'B004DFO57M', 'B005E7K3LU', 'B00EFBHULW', 'B007Y8OOSU', 'B009F98SSS', 'B00G9NG14G', 'B00D2WFBC0', 'B003OQTPF8', 'B000096QQ5', 'B0018LRDIM', 'B0091E31KM', 'B004GCJMLG', 'B005F0CQ9I', 'B00HB0WKQY', 'B004323NHS', 'B000046S3W', 'B000JWSO9I', 'B006PASJAC', 'B002KCMSPQ', 'B0085CBA90'], 'also_viewed': ['9729375011', 'B004FN1ACK', '0976779803', 'B00K1FNSFI', '0976779811', 'B004TGVY9C', 'B00A1MG088', 'B00BS8IKYG', 'B004FN1AE8', '1450517528', 'B000V5KPZ4', 'B005CC2CCK', 'B001F8TLLU', '1419624970', '8862936206', '0976647958', 'B005B1E39C', '0345506499', '1584795018', '1908714050', 'B001KMAHYG', 'B00BS8IK7I', '1492339628', 'B00AXALTS4', 'B0012BS2O2', '1887169318', '1500287318', '0989326551', '0778801748', '1841722928', '0762427353', '030746542X', 'B00L63Q9UK', '0615797555', '0307719790', 'B001KMA868', '0740727303', '1441487867', 'B0046IGUY2', '1936061120', 'B004AVRZEY', '0615797474', '0972904549', '1936061007', '1438262094', '1427643474', 'B00IK1TZXO', '0976647915', 'B0034G5UZC', 'B0052LT50S', '1846012813', '157061508X', '0811829413', '0966480708', '1412758181', '1452106509', '1440422958', '0811874907', 'B004LE8TAE'], 'bought_together': ['9729375011', 'B001F8TLLU'], 'buy_after_viewing': ['9729375011', 'B001F8TLLU', 'B004FN1ACK', '0976779803']}}
{'asin': '0974671517', 'categories': [['Baby']], 'description': 'What should we call the Twins? uses an amusing play on words to create an entertaining board book for all ages. The high-contrast faces and colorful flairs cavtipate babies while the rhythmic language appeals to older children. What would you call the twins? You will be tickled by the names toddlers, and even grandparents, come up with.', 'title': 'Wee Gallery Twins Board Book', 'price': 3.58, 'imUrl': 'http://ecx.images-amazon.com/images/I/51lCiAJWfML._SY300_.jpg', 'brand': 'Wee Gallery', 'related': {'also_bought': ['0670013102', '0763637025', '1442430265', '0689844948', '1442430273', '1604627360', 'B0028LOQ5O'], 'also_viewed': ['0670013102', 'B000KN2YOM', 'B004U8XBFO', '0525420282', '0689844948', '1442430265', '0763644242', '0763637025', '1589258614', '1578565073', 'B00IIUZ88S', 'B004AVV0YK', 'B0028LOQ5O', 'B00AVX13A2', 'B004AVV194', 'B00274S8BA', 'B007NFTYYI', 'B00IIUMZ2K', 'B007K4U5KY', 'B00EYDECNU', 'B00IZWHI3M', '1442430273', 'B00AHVR4N8', 'B002LE74DE', 'B00EMG3Q18'], 'bought_together': ['0670013102', '0763637025'], 'buy_after_viewing': ['0670013102', 'B004U8XBFO', 'B000KN2YOM', '0525420282']}}
{'asin': '0980027519', 'imUrl': 'http://ecx.images-amazon.com/images/I/41NAMKmS8%2BL._SY300_.jpg', 'description': 'These adorable, high quality calendars are gender neutral and make a beautiful keepsake gift for any baby and parents.', 'categories': [['Baby']], 'title': "Nature's Lullabies First and Second Year Calendars"}

In [104]:
import ast
import os
import json

def fast_normalize(input_path, output_path, chunk_size=1000):
    print(f"Bắt đầu chuẩn hóa: {input_path}")

    with open(input_path, 'r', encoding='utf-8') as f_in, \
         open(output_path, 'w', encoding='utf-8') as f_out:

        buffer = []
        for line in f_in:
            line = line.strip()
            if not line: continue

            try:
                # ast.literal_eval nhanh và chuẩn hơn eval cho bài toán này
                data_dict = ast.literal_eval(line)
                buffer.append(json.dumps(data_dict) + '\n')

                # Khi đủ 1000 dòng thì ghi xuống ổ cứng 1 lần
                if len(buffer) >= chunk_size:
                    f_out.writelines(buffer)
                    buffer = []
            except:
                continue

        # Ghi nốt phần còn lại trong buffer
        if buffer:
            f_out.writelines(buffer)

    print(f"Hoàn thành! Đã lưu tại: {output_path}")
    print(f"Kích thước file mới: {os.path.getsize(output_path) / 1024 / 1024:.2f} MB")

In [105]:
fast_normalize("/content/meta_Baby.json", "/content/meta_Baby.jsonl")

Bắt đầu chuẩn hóa: /content/meta_Baby.json
Hoàn thành! Đã lưu tại: /content/meta_Baby.jsonl
Kích thước file mới: 105.82 MB

In [106]:
df_meta_2014 = pd.read_json("meta_Baby.jsonl", lines=True)

In [107]:
df_meta_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71317 entries, 0 to 71316
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         71317 non-null  object
 1   categories   71317 non-null  object
 2   description  65642 non-null  object
 3   title        71241 non-null  object
 4   price        57741 non-null  float64
 5   imUrl        71243 non-null  object
 6   brand        27858 non-null  object
 7   related      58721 non-null  object
 8   salesRank    36 non-null     object
dtypes: float64(1), object(8)
memory usage: 4.9+ MB

In [108]:
df_meta_5core_2014 = df_meta_2014[df_meta_2014["asin"].isin(asin5core)].copy()

In [109]:
df_meta_5core_2014.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7050 entries, 7 to 71289
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         7050 non-null   object
 1   categories   7050 non-null   object
 2   description  6956 non-null   object
 3   title        7037 non-null   object
 4   price        6883 non-null   float64
 5   imUrl        7037 non-null   object
 6   brand        4926 non-null   object
 7   related      6946 non-null   object
 8   salesRank    4 non-null      object
dtypes: float64(1), object(8)
memory usage: 550.8+ KB

In [110]:
df_meta_5core_2014.to_parquet("df_meta_5core_2014.parquet")

In [111]:
!cp df_meta_5core_2014.parquet "{PATH}/2014/df_meta_5core_2014.parquet"

In [116]:
df_meta_5core_2014

,asin,categories,description,title,price,imUrl,brand,related,salesRank
7,097293751X,[[Baby]],Easily keep track of your baby's or child's da...,"Baby Tracker&reg; - Daily Childcare Journal, S...",17.00,http://ecx.images-amazon.com/images/I/41Bb6wf%...,Time Too,"{'also_bought': ['9729375011', 'B004FN1AE8', '...",NaN
108,9729375011,[[Baby]],This is version of the award-winningBaby Track...,Newborn Baby Tracker&reg; - Round the Clock Ch...,15.95,http://ecx.images-amazon.com/images/I/51r3BLpL...,NaN,"{'also_bought': ['B000V5KPZ4', 'B001F8TLLU', '...",NaN
134,B00000IZQI,[[Baby]],This colorful car collection develops motor sk...,Fisher Price Nesting Action Vehicles,8.37,http://ecx.images-amazon.com/images/I/51E83QCC...,NaN,"{'also_bought': ['B0042D69W4', 'B00428LIZM', '...",NaN
144,B00000J3LL,[[Baby]],This darling cloth book offers hands-on experi...,"My Quiet Book, Fabric Activity Book for Children",27.00,http://ecx.images-amazon.com/images/I/51GoNXhB...,NaN,"{'also_bought': ['B00000J3LC', 'B0043G4JOA', '...",NaN
163,B00002JV9S,[[Baby]],"In a relatively new concept in teething, The F...",The First Years Massaging Action Teether,8.84,http://ecx.images-amazon.com/images/I/41gVp98n...,The First Years,"{'also_bought': ['B0013FCBJO', 'B0019QCGVK', '...",NaN
...,...,...,...,...,...,...,...,...,...
70839,B00JEV5UI8,[[Baby]],,VTech Communications Safe and Sound Digital Au...,19.99,http://ecx.images-amazon.com/images/I/41KvPcQ-...,NaN,"{'also_bought': ['B007INU6EC', 'B00BRHSD90', '...",NaN
70927,B00JLI73ZM,[[Baby]],Parents dont vibrate like bouncy seats or swin...,4Moms mamaRoo Plush Infant Seat - Silver,249.00,http://ecx.images-amazon.com/images/I/41-lfZws...,4moms,"{'also_bought': ['B007ZXX03Y', 'B00BXWTVJ0', '...",NaN
70930,B00JLHWDO4,[[Baby]],Baby's weight is supported by buttocks and upp...,Merry Muscles Ergonomic Jumper Exerciser Baby ...,89.95,http://ecx.images-amazon.com/images/I/41Z5Is6e...,NaN,"{'also_bought': ['B003I1XA0U', 'B008BGNT3A', '...",NaN
71006,B00JRYRYS6,[[Baby]],NaN,"Graco Argos 65 3-in-1 Harness Booster, Link",199.99,http://ecx.images-amazon.com/images/I/41vnR97a...,Graco,"{'also_bought': ['B00H8MSKAU', 'B00HG699OO', '...",NaN
71289,B00L13XFIE,[[Baby]],The stay dry insert consists of 4 layers of su...,"Best Bottom Stay Dry Inserts, Large, 3 Count",12.55,http://ecx.images-amazon.com/images/I/41gFQtfe...,bestbottom,"{'also_bought': ['B00A3JXVZY', 'B007NIFFHA', '...",NaN

In [121]:
df_meta_5core_2014.columns

Index(['asin', 'categories', 'description', 'title', 'price', 'imUrl', 'brand',
       'related', 'salesRank'],
      dtype='object')

In [119]:
df_meta_5core_2014["imUrl"]

7        http://ecx.images-amazon.com/images/I/41Bb6wf%...
108      http://ecx.images-amazon.com/images/I/51r3BLpL...
134      http://ecx.images-amazon.com/images/I/51E83QCC...
144      http://ecx.images-amazon.com/images/I/51GoNXhB...
163      http://ecx.images-amazon.com/images/I/41gVp98n...
                               ...
70839    http://ecx.images-amazon.com/images/I/41KvPcQ-...
70927    http://ecx.images-amazon.com/images/I/41-lfZws...
70930    http://ecx.images-amazon.com/images/I/41Z5Is6e...
71006    http://ecx.images-amazon.com/images/I/41vnR97a...
71289    http://ecx.images-amazon.com/images/I/41gFQtfe...
Name: imUrl, Length: 7050, dtype: object

In [120]:
df_filtered_meta_5core_2014["images"]

0       [{'hi_res': 'https://m.media-amazon.com/images...
1       [{'hi_res': None, 'large': 'https://m.media-am...
2       [{'hi_res': None, 'large': 'https://m.media-am...
3       [{'hi_res': 'https://m.media-amazon.com/images...
4       [{'hi_res': 'https://m.media-amazon.com/images...
                              ...
3438    [{'hi_res': None, 'large': 'https://m.media-am...
3439    [{'hi_res': 'https://m.media-amazon.com/images...
3440    [{'hi_res': None, 'large': 'https://m.media-am...
3441    [{'hi_res': 'https://m.media-amazon.com/images...
3442    [{'hi_res': 'https://m.media-amazon.com/images...
Name: images, Length: 3443, dtype: object

In [122]:
df_filtered_found = df_meta_5core_2014[df_meta_5core_2014["asin"].isin(set(df_filtered_meta_5core_2014["parent_asin"]))]

In [123]:
df_filtered_found.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3443 entries, 7 to 71289
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         3443 non-null   object
 1   categories   3443 non-null   object
 2   description  3400 non-null   object
 3   title        3437 non-null   object
 4   price        3356 non-null   float64
 5   imUrl        3437 non-null   object
 6   brand        2335 non-null   object
 7   related      3394 non-null   object
 8   salesRank    0 non-null      object
dtypes: float64(1), object(8)
memory usage: 269.0+ KB

## Read jonl

In [16]:
reviews_chunks = pd.read_json(os.path.join(PATH, "2023/Baby_Products.jsonl"), lines=True, chunksize=100_000)

In [17]:
!cp "{PATH}/2023/Baby_Products.jsonl" "Baby_Products.jsonl"

In [31]:
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa
import os
import gc

def convert_jsonl_to_parquet_snappy(jsonl_path, parquet_path, chunk_size=100_000):
    """
    Chuyển đổi file JSONL sang Parquet với nén Snappy để tránh crash RAM.
    """
    # Khởi tạo reader theo từng cụm (chunk)
    reviews_chunks = pd.read_json(jsonl_path, lines=True, chunksize=chunk_size)

    writer = None

    print(f"Bắt đầu chuyển đổi: {jsonl_path} -> {parquet_path}")

    try:
        for i, chunk in enumerate(reviews_chunks):
            # 1. Ép kiểu object (thường là string/mixed) sang string thuần
            # Việc này giúp tránh lỗi không đồng nhất kiểu dữ liệu (Schema mismatch) trong Parquet
            for col in chunk.select_dtypes(include=['object']).columns:
                chunk[col] = chunk[col].astype(str)

            # 2. Chuyển sang bảng Arrow
            table = pa.Table.from_pandas(chunk)

            # 3. Khởi tạo writer ở vòng lặp đầu tiên với nén Snappy
            if writer is None:
                writer = pq.ParquetWriter(parquet_path, table.schema, compression='snappy')

            # 4. Ghi chunk hiện tại vào file
            writer.write_table(table)

            # 5. Dọn dẹp bộ nhớ ngay lập tức
            del chunk
            del table
            gc.collect()

            print(f"--- Đã xử lý xong chunk {i+1} ({((i+1)*chunk_size):,}) dòng ---")

    except Exception as e:
        print(f"Lỗi trong quá trình chuyển đổi: {e}")

    finally:
        # Đảm bảo đóng file dù có lỗi xảy ra hay không
        if writer:
            writer.close()
            print(f"\n[XONG] File Parquet Snappy đã được lưu tại: {parquet_path}")

# --- Cách sử dụng ---
# convert_jsonl_to_parquet_snappy("Baby_Products.jsonl", "Baby_Products.parquet")

In [30]:
!ls -lh

total 4.3G
-rw------- 1 root root 2.8G Mar 27 08:04 Baby_Products.jsonl
-rw-r--r-- 1 root root 1.1G Mar 27 08:06 Baby_Products.parquet
-rw------- 1 root root 167M Mar 27 07:54 df_meta_2023.gzip.parquet
-rw-r--r-- 1 root root 265M Mar 27 08:11 df_meta_2023.parquet
drwx------ 5 root root 4.0K Mar 27 07:51 drive
drwxr-xr-x 1 root root 4.0K Mar 23 13:29 sample_data

In [20]:
!cp Baby_Products.parquet "{PATH}/2023/Baby_Products.parquet"

In [29]:
!cp df_meta_2023.parquet "{PATH}/2023/df_meta_2023.parquet"