# Dọn dữ liệu có sẵn của thư mục BM3

## Tham khảo file preprocessing_v2\image\FilterData2014.ipynb, để có file df_meta_5core_2014.parquet

In [ ]:
# %pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.6 MB 8.3 MB/s eta 0:00:04
   ----------- ---------------------------- 8.1/27.6 MB 31.5 MB/s eta 0:00:01
   --------------------- ------------------ 14.7/27.6 MB 29.7 MB/s eta 0:00:01
   ----------------------------- ---------- 20.2/27.6 MB 28.3 MB/s eta 0:00:01
   ---------------------------------- ----- 24.1/27.6 MB 26.8 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.6 MB 24.8 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 21.9 MB/s  0:00:01
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
import pandas as pd

In [2]:
PATH = "./data/2014"

In [3]:
df_meta = pd.read_parquet(os.path.join(PATH, "df_meta_5core_2014.parquet"))

In [4]:
df_meta.info()

<class 'pandas.DataFrame'>
Index: 7050 entries, 7 to 71289
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         7050 non-null   str
 1   categories   7050 non-null   object
 2   description  6956 non-null   str
 3   title        7037 non-null   str
 4   price        6883 non-null   float64
 5   imUrl        7037 non-null   str
 6   brand        4926 non-null   str
 7   related      6946 non-null   object
 8   salesRank    4 non-null      object
dtypes: float64(1), object(3), str(5)
memory usage: 4.9+ MB

In [5]:
df_meta.head(3)

,asin,categories,description,title,price,imUrl,brand,related,salesRank
7,097293751X,[[Baby]],Easily keep track of your baby's or child's da...,"Baby Tracker&reg; - Daily Childcare Journal, S...",17.00,http://ecx.images-amazon.com/images/I/41Bb6wf%...,Time Too,"{'also_bought': ['9729375011', 'B004FN1AE8', '...",None
108,9729375011,[[Baby]],This is version of the award-winningBaby Track...,Newborn Baby Tracker&reg; - Round the Clock Ch...,15.95,http://ecx.images-amazon.com/images/I/51r3BLpL...,NaN,"{'also_bought': ['B000V5KPZ4', 'B001F8TLLU', '...",None
134,B00000IZQI,[[Baby]],This colorful car collection develops motor sk...,Fisher Price Nesting Action Vehicles,8.37,http://ecx.images-amazon.com/images/I/51E83QCC...,NaN,"{'also_bought': ['B0042D69W4', 'B00428LIZM', '...",None

In [6]:
df_meta_to_drop = df_meta[df_meta["imUrl"].isna()].copy()
df_meta_to_drop.shape

(13, 9)

In [7]:
# Bỏ các dòng bị thiếu ảnh
df_meta.dropna(subset=["imUrl"], inplace=True)

In [8]:
df_meta.shape

(7037, 9)

In [9]:
df_meta.info()

<class 'pandas.DataFrame'>
Index: 7037 entries, 7 to 71289
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         7037 non-null   str
 1   categories   7037 non-null   object
 2   description  6956 non-null   str
 3   title        7037 non-null   str
 4   price        6883 non-null   float64
 5   imUrl        7037 non-null   str
 6   brand        4926 non-null   str
 7   related      6946 non-null   object
 8   salesRank    4 non-null      object
dtypes: float64(1), object(3), str(5)
memory usage: 4.9+ MB

In [21]:
## Ghi ra lại file
df_meta.to_parquet(os.path.join(PATH, "clean/df_meta.parquet"), index=False)

## Sửa file có sẵn của BM3 (Không sửa được rồi phải làm lại từ bước từ csv -> .inter vì index mất vài dòng)

In [10]:
df_inter = pd.read_csv(os.path.join(PATH, "baby.inter"), sep="\t")

In [11]:
df_inter.info()

<class 'pandas.DataFrame'>
RangeIndex: 160792 entries, 0 to 160791
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     160792 non-null  int64
 1   itemID     160792 non-null  int64
 2   rating     160792 non-null  float64
 3   timestamp  160792 non-null  int64
 4   x_label    160792 non-null  int64
dtypes: float64(1), int64(4)
memory usage: 6.1 MB

In [12]:
df_inter.head(3)

   userID  itemID  rating   timestamp  x_label
0       0    1587     5.0  1373932800        0
1       0    1879     5.0  1373932800        0
2       0       0     5.0  1373932800        0

In [13]:
df_i_id_map = pd.read_csv(os.path.join(PATH, "i_id_mapping.csv"), sep="\t")

In [14]:
df_i_id_map.info()

<class 'pandas.DataFrame'>
RangeIndex: 7050 entries, 0 to 7049
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   asin    7050 non-null   str
 1   itemID  7050 non-null   int64
dtypes: int64(1), str(1)
memory usage: 179.1 KB

In [15]:
df_i_id_map.head(3)

         asin  itemID
0  097293751X       0
1  9729375011       1
2  B00000IZQI       2

In [16]:
df_inter_map_i_id = df_inter.merge(df_i_id_map, how="inner", on="itemID")

In [17]:
df_inter_map_i_id.info()

<class 'pandas.DataFrame'>
RangeIndex: 160792 entries, 0 to 160791
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     160792 non-null  int64
 1   itemID     160792 non-null  int64
 2   rating     160792 non-null  float64
 3   timestamp  160792 non-null  int64
 4   x_label    160792 non-null  int64
 5   asin       160792 non-null  str
dtypes: float64(1), int64(4), str(1)
memory usage: 8.9 MB

In [18]:
## Bỏ các dòng có asin trong df_meta_to_drop
df_inter_map_i_id = df_inter_map_i_id[
    ~df_inter_map_i_id["asin"].isin(set(df_meta_to_drop["asin"]))
].copy()

In [19]:
df_inter_map_i_id.info()

<class 'pandas.DataFrame'>
Index: 160522 entries, 0 to 160791
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     160522 non-null  int64
 1   itemID     160522 non-null  int64
 2   rating     160522 non-null  float64
 3   timestamp  160522 non-null  int64
 4   x_label    160522 non-null  int64
 5   asin       160522 non-null  str
dtypes: float64(1), int64(4), str(1)
memory usage: 10.1 MB

In [20]:
160792 - 160522

270

In [22]:
df_inter_map_i_id

        userID  itemID  rating   timestamp  x_label        asin
0            0    1587     5.0  1373932800        0  B0013FGWD0
1            0    1879     5.0  1373932800        0  B001DKHPD6
2            0       0     5.0  1373932800        0  097293751X
3            0    1922     5.0  1363996800        1  B001F8TLLU
4            0    3870     4.0  1357689600        2  B004071ZOY
...        ...     ...     ...         ...      ...         ...
160787   19444    7022     5.0  1393804800        0  B00I3WEXPU
160788   19444    6959     5.0  1394064000        0  B00GRS9YQK
160789   19444    7005     5.0  1396310400        0  B00HPQT9MC
160790   19444    7023     4.0  1394668800        1  B00I3WEXUA
160791   19444    6994     5.0  1393632000        2  B00HE66NN6

[160522 rows x 6 columns]